context-menu-play = נגן
context-menu-rewind = אחורה
context-menu-forward = קדימה
context-menu-back = חזרה
context-menu-quality-low = איכות: נמוכה
context-menu-quality-medium = איכות: בינונית
context-menu-quality-high = איכות: גבוהה
context-menu-cut = גזור
context-menu-copy = העתק
context-menu-paste = הדבק
context-menu-delete = מחק
context-menu-select-all = בחר הכל
