about-ruffle = Ruffle hakkında
about-ruffle-version = Sürüm
about-ruffle-channel = Kanal
about-ruffle-build-time = Yükl. tarihi
about-ruffle-build-features = Yapımın Özellk.
about-ruffle-commit-ref = İşlem kaynağı
about-ruffle-commit-time = İşleme tarihi
about-ruffle-visit-website = İnt. sitesi
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Destekle
