about-ruffle = Ruffle Hakkında
about-ruffle-version = Sürüm
about-ruffle-channel = Kanal
about-ruffle-build-time = Yükl. Tarihi
about-ruffle-build-features = Yapımın Özellk.
about-ruffle-commit-ref = İşlem Kaynağı
about-ruffle-commit-time = İşleme Tarihi
about-ruffle-visit-website = İnt. Sitesi
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Destekle
