file-picker-title-open-file = Tek bir dosyayı aç
file-picker-title-open-directory = Bir klasör aç
file-picker-filter-supported = Desteklenen Tüm Dosyalar
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Ruffle paketi (*.ruf)
file-picker-filter-all = Tüm dosyalar
file-picker-select-root-movie-title = Kök filmi seç
file-picker-select-root-movie-message = Açılan klasörden kök filmi seç.
file-picker-select-root-movie-select = Seç
