preferences-dialog = Ruffle Tercihleri
preference-locked-by-cli = Salt-Okunur (CLI tarafından ayarlanır)
graphics-backend = Grafik Altyapısı
graphics-backend-default = Varsayılan
graphics-power = Güç Tercihi
graphics-power-low = Düşük (örn. iGPU)
graphics-power-high = Yüksek (örn. GPU)
language = Dil
audio-output-device = Ses Çıkış Aygıtı
audio-output-device-default = Sistem Varsayılanı
enable-openh264 = OpenH264 Etkinleşir
show-license = Lisansı Göster
openh264-license = OpenH264 Lisansı
log-filename-pattern = Günlük Dosya Adı
log-filename-pattern-single-file = Tekli Dosya (ruffle.log)
log-filename-pattern-with-timestamp = Zaman Damgalı
storage-backend = Kayıt Dosyası Konumu
storage-backend-disk = Disk
storage-backend-memory = Bellek
recent-limit = En sonki Limit
recent-clear = Temizle
theme = Tema
theme-system = Sistem Varsayılanı
theme-light = Aydınlık
theme-dark = Karanlık
