preferences-dialog = Ruffle Tercihleri
preference-locked-by-cli = Salt-Okunur (CLI tarafından ayarlandı)
graphics-backend = Grafik API'sı
graphics-backend-default = Varsayılan
graphics-power = Güç Tercihi
graphics-power-low = Düşük (örn. iGPU)
graphics-power-high = Yüksek (örn. GPU)
language = Dil
audio-output-device = Ses Çıkış Aygıtı
audio-output-device-default = Sistem Varsayılanı
log-filename-pattern = Günlük Dosya Adı
log-filename-pattern-single-file = Tekli Dosya (ruffle.log)
log-filename-pattern-with-timestamp = Tekli Dosya (ruffle.log)
storage-backend = Kayıt dosyası yeri
storage-backend-disk = Disk
storage-backend-memory = Bellek
recent-clear = Temizle
