network-settings = Ağ Ayarları
player-settings = Oyuncu Ayarları
movie-parameters = Film Parametreleri
custom-base-url = Özel Temel URL
spoof-swf-url = Sahte SWF URL'si
proxy = Vekil Sunucu
upgrade-http = HTTP'yi HTTPS'e Yükselt
upgrade-http-check = Yükselt
open-url-mode = URL Modunu Aç
open-url-mode-allow = İzin Ver
open-url-mode-confirm = Onayla
open-url-mode-deny = Reddet
load-behavior = Yükleme Davranışı
load-behavior-streaming = Yayın Akışı
load-behavior-delayed = Gecikmeli
load-behavior-blocking = Engelleme
max-execution-duration = Maksimum Yürütme Süresi
max-execution-duration-suffix = { " " } saniye
quality = Kalite
quality-low = Düşük
quality-medium = Orta
quality-high = Yüksek
quality-best = En İyi
quality-high8x8 = Yüksek (8x8)
quality-high8x8linear = Yüksek (8x8) Doğrusal
quality-high16x16 = Yüksek (16x16)
quality-high16x16linear = Yüksek (16x16) Doğrusal
align = Sahne Hizalaması
align-center = Ortala
align-left = Solda
align-right = Sağda
align-top = Üstte
align-bottom = Altta
align-top-left = Sol Üstte
align-bottom-left = Sol Altta
align-top-right = Sağ Üstte
align-bottom-right = Sağ Altta
align-force = Zorla
scale-mode = Ölçek Modu
scale-mode-exactfit = Tam Uyum
scale-mode-noborder = Kenarlık Yok
scale-mode-noscale = Ölçeksiz
scale-mode-showall = Tümünü Göster
scale-mode-force = Zorla
player-version = Oynatma Sürümü
custom-framerate = Özel Kare Hızı
custom-framerate-suffix = { " " } fps
dummy-external-interface = Sahte Harici Arayüz
dummy-external-interface-check = Etkin
