// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/printing/PrintJobOptions.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.printing {
    public class PrintJobOptions {
        // Specifies whether the content in the print job is printed as a bitmap or as a vector.
        public var printAsBitmap: Boolean;

        public function PrintJobOptions(printAsBitmap:Boolean = false)
        {
            this.printAsBitmap = printAsBitmap;
        }
    }
}
