// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/ClipboardTransferMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.desktop
{

    public class ClipboardTransferMode
    {
        // The Clipboard object should only return a copy.
        public static const CLONE_ONLY:String = "cloneOnly";

        // The Clipboard object should return a copy if available and a reference if not.
        public static const CLONE_PREFERRED:String = "clonePreferred";

        // The Clipboard object should only return a reference.
        public static const ORIGINAL_ONLY:String = "originalOnly";

        // The Clipboard object should return a reference if available and a copy if not.
        public static const ORIGINAL_PREFERRED:String = "originalPreferred";

    }
}
