// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/ClipboardFormats.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.desktop
{

    public class ClipboardFormats
    {
        // HTML data.
        public static const HTML_FORMAT:String = "air:html";

        // Rich Text Format data.
        public static const RICH_TEXT_FORMAT:String = "air:rtf";

        // String data.
        public static const TEXT_FORMAT:String = "air:text";

    }
}
