// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/Icon.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.desktop
{
  import flash.events.EventDispatcher;
  [API("661")]
  public class Icon extends EventDispatcher
  {

    // The icon image as an array of BitmapData objects of different sizes.
    public var bitmaps:Array;

    function Icon() {}
  }
}
