// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/InteractiveIcon.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.desktop
{
  import __ruffle__.stub_getter;

  [API("661")]
  public class InteractiveIcon extends Icon
  {
    public function get height():int
    {
      stub_getter("flash.desktop.InteractiveIcon", "height");
      return 64;
    }

    public function get width():int
    {
      stub_getter("flash.desktop.InteractiveIcon", "width");
      return 64;
    }
  }
}
