context-menu-play = Pokrenite
context-menu-rewind = Premotaj unazad
context-menu-forward = Napred
context-menu-back = Nazad
context-menu-quality-low = Kvalitet: nizak
context-menu-quality-medium = Kvalitet: srednji
context-menu-quality-high = Kvalitet: visok
context-menu-cut = Iseci
context-menu-copy = Kopija
context-menu-paste = Zalepi
context-menu-delete = Obriši
context-menu-select-all = Izaberi sve
