export-bundle-dialog-title = ייצוא חבילת Ruffle
export-bundle-dialog-bundle-name = שם החבילה:
export-bundle-dialog-files-description = בחר קבצים שייכללו בחבילה:
export-bundle-dialog-files-select-all = בחר הכול
export-bundle-dialog-export = ייצוא
export-bundle-dialog-exporting = מייצא...
export-bundle-dialog-exporting-failed = הייצוא נכשל.
export-bundle-dialog-error-user-canceled = הפעולה בוטלה על ידי המשתמש.
export-bundle-dialog-error-failed-to-show-picker = לא ניתן להציג את בורר הקבצים.
export-bundle-dialog-error-io-error = אירעה שגיאה בעת כתיבת החבילה.
export-bundle-dialog-info-title = מהי חבילת Ruffle?
export-bundle-dialog-info-description = חבילת Ruffle היא חבילה אוניברסלית הכוללת את כל הדרוש להפעלת קובץ SWF, כולל כל המשאבים וההגדרות הנדרשים. באמצעות חבילה, קובץ ה SWF שלך מוכן לפעולה מיד, ללא קבצים חסרים וללא צורך בהגדרה ידנית. פשוט מפעילים וזה עובד.
