preferences-dialog = העדפות עבור Ruffle
preference-locked-by-cli = לקריאה בלבד (הוגדר על ידי ממשק שורת הפקודות)
graphics-backend = גרפיקת צד שרת
graphics-backend-default = ברירת מחדל
graphics-power = העדפות צריכת כוח
graphics-power-low = נמוך (לדוגמא; יחידת עיבוד גרפית משולבת)
graphics-power-high = גבוה (לדוגמא; יחידת עיבוד גרפי)
language = שפה
audio-output-device = התקן פלט שמע
audio-output-device-default = ברירת מחדל של המערכת
enable-openh264 = הפעלת OpenH264
show-license = הצג רשיונות
openh264-license = רישיון OpenH264
log-filename-pattern = שמו של קובץ רישום הנתונים
log-filename-pattern-single-file = קובץ יחיד (ruffle.log)
log-filename-pattern-with-timestamp = כולל חותמת זמן
storage-backend = שמור מיקום קובץ
storage-backend-disk = דיסק
storage-backend-memory = זיכרון
recent-limit = מגבלה אחרונה
recent-clear = מחיקה
