network-settings = הגדרות רשת
player-settings = הגדרות שחקן
movie-parameters = משתני הסרט
custom-base-url = כתובת בסיס אתר מותאמת אישית
spoof-swf-url = זיוף כתובת SWF
proxy = פרוקסי
upgrade-http = שדרג מ-HTTP ל-HTTPS
upgrade-http-check = שדרג
open-url-mode = פתח מצב כתובת URL
open-url-mode-allow = אפשר
open-url-mode-confirm = אישור
open-url-mode-deny = דחה
load-behavior = טען תצורה
load-behavior-streaming = הסטרמה
load-behavior-delayed = דיליי
load-behavior-blocking = חסימה
max-execution-duration = משך זמן ביצוע מירבי
max-execution-duration-suffix = { " " } שניות
quality = איכות
quality-low = נמוכה
quality-medium = בינונית
quality-high = גבוהה
quality-best = הטובה ביותר
quality-high8x8 = גבוהה (8x8)
quality-high8x8linear = גבוהה (8x8) לינארית
quality-high16x16 = גבוהה (16x16)
quality-high16x16linear = גבוהה (16x16) לינארית
scale-mode = מצב קנה-מידה
scale-mode-exactfit = התאמה מדויקת
scale-mode-noborder = ללא מסגרת
scale-mode-noscale = ללא קנה-מידה
scale-mode-showall = הצג הכול
warn-if-unsupported = אזהר אם אינו נתמך
warn-if-unsupported-check = אזהר
player-version = גרסת שחקן
custom-framerate = קצב פריימים מותאם אישית
custom-framerate-suffix = { " " } פריימים לשנייה
