network-settings = הגדרות רשת
player-settings = הגדרות שחקן
movie-parameters = משתני הסרט
custom-base-url = כתובת בסיס אתר מותאמת אישית
spoof-swf-url = זיוף כתובת SWF
referer-url = כתובת אתר מפנה
cookie = עוגיות
proxy = פרוקסי
upgrade-http = שדרג מ-HTTP ל-HTTPS
tcp-connections = חיבורי TCP
tcp-connections-allow = אפשר
tcp-connections-ask = שאל
tcp-connections-deny = סרב
open-url-mode = פתח קישורים
open-url-mode-allow = אפשר
open-url-mode-confirm = שאל
open-url-mode-deny = דחה
load-behavior = טען תצורה
load-behavior-streaming = הסטרמה
load-behavior-delayed = דיליי
load-behavior-blocking = חסימה
max-execution-duration = משך זמן ביצוע מירבי
max-execution-duration-suffix = { " " } שניות
quality = איכות
quality-low = נמוכה
quality-medium = בינונית
quality-high = גבוהה
quality-best = הטובה ביותר
quality-high8x8 = גבוהה (8x8)
quality-high8x8linear = גבוהה (8x8) לינארית
quality-high16x16 = גבוהה (16x16)
quality-high16x16linear = גבוהה (16x16) לינארית
letterbox = תיבת מכתים
letterbox-on = פועל
letterbox-fullscreen = מסך מלא בלבד
letterbox-off = כבוי
align = יישור אזור
align-center = מרכז
align-left = שמאל
align-right = ימין
align-top = עליון
align-bottom = תחתית
align-top-left = שמאלית עליונה
align-bottom-left = שמאלית תחתונה
align-top-right = ימנית עליונה
align-bottom-right = ימנית תחתונה
align-force = כפה
scale-mode = מצב קנה-מידה
scale-mode-force = כפה
player-version = גרסת שחקן
player-runtime = הרצת נגן
player-runtime-flash = נגן פלאש
player-runtime-air = אדובי AIR
custom-framerate = קצב פריימים מותאם אישית
custom-framerate-suffix = { " " } פריימים לשנייה
dummy-external-interface = ממשק חיצוני מדומה
