// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DTriangleFace.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    [API("674")]
    public final class Context3DTriangleFace
    {
        public static const BACK:String = "back";

        public static const FRONT:String = "front";

        public static const FRONT_AND_BACK:String = "frontAndBack";

        public static const NONE:String = "none";

    }
}
