// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DClearMask.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    public final class Context3DClearMask
    {
        // Clear all buffers.
        public static const ALL:int = COLOR | DEPTH | STENCIL;

        // Clear only the color buffer.
        public static const COLOR:int =   1 << 0;

        // Clear only the depth buffer.
        public static const DEPTH:int =   1 << 1;

        // Clear only the stencil buffer.
        public static const STENCIL:int = 1 << 2;

    }
}
