// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DTextureFilter.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    [API("686")]
    public final class Context3DTextureFilter
    {
        // Use anisotropic filter with radio 16 when upsampling textures
        [API("698")]
        public static const ANISOTROPIC16X:String = "anisotropic16x";

        // Use anisotropic filter with radio 2 when upsampling textures
        [API("698")]
        public static const ANISOTROPIC2X:String = "anisotropic2x";

        // Use anisotropic filter with radio 4 when upsampling textures
        [API("698")]
        public static const ANISOTROPIC4X:String = "anisotropic4x";

        // Use anisotropic filter with radio 8 when upsampling textures
        [API("698")]
        public static const ANISOTROPIC8X:String = "anisotropic8x";

        // Use linear interpolation when upsampling textures (gives a smooth, blurry look).
        public static const LINEAR:String = "linear";

        // Use nearest neighbor sampling when upsampling textures (gives a pixelated, sharp mosaic look).
        public static const NEAREST:String = "nearest";

    }
}
