// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DTextureFormat.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    [API("674")]
    public final class Context3DTextureFormat
    {
        public static const BGRA:String = "bgra";

        // 16 bit, bgra packed as 4:4:4:4
        [API("688")]
        public static const BGRA_PACKED:String = "bgraPacked4444";

        // 16 bit, bgr packed as 5:6:5
        [API("688")]
        public static const BGR_PACKED:String = "bgrPacked565";

        public static const COMPRESSED:String = "compressed";

        [API("682")]
        public static const COMPRESSED_ALPHA:String = "compressedAlpha";

        [API("698")]
        public static const RGBA_HALF_FLOAT:String = "rgbaHalfFloat";

    }
}
