// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DCompareMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    public final class Context3DCompareMode
    {
        // The comparison always evaluates as true.
        public static const ALWAYS:String = "always";

        // Equal (==).
        public static const EQUAL:String = "equal";

        // Greater than (>).
        public static const GREATER:String = "greater";

        // Greater than or equal (>=).
        public static const GREATER_EQUAL:String = "greaterEqual";

        // Less than (<).
        public static const LESS:String = "less";

        // Less than or equal (<=).
        public static const LESS_EQUAL:String = "lessEqual";

        // The comparison never evaluates as true.
        public static const NEVER:String = "never";

        // Not equal (!=).
        public static const NOT_EQUAL:String = "notEqual";

    }
}
