// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DProgramType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{
    
    [API("674")]
    public final class Context3DProgramType
    {
        // A fragment (or pixel) program.
        public static const FRAGMENT:String = "fragment";
        
        // A vertex program.
        public static const VERTEX:String = "vertex";
        
        
    }
}
