// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DBufferUsage.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    [API("692")] // the docs say 694, that's wrong
    public final class Context3DBufferUsage
    {
        // Indicates the buffer will be used for drawing and be updated frequently
        public static const DYNAMIC_DRAW:String = "dynamicDraw";

        // Indicates the buffer will be used for drawing and be updated once This type is the default value for buffers in Stage3D.
        public static const STATIC_DRAW:String = "staticDraw";

    }
}
