// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3DVertexBufferFormat.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display3D
{

    [API("674")]
    public final class Context3DVertexBufferFormat
    {
        public static const BYTES_4:String = "bytes4";

        public static const FLOAT_1:String = "float1";

        public static const FLOAT_2:String = "float2";

        public static const FLOAT_3:String = "float3";

        public static const FLOAT_4:String = "float4";

    }
}
