context-menu-play = Spela
context-menu-rewind = Spola tillbaka
context-menu-forward = Framåt
context-menu-back = Bakåt
context-menu-quality-low = Kvalitet: Låg
context-menu-quality-medium = Kvalitet: Medel
context-menu-quality-high = Kvalitet: Hög
context-menu-cut = Klipp
context-menu-copy = Kopiera
context-menu-paste = Klistra in
context-menu-delete = Radera
context-menu-select-all = Markera Allt
