context-menu-play = Redă
context-menu-rewind = Derulează înapoi
context-menu-forward = Derulează înainte
context-menu-back = Înapoi
context-menu-quality-low = Calitate: Scăzută
context-menu-quality-medium = Calitate: Medie
context-menu-quality-high = Calitate: Ridicată
context-menu-cut = Decupează
context-menu-copy = Copiază
context-menu-paste = Lipește
context-menu-delete = Șterge
context-menu-select-all = Selectează tot
