#![allow(dead_code)]

use gc_arena::Gc;
use ruffle_common::utils::HasPrefixField;

use super::kind::{Erased, Kind};
use super::{ObjectVariant, ScriptObjectData};

pub fn upcast<'gc, T: ObjectVariant<'gc>>(value: T) -> Gc<'gc, ScriptObjectData<'gc, Erased>> {
    let typed = HasPrefixField::as_prefix_gc(value.data_gc());
    ScriptObjectData::erase_kind(typed)
}

pub fn downcast<'gc, T: ObjectVariant<'gc>>(
    base: Gc<'gc, ScriptObjectData<'gc, Erased>>,
) -> Option<T> {
    if base.kind() == T::Kind::ID {
        // SAFETY: the tag check proves the allocation was originally T::Data.
        // Every ObjectVariant impl is generated by define_variants! with a
        // unique Kind, so kind match implies data type match.
        Some(unsafe { downcast_unchecked(base) })
    } else {
        None
    }
}

/// # Safety
/// `base` must point to an allocation that was originally allocated as `T::Data`.
pub unsafe fn downcast_unchecked<'gc, T: ObjectVariant<'gc>>(
    base: Gc<'gc, ScriptObjectData<'gc, Erased>>,
) -> T {
    // SAFETY: ScriptObjectData<'gc, Erased> and ScriptObjectData<'gc, T::Kind>
    // have identical layout (K is phantom, repr(C)).
    let typed: Gc<'gc, ScriptObjectData<'gc, T::Kind>> = unsafe { Gc::cast(base) };
    // SAFETY: the caller guarantees the allocation is T::Data, whose prefix
    // field is ScriptObjectData<'gc, T::Kind>.
    let data: Gc<'gc, T::Data> = unsafe { Gc::cast(typed) };
    // SAFETY: the allocation is T::Data.
    unsafe { T::from_data_gc_unchecked(data) }
}
