about-ruffle = О Ruffle-у
about-ruffle-version = Верзија
about-ruffle-channel = Канал
about-ruffle-build-time = Време саграђивања
about-ruffle-build-features = Карактеристике саграђивања
about-ruffle-commit-ref = Референца посвете
about-ruffle-commit-time = Време потврде
about-ruffle-visit-website = Веб-сајт
about-ruffle-visit-github = ГитХаб
about-ruffle-visit-discord = Неслагање
about-ruffle-visit-sponsor = Спонзорирајте
