preferences-dialog = Подешавања Ruffle-а
preference-locked-by-cli = Само за читање (подешава се помоћу командне линије)
graphics-backend = Графички бекенд систем
graphics-backend-default = Подразумевано
graphics-power = Преференција снаге
graphics-power-low = Ниско (нпр. iGPU)
graphics-power-high = Високо (нпр. GPU)
language = Језик
audio-output-device = Аудио излазни уређај
audio-output-device-default = Системска подразумевана вредност
enable-openh264 = Омогући OpenH264
show-license = Прикажи лиценцу
openh264-license = Лиценца OpenH264
log-filename-pattern = Име датотеке дневника
log-filename-pattern-single-file = Једна датотека (ruffle.log)
log-filename-pattern-with-timestamp = Означено временском ознаком
storage-backend = Локација за чување датотеке
storage-backend-disk = Диск
storage-backend-memory = Памћење
theme = Тема
theme-system = Системска подразумевана вредност
theme-light = Светла
theme-dark = Тамна
gamemode-default = Подразумевано
# See for context https://wiki.archlinux.org/title/Input_method
ime-enabled = Метод уноса
ime-enabled-experimental = (експериментално)
ime-enabled-tooltip = Метод уноса вам омогућава да уносите знакове који нису доступни на тастатури, као што су кинески, јапански или корејски знакови.
ime-enabled-default = Подразумевано
