network-settings = Подешавања мреже
player-settings = Подешавања плејера
movie-parameters = Параметри филма
custom-base-url = Прилагођени основни URL
spoof-swf-url = Лажни SWF URL
cookie = Колачић
proxy = Прокси
upgrade-http = Надоградите HTTP на HTTPS
tcp-connections = TCP везе
tcp-connections-allow = Дозволи
tcp-connections-ask = Питајте
tcp-connections-deny = Одбаци
open-url-mode = Отвори линкове
open-url-mode-allow = Дозволи
open-url-mode-confirm = Питајте
open-url-mode-deny = Одбаци
load-behavior = Понашање оптерећења
load-behavior-delayed = Одложено
max-execution-duration = Максимално трајање извршења
max-execution-duration-suffix = { " " } секунди
quality = Квалитет
quality-low = Низак
quality-medium = Средњи
quality-high = Висок
quality-best = Најбољи
quality-high8x8 = Висок (8x8)
quality-high8x8linear = Висок (8x8) линеаран
quality-high16x16 = Висок (16x16)
quality-high16x16linear = Висок (16x16) линеаран
