// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/AccelerometerEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    [API("667")]
    public class AccelerometerEvent extends Event
    {
        // Defines the value of the type property of a AccelerometerEvent event object.
        public static const UPDATE:String = "update";

        // The number of milliseconds at the time of the event since the runtime was initialized.
        private var _timestamp:Number;

        // Acceleration along the x-axis, measured in Gs.
        private var _accelerationX:Number;

        // Acceleration along the y-axis, measured in Gs.
        private var _accelerationY:Number;
        
        // Acceleration along the z-axis, measured in Gs.
        private var _accelerationZ:Number;

        public function AccelerometerEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, timestamp:Number = 0,
            accelerationX:Number = 0, accelerationY:Number = 0, accelerationZ:Number = 0)
        {
            super(type, bubbles, cancelable);
            this.timestamp = timestamp;
            this.accelerationX = accelerationX;
            this.accelerationY = accelerationY;
            this.accelerationZ = accelerationZ;
        }

        public function get timestamp():Number {
            return this._timestamp;
        }
        public function set timestamp(value:Number):void {
            this._timestamp = value;
        }

        public function get accelerationX():Number {
            return this._accelerationX;
        }
        public function set accelerationX(value:Number):void {
            this._accelerationX = value;
        }

        public function get accelerationY():Number {
            return this._accelerationY;
        }
        public function set accelerationY(value:Number):void {
            this._accelerationY = value;
        }

        public function get accelerationZ():Number {
            return this._accelerationZ;
        }
        public function set accelerationZ(value:Number):void {
            this._accelerationZ = value;
        }

        // Creates a copy of an AccelerometerEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new AccelerometerEvent(this.type, this.bubbles, this.cancelable, this.timestamp, this.accelerationX, this.accelerationY, this.accelerationZ);
        }

        // Returns a string that contains all the properties of the AccelerometerEvent object.
        override public function toString():String
        {
            return this.formatToString("AccelerometerEvent", "type", "bubbles", "cancelable", "eventPhase", "timestamp", "accelerationX", "accelerationY", "accelerationZ");
        }
    }
}



