// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/AsyncErrorEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    public class AsyncErrorEvent extends ErrorEvent
    {
        public static const ASYNC_ERROR:String = "asyncError"; // The AsyncErrorEvent.ASYNC_ERROR constant defines the value of the type property of an asyncError event object.

        public var error: Error; // The exception that was thrown.

        public function AsyncErrorEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, text:String = "", error:Error = null)
        {
            super(type,bubbles,cancelable,text);
            this.error = error;
        }
        

        //  Creates a copy of the AsyncErrorEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new AsyncErrorEvent(this.type, this.bubbles, this.cancelable, this.text, this.error);
        }

        //  Returns a string that contains all the properties of the AsyncErrorEvent object.
        override public function toString():String
        {
            return this.formatToString("AsyncErrorEvent","type","bubbles","cancelable","eventPhase","text","error");
        }
    }
}

