// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/AudioOutputChangeEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    // TODO: [API("724")]
    public class AudioOutputChangeEvent extends Event
    {
        public static const AUDIO_OUTPUT_CHANGE:String = "audioOutputChange"; // Defines the value of the type property of a AudioOutputChangeEvent event object.

        private var _reason: String; // Reports the reason that triggers this AudioOutputChangeEvent.

        public function AudioOutputChangeEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, reason:String = null)
        {
            super(type,bubbles,cancelable);
            this._reason = reason;
        }
        

        public function get reason() : String
        {
            return this._reason;
        }
        
    }
}

