// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/BrowserInvokeEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class BrowserInvokeEvent extends Event
    {
        public static const BROWSER_INVOKE:String = "browserInvoke"; // [static] The BrowserInvokeEvent.BROWSER_INVOKE constant defines the value of the type property of a BrowserInvokeEvent object.

        private var _arguments: Array; // [read-only] An array of arguments (strings) to pass to the application.
        private var _sandboxType: String; // [read-only] The sandbox type for the content in the browser.
        private var _securityDomain: String; // [read-only] The security domain for the content in the browser, such as "www.adobe.com" or "www.example.org".
        private var _isHTTPS: Boolean; // [read-only] Whether the content in the browser uses the HTTPS URL scheme (true) or not (false).
        private var _isUserEvent: Boolean; // [read-only] Whether the browser invocation resulted in a user event (such as a mouse click).

        public function BrowserInvokeEvent(type:String, bubbles:Boolean, cancelable:Boolean, arguments:Array, sandboxType:String, securityDomain:String, isHTTPS:Boolean, isUserEvent:Boolean)
        {
            super(type,bubbles,cancelable);
            this._arguments = arguments;
            this._sandboxType = sandboxType;
            this._securityDomain = securityDomain;
            this._isHTTPS = isHTTPS;
            this._isUserEvent = isUserEvent;
        }
        

        // [override] Creates a new copy of this event.
        override public function clone():Event
        {
            return new BrowserInvokeEvent(this.type, this.bubbles, this.cancelable, this.arguments, this.sandboxType, this.securityDomain, this.isHTTPS, this.isUserEvent);
        }

        public function get arguments() : Array
        {
            return this._arguments;
        }
        

        public function get sandboxType() : String
        {
            return this._sandboxType;
        }
        

        public function get securityDomain() : String
        {
            return this._securityDomain;
        }
        

        public function get isHTTPS() : Boolean
        {
            return this._isHTTPS;
        }
        

        public function get isUserEvent() : Boolean
        {
            return this._isUserEvent;
        }
        
    }
}

