// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMAuthenticationCompleteEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    import flash.utils.ByteArray;
    
    [API("667")]
    public class DRMAuthenticationCompleteEvent extends Event
    {
        // The string constant to use for the authentication complete event in the type parameter when adding and removing event listeners.
        public static const AUTHENTICATION_COMPLETE:String = "authenticationComplete";

        public var serverURL: String; // The URL of the media rights server.
        public var domain: String; // The content domain of the media rights server.
        public var token: ByteArray; // The authentication token.

        public function DRMAuthenticationCompleteEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, inServerURL:String = null, inDomain:String = null, inToken:ByteArray = null)
        {
            super(type,bubbles,cancelable);
            this.serverURL = inServerURL;
            this.domain = inDomain;
            this.token = inToken;
        }
        

        //  Duplicates an instance of an Event subclass.
        override public function clone():Event
        {
            return new DRMAuthenticationCompleteEvent(this.type, this.bubbles, this.cancelable, this.serverURL, this.domain, this.token);
        }
    }
}

