// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMDeviceGroupErrorEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    import flash.net.drm.DRMDeviceGroup;
    
    public class DRMDeviceGroupErrorEvent extends ErrorEvent
    {
        public static const ADD_TO_DEVICE_GROUP_ERROR:String = "addToDeviceGroupError";
        public static const REMOVE_FROM_DEVICE_GROUP_ERROR:String = "removeFromDeviceGroupError";

        public var subErrorID: int; 
        public var deviceGroup: DRMDeviceGroup; // The DRMDeviceGroup object for this error event.
        private var _systemUpdateNeeded: Boolean; 
        private var _drmUpdateNeeded: Boolean; 

        public function DRMDeviceGroupErrorEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, errorDetail:String = "", errorCode:int = 0, subErrorID:int = 0, deviceGroup:DRMDeviceGroup = null, systemUpdateNeeded:Boolean = false, drmUpdateNeeded:Boolean = false)
        {
            super(type,bubbles,cancelable,errorDetail,errorCode);
            this.subErrorID = subErrorID;
            this.deviceGroup = deviceGroup;
            this._systemUpdateNeeded = systemUpdateNeeded;
            this._drmUpdateNeeded = drmUpdateNeeded;
        }
        

        
        override public function clone():Event
        {
            return new DRMDeviceGroupErrorEvent(this.type, this.bubbles, this.cancelable, this.text, this.errorID, this.subErrorID, this.deviceGroup, this.systemUpdateNeeded, this.drmUpdateNeeded);
        }

        
        override public function toString():String
        {
            return this.formatToString("DRMDeviceGroupErrorEvent","type","bubbles","cancelable","eventPhase","text","subErrorID","deviceGroup","systemUpdateNeeded","drmUpdateNeeded");
        }

        public function get systemUpdateNeeded() : Boolean
        {
            return this._systemUpdateNeeded;
        }
        

        public function get drmUpdateNeeded() : Boolean
        {
            return this._drmUpdateNeeded;
        }
        
    }
}

