// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMDeviceGroupEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    import flash.net.drm.DRMDeviceGroup;
    
    public class DRMDeviceGroupEvent extends Event
    {
        public static const ADD_TO_DEVICE_GROUP_COMPLETE:String = "addToDeviceGroupComplete"; 
        public static const REMOVE_FROM_DEVICE_GROUP_COMPLETE:String = "removeFromDeviceGroupComplete"; 

        public var deviceGroup: DRMDeviceGroup; // The DRMDeviceGroup object for this event.

        public function DRMDeviceGroupEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, deviceGroup:DRMDeviceGroup = null)
        {
            super(type,bubbles,cancelable);
            this.deviceGroup = deviceGroup;
        }
        

        
        override public function clone():Event
        {
            return new DRMDeviceGroupEvent(this.type, this.bubbles, this.cancelable, this.deviceGroup);
        }

        
        override public function toString():String
        {
            return this.formatToString("DRMDeviceGroupEvent","type","bubbles","cancelable","eventPhase","deviceGroup");
        }
    }
}

