// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMErrorEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    import flash.net.drm.DRMContentData;
    
    public class DRMErrorEvent extends ErrorEvent
    {
        public static const DRM_ERROR:String = "drmError"; // The DRMErrorEvent.DRM_ERROR constant defines the value of the type property of a drmError event object.
        public static const DRM_LOAD_DEVICEID_ERROR:String = "drmLoadDeviceIdError"; 

        private var _subErrorID: int; // An error ID that indicates more detailed information about the underlying problem.
        private var _systemUpdateNeeded: Boolean; // Indicates whether a system update is needed to play the DRM-protected content.
        private var _drmUpdateNeeded: Boolean; // Indicates whether a DRM update is needed to play the DRM-protected content.
        public var contentData: DRMContentData; // The DRMContentData for the media file.

        public function DRMErrorEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, inErrorDetail:String = "", inErrorCode:int = 0, insubErrorID:int = 0, inMetadata:DRMContentData = null, inSystemUpdateNeeded:Boolean = false, inDrmUpdateNeeded:Boolean = false)
        {
            super(type,bubbles,cancelable,inErrorDetail,inErrorCode);
            this._subErrorID = insubErrorID;
            this.contentData = inMetadata;
            this._systemUpdateNeeded = inSystemUpdateNeeded;
            this._drmUpdateNeeded = inDrmUpdateNeeded;
        }
        

        //  Creates a copy of the DRMErrorEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new DRMErrorEvent(this.type, this.bubbles, this.cancelable, this.text, this.errorID, this.subErrorID, this.contentData, this.systemUpdateNeeded, this.drmUpdateNeeded);
        }

        //  Returns a string that contains all the properties of the DRMErrorEvent object.
        override public function toString():String
        {
            return this.formatToString("DRMErrorEvent","type","bubbles","cancelable","eventPhase","errorID","subErrorID","text");
        }

        public function get subErrorID() : int
        {
            return this._subErrorID;
        }
        

        public function get systemUpdateNeeded() : Boolean
        {
            return this._systemUpdateNeeded;
        }
        

        public function get drmUpdateNeeded() : Boolean
        {
            return this._drmUpdateNeeded;
        }
        
    }
}

