// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMLicenseRequestEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class DRMLicenseRequestEvent extends Event
    {
        public static const LICENSE_REQUEST:String = "licenseRequest"; // The string constant to use for the license request event in the type parameter when adding and removing event listeners.

        public var serverURL: String; // The URL which will be used to communicate with the license server

        public function DRMLicenseRequestEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, inServerURL:String = null)
        {
            super(type,bubbles,cancelable);
            this.serverURL = inServerURL;
        }
        

        //  Duplicates an instance of an Event subclass.
        override public function clone():Event
        {
            return new DRMLicenseRequestEvent(this.type, this.bubbles, this.cancelable, this.serverURL);
        }
    }
}

