// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMMetadataEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    import flash.utils.ByteArray;
    import flash.net.drm.DRMContentData;
    
    public class DRMMetadataEvent extends Event
    {
        public static const DRM_METADATA:String = "drmMetadata"; // The DRMMetadataEvent.DRM_METADATA constant defines the value of the type property of a DRMMetadataEvent event object.

        private var _timestamp: Number; // The timestamp associated with the metadata
        private var _drmMetadata: DRMContentData; // The raw metadata bytes

        public function DRMMetadataEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, inMetadata:ByteArray = null, inTimestamp:Number = 0)
        {
            super(type,bubbles,cancelable);
            this._drmMetadata = DRMContentData(inMetadata);
            this._timestamp = inTimestamp;
        }
        

        public function get timestamp() : Number
        {
            return this._timestamp;
        }
        

        public function get drmMetadata() : DRMContentData
        {
            return this._drmMetadata;
        }
        
    }
}

