// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/DRMReturnVoucherErrorEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class DRMReturnVoucherErrorEvent extends ErrorEvent
    {
        // The string constant to use for the return voucher error event in the type parameter when adding and removing event listeners.
        public static const RETURN_VOUCHER_ERROR:String = "returnVoucherError";

        // A more detailed error code.
        private var _subErrorID: int;

         // The URL of the media rights server for this return Voucher attempt.
        private var _serverURL: String;

        // The license ID that was passed into the returnVoucher() call that resulted in this error.
        private var _licenseID: String;

        // The policy ID that was passed into the returnVoucher() call that resulted in this error.
        private var _policyID: String;

        public function DRMReturnVoucherErrorEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, inDetail:String = "",
            inErrorID:int = 0, inSubErrorID:int = 0, inServerURL:String = null, inLicenseID:String = null, inPolicyID:String = null)
        {
            super(type,bubbles,cancelable,inDetail,inErrorID);
            this.subErrorID = inSubErrorID;
            this.serverURL = inServerURL;
            this.licenseID = inLicenseID;
            this.policyID = inPolicyID;
        }

        public function get subErrorID():int {
            return this._subErrorID;
        }
        public function set subErrorID(value:int):void {
            this._subErrorID = value;
        }

        public function get serverURL():String {
            return this._serverURL;
        }
        public function set serverURL(value:String):void {
            this._serverURL = value;
        }

        public function get licenseID():String {
            return this._licenseID;
        }
        public function set licenseID(value:String):void {
            this._licenseID = value;
        }

        public function get policyID():String {
            return this._policyID;
        }
        public function set policyID(value:String):void {
            this._policyID = value;
        }

        // Creates a copy of the ErrorEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new DRMReturnVoucherErrorEvent(this.type, this.bubbles, this.cancelable, this.text, this.errorID, this.subErrorID, this.serverURL, this.licenseID, this.policyID);
        }
    }
}

