// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/FileListEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class FileListEvent extends Event
    {
        public static const DIRECTORY_LISTING:String = "directoryListing"; // [static] The FileListEvent.DIRECTORY_LISTING constant defines the value of the type property of the event object for a directoryListing event.
        public static const SELECT_MULTIPLE:String = "selectMultiple"; // [static] The FileListEvent.SELECT_MULTIPLE constant defines the value of the type property of the event object for a selectMultiple event.

        public var files: Array; // An array of File objects representing the files and directories found or selected.

        public function FileListEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, files:Array = null)
        {
            super(type,bubbles,cancelable);
            this.files = files;
        }
        
    }
}

