// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/InvokeEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.events
{

  import flash.filesystem.File;

  [API("661")]
  public class InvokeEvent extends Event
  {
    public static const INVOKE:String = "invoke";

    // The array of string arguments passed during this invocation.
    private var _arguments:Array;

    // The reason for this InvokeEvent.
    private var _reason:String;

    // The directory that should be used to resolve any relative paths in the arguments array.
    private var _currentDirectory:File;

    public function InvokeEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, dir:File = null, argv:Array = null, reason:String = "standard")
    {
      super(type, bubbles, cancelable);
      this._currentDirectory = dir;
      this._arguments = argv;
      this._reason = reason;
    }

    // [override] Creates a new copy of this event.
    override public function clone():Event
    {
      return new InvokeEvent(this.type, this.bubbles, this.cancelable, this.arguments, this.reason);
    }

    public function get arguments():Array
    {
      return this._arguments;
    }

    [API("664")]
    public function get reason():String
    {
      return this._reason;
    }

    public function get currentDirectory():File
    {
      return this._currentDirectory;
    }
  }
}
