// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/PermissionEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public final class PermissionEvent extends Event
    {
        public static const PERMISSION_STATUS:String = "permissionStatus"; 

        private var _status: String; // Check whether the permission has been granted or denied.

        public function PermissionEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, status:String = "denied")
        {
            super(type,bubbles,cancelable);
            this._status = status;
        }
        

        //  Creates a copy of an PermissionEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new PermissionEvent(this.type, this.bubbles, this.cancelable, this.status);
        }

        //  Returns a string that contains all the properties of the PermissionEvent object.
        override public function toString():String
        {
            return this.formatToString("PermissionEvent","type","bubbles","cancelable","eventPhase","status");
        }

        public function get status() : String
        {
            return this._status;
        }
        
    }
}

