// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/RemoteNotificationEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public final class RemoteNotificationEvent extends Event
    {
        public static const NOTIFICATION:String = "notification"; // [static] Defines the value of the type property of a RemoteNotificationEvent event object.
        public static const TOKEN:String = "token"; // [static] Defines the value of the type property of a RemoteNotificationEvent event object.

        private var _data: Object; // [read-only] Contains a JSON-format notification payload.
        private var _tokenId: String; // [read-only] Cotains the tokenId received from APNs, used to identify the application.

        public function RemoteNotificationEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, data:Object = null, tokenId:String = null)
        {
            super(type,bubbles,cancelable);
            this._data = data;
            this._tokenId = tokenId;
        }
        

        public function get data() : Object
        {
            return this._data;
        }
        

        public function get tokenId() : String
        {
            return this._tokenId;
        }
        
    }
}

