// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/StageOrientationEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class StageOrientationEvent extends Event
    {
        public static const ORIENTATION_CHANGE:String = "orientationChange"; // The ORIENTATION_CHANGE constant defines the value of the type property of a orientationChange event object.
        public static const ORIENTATION_CHANGING:String = "orientationChanging"; // The ORIENTATION_CHANGING constant defines the value of the type property of a orientationChanging event object.

        private var _beforeOrientation: String; // The orientation of the stage before the change.
        private var _afterOrientation: String; // The orientation of the stage after the change.

        public function StageOrientationEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, beforeOrientation:String = null, afterOrientation:String = null)
        {
            super(type,bubbles,cancelable);
            this._beforeOrientation = beforeOrientation;
            this._afterOrientation = afterOrientation;
        }
        

        //  Creates a copy of the StageOrientationEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new StageOrientationEvent(this.type, this.bubbles, this.cancelable, this.beforeOrientation, this.afterOrientation);
        }

        //  Returns a string that contains all the properties of the StageOrientationEvent object.
        override public function toString():String
        {
            return this.formatToString("StageOrientationEvent","type","bubbles","cancelable","eventPhase","beforeOrientation","afterOrientation");
        }

        public function get beforeOrientation() : String
        {
            return this._beforeOrientation;
        }
        

        public function get afterOrientation() : String
        {
            return this._afterOrientation;
        }
        
    }
}

