// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/StatusEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class StatusEvent extends Event
    {
        public static const STATUS:String = "status"; // Defines the value of the type property of a status event object.

        public var code: String; // A description of the object's status.
        public var level: String; // The category of the message, such as "status", "warning" or "error".

        public function StatusEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, code:String = "", level:String = "")
        {
            super(type,bubbles,cancelable);
            this.code = code;
            this.level = level;
        }
        

        //  Creates a copy of the StatusEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new StatusEvent(this.type, this.bubbles, this.cancelable, this.code, this.level);
        }

        //  Returns a string that contains all the properties of the StatusEvent object.
        override public function toString():String
        {
            return this.formatToString("StatusEvent","type","bubbles","cancelable","eventPhase","code","level");
        }
    }
}

