// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/SyncEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class SyncEvent extends Event
    {
        public static const SYNC:String = "sync"; // Defines the value of the type property of a sync event object.

        public var changeList: Array; // An array of objects; each object contains properties that describe the changed members of a remote shared object.

        public function SyncEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, changeList:Array = null)
        {
            super(type,bubbles,cancelable);
            this.changeList = changeList;
        }
        

        //  Creates a copy of the SyncEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new SyncEvent(this.type, this.bubbles, this.cancelable, this.changeList);
        }

        //  Returns a string that contains all the properties of the SyncEvent object.
        override public function toString():String
        {
            return this.formatToString("SyncEvent","type","bubbles","cancelable","eventPhase", "changeList");
        }
    }
}

