// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/UncaughtErrorEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    public class UncaughtErrorEvent extends ErrorEvent
    {
        public static const UNCAUGHT_ERROR:String = "uncaughtError"; // Defines the value of the type property of an uncaughtError event object.

        private var _error: *; // The error object associated with the uncaught error.

        public function UncaughtErrorEvent(type:String, bubbles:Boolean = true, cancelable:Boolean = true, error_in:* = null)
        {
            super(type,bubbles,cancelable);
            this._error = error_in;
        }
        

        //  Creates a copy of the UncaughtErrorEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new UncaughtErrorEvent(this.type, this.bubbles, this.cancelable, this.error);
        }

        //  Returns a string that contains all the properties of the UncaughtErrorEvent object.
        override public function toString():String
        {
            return this.formatToString("UncaughtErrorEvent","type","bubbles","cancelable","eventPhase","error");
        }

        public function get error() : *
        {
            return this._error;
        }
        
    }
}

