// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/VideoEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class VideoEvent extends Event
    {
        public const codecInfo:String; 
        public static const RENDER_STATE:String = "renderState"; // Defines the value of the type property of a renderState event object.
        public static const RENDER_STATUS_ACCELERATED:String = "accelerated"; // For internal use only.
        public static const RENDER_STATUS_SOFTWARE:String = "software"; // For internal use only.
        public static const RENDER_STATUS_UNAVAILABLE:String = "unavailable"; // For internal use only.

        private var _status: String; // Returns the rendering status of the VideoEvent object.

        public function VideoEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, status:String = null)
        {
            super(type,bubbles,cancelable);
            this._status = status;
        }
        

        public function get status() : String
        {
            return this._status;
        }
        
    }
}

