// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/VideoTextureEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class VideoTextureEvent extends Event
    {
        [API("706")]
        public static const RENDER_STATE:String = "renderState"; // The VideoTextureEvent.RENDER_STATE constant defines the value of the type property of a renderState event object.

        private var _status: String; // The status of the VideoTexture object.
        private var _colorSpace: String; // The color space used by the video being displayed in the VideoTexture object.

        public function VideoTextureEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, status:String = null, colorSpace:String = null)
        {
            super(type,bubbles,cancelable);
            this._status = status;
            this._colorSpace = colorSpace;
        }        

        [API("706")]
        public function get status() : String
        {
            return this._status;
        }
        
        [API("706")]
        public function get colorSpace() : String
        {
            return this._colorSpace;
        }
        
    }
}

