// The initial version of this file was autogenerated from the official AS3 reference at 
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/VsyncStateChangeAvailabilityEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix
package flash.events
{
    
    public class VsyncStateChangeAvailabilityEvent extends Event
    {
        public static const VSYNC_STATE_CHANGE_AVAILABILITY:String = "vSyncStateChangeAvailability"; // Defines the value of the type property of a VsyncStateChangeAvailabilityEvent event object.

        private var _available: Boolean; // Indicate that vsync state of Stage is changeable.

        public function VsyncStateChangeAvailabilityEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, available:Boolean = false)
        {
            super(type,bubbles,cancelable);
            this._available = available;
        }
        

        //  Creates a copy of an VsyncStateChangeAvailabilityEvent object and sets the value of each property to match that of the original.
        override public function clone():Event
        {
            return new VsyncStateChangeAvailabilityEvent(this.type, this.bubbles, this.cancelable, this.available);
        }

        //  Returns a string that contains all the properties of the VsyncStateChangeAvailabilityEvent object.
        override public function toString():String
        {
            return this.formatToString("VsyncStateChangeAvailabilityEvent","type","bubbles","cancelable","eventPhase","available");
        }

        public function get available() : Boolean
        {
            return this._available;
        }
        
    }
}

