// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetGroupSendMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class NetGroupSendMode
    {
        // Specifies the neighbor with the nearest group address in the decreasing direction.
        public static const NEXT_DECREASING:String = "nextDecreasing";

        // Specifies the neighbor with the nearest group address in the increasing direction.
        public static const NEXT_INCREASING:String = "nextIncreasing";

    }
}
