// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetGroupReceiveMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class NetGroupReceiveMode
    {
        // Specifies that this node accepts local messages from neighbors only if the address the neighbor uses matches this node's address exactly.
        public static const EXACT:String = "exact";

        // Specifies that this node accepts local messages from neighbors that send messages to group addresses that don't match this node's address exactly.
        public static const NEAREST:String = "nearest";

    }
}
