// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetGroupSendResult.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class NetGroupSendResult
    {
        // Indicates an error occurred (such as no permission) when using a Directed Routing method.
        public static const ERROR:String = "error";

        // Indicates no neighbor could be found to route the message toward its requested destination.
        public static const NO_ROUTE:String = "no route";

        // Indicates that a route was found for the message and it was forwarded toward its destination.
        public static const SENT:String = "sent";

    }
}
