// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetGroupReplicationStrategy.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class NetGroupReplicationStrategy
    {
        // Specifies that when fetching objects from a neighbor to satisfy a want, the objects with the lowest index numbers are requested first.
        public static const LOWEST_FIRST:String = "lowestFirst";

        // Specifies that when fetching objects from a neighbor to satisfy a want, the objects with the fewest replicas among all the neighbors are requested first.
        public static const RAREST_FIRST:String = "rarestFirst";

    }
}
