// List is ordered alphabetically.
include "flash/accessibility/AccessibilityProperties.as"
include "flash/geom/ColorTransform.as"
include "flash/geom/Orientation3D.as"
include "flash/geom/Point.as"
include "flash/geom/Rectangle.as"
include "flash/text/AntiAliasType.as"
include "flash/text/FontStyle.as"
include "flash/text/FontType.as"
include "flash/text/GridFitType.as"
include "flash/text/TextColorType.as"
include "flash/utils/CompressionAlgorithm.as"
include "flash/utils/Endian.as"
