// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/SyntaxError.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package
{

    public dynamic class SyntaxError extends Error
    {
        prototype.name = "SyntaxError";

        public function SyntaxError(message:String = "", id:int = 0)
        {
            super(message, id);
            this.name = prototype.name;
        }

    }
}

