preferences-dialog = Preferencje Ruffle
preference-locked-by-cli = Tylko do odczytu (ustawione przez CLI)
graphics-backend = Biblioteka graficzna
graphics-backend-default = Domyślna
graphics-power = Preferencje wydajności
graphics-power-low = Niskie (np. iGPU)
graphics-power-high = Wysokie (np. GPU)
language = Język
audio-output-device = Urządzenie wyjściowe audio
audio-output-device-default = Domyślne
enable-openh264 = Włącz OpenH264
show-license = Pokaż licencję
openh264-license = Licencja OpenH264
log-filename-pattern = Plik dziennika
log-filename-pattern-single-file = Pojedynczy plik (ruffle.log)
log-filename-pattern-with-timestamp = Ze znacznikiem czasu
storage-backend = Miejsce zapisu plików
storage-backend-disk = Dysk
storage-backend-memory = Pamięć RAM
recent-limit = Limit ostatnio otwartych plików
recent-clear = Wyczyść
theme = Motyw
theme-system = Motyw systemu
theme-light = Jasny
theme-dark = Ciemny
