network-settings = Ustawienia sieci
player-settings = Ustawienia odtwarzacza
movie-parameters = Parametry filmu
tcp-connections = Połączenia TCP
tcp-connections-allow = Zezwól
tcp-connections-ask = Pytaj
tcp-connections-deny = Zabroń
open-url-mode-allow = Zezwól
open-url-mode-confirm = Potwierdź
open-url-mode-deny = Zabroń
load-behavior-streaming = Strumieniowanie
load-behavior-delayed = Opóźnione
load-behavior-blocking = Blokowanie
max-execution-duration = Maksymalny czas wykonywania
max-execution-duration-suffix = { " " } sek
quality = Jakość
quality-low = Niska
quality-medium = Średnia
quality-high = Wysoka
quality-best = Najlepsza
quality-high8x8 = Wysoka (8x8)
quality-high16x16 = Wysoka (16x16)
letterbox-on = Włącz
letterbox-fullscreen = Tylko na pełnym ekranie
letterbox-off = Wyłącz
align-center = Wyśrodkuj
align-left = Po lewej
align-right = Po prawej
align-top = U góry
align-bottom = U dołu
align-top-left = Lewy górny róg
align-force = Wymuś
scale-mode = Tryb skalowania
scale-mode-exactfit = Dokładne dopasowanie
scale-mode-noborder = Bez obramowania
scale-mode-noscale = Brak skali
scale-mode-showall = Pokaż wszystko
scale-mode-force = Wymuś
player-version = Wersja odtwarzacza
custom-framerate-suffix = { " " } fps
dummy-external-interface-check = Włącz
