network-settings = Ustawienia sieci
player-settings = Ustawienia odtwarzacza
movie-parameters = Parametry filmu
custom-base-url = Niestandardowy adres URL
spoof-swf-url = Adres URL SWF
proxy = Proxy
upgrade-http = Uaktualnij HTTP do HTTPS
upgrade-http-check = Aktualizuj
tcp-connections = Połączenia TCP
tcp-connections-allow = Zezwól
tcp-connections-ask = Pytaj
tcp-connections-deny = Odmów
open-url-mode = Otwórz linki
open-url-mode-allow = Zezwól
open-url-mode-confirm = Zapytaj
open-url-mode-deny = Odmów
load-behavior = Priorytety
load-behavior-streaming = Strumieniowanie
load-behavior-delayed = Opóźnione
load-behavior-blocking = Blokowanie
max-execution-duration = Maksymalny czas wykonywania
max-execution-duration-suffix = { " " } sek
quality = Jakość
quality-low = Niska
quality-medium = Średnia
quality-high = Wysoka
quality-best = Najlepsza
quality-high8x8 = Wysoka (8x8)
quality-high8x8linear = Wysoki (8x8) liniowy
quality-high16x16 = Wysoka (16x16)
quality-high16x16linear = Wysoki (16x16) liniowy
letterbox-on = Włącz
letterbox-fullscreen = Tylko na pełnym ekranie
letterbox-off = Wyłącz
align = Wyrównanie etapu
align-center = Wyśrodkuj
align-left = Po lewej
align-right = Po prawej
align-top = U góry
align-bottom = U dołu
align-top-left = Lewy-górny
align-bottom-left = Lewy dolny
align-top-right = Górny prawy
align-bottom-right = Prawy-dół
align-force = Wymuś
scale-mode = Tryb skalowania
scale-mode-exactfit = Dokładne dopasowanie
scale-mode-noborder = Bez obramowania
scale-mode-noscale = Brak skali
scale-mode-showall = Pokaż wszystko
scale-mode-force = Wymuś
player-version = Wersja odtwarzacza
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interfejs zewnętrzny Dummy
dummy-external-interface-check = Włącz
