about-ruffle = Informazioni Su Ruffle
about-ruffle-version = Versione
about-ruffle-channel = Canale
about-ruffle-build-time = Tempo Di Costruzione
about-ruffle-build-features = Funzioni Di Build
about-ruffle-commit-ref = Alias del Commit
about-ruffle-commit-time = Tempo Di Commit
about-ruffle-visit-website = Sito web
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Sponsor
