network-settings = Impostazioni Di Rete
player-settings = Impostazioni Del Riproduttore
movie-parameters = Parametri Del Film
custom-base-url = Url Di Base Personalizzato
spoof-swf-url = URL SWF Spoof
proxy = Proxy
upgrade-http = Aggiorna HTTP a HTTPS
tcp-connections = Connessioni TCP
tcp-connections-allow = Consenti
tcp-connections-ask = Chiedi
tcp-connections-deny = Rifiuta
open-url-mode = Apri Link
open-url-mode-allow = Permetti
open-url-mode-confirm = Chiedi
open-url-mode-deny = Nega
load-behavior = Modalità di caricamento
load-behavior-streaming = Streaming
load-behavior-delayed = In ritardo
load-behavior-blocking = Blocco
max-execution-duration = Durata Massima Esecuzione
max-execution-duration-suffix = { " " } secs
quality = Qualità
quality-low = Bassa
quality-medium = Media
quality-high = Alta
quality-best = Migliore
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) Lineare
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (16x16) Lineare
letterbox = Formato Letterbox
letterbox-on = Attivo
letterbox-fullscreen = Solo Schermo Intero
letterbox-off = Spento
align = Allineamento Scena
align-center = Centrato
align-left = Sinistra
align-right = Destra
align-top = Sopra
align-bottom = Sotto
align-top-left = Sopra-Sinistra
align-bottom-left = Sotto-Sinistra
align-top-right = Sopra-Destra
align-bottom-right = Sotto-Destra
align-force = Forza
scale-mode = Modalità Scala
scale-mode-force = Forza
player-version = Versione Riproduttore
custom-framerate = Framerate Personalizzato
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interfaccia Esterna Dummy
