// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/KeyboardType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.ui
{

    public final class KeyboardType
    {
        // A standard keyboard with a full set of numbers and letters.
        public static const ALPHANUMERIC:String = "alphanumeric";

        // A phone-style 12-button keypad.
        public static const KEYPAD:String = "keypad";

        // No physical keyboard is supported.
        public static const NONE:String = "none";

    }
}
