// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/KeyLocation.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.ui
{

    public final class KeyLocation
    {
        // Indicates the key activated is in the left key location (there is more than one possible location for this key).
        public static const LEFT:uint = 1;

        // Indicates the key activation originated on the numeric keypad or with a virtual key corresponding to the numeric keypad.
        public static const NUM_PAD:uint = 3;

        // Indicates the key activated is in the right key location (there is more than one possible location for this key).
        public static const RIGHT:uint = 2;

        // Indicates the key activation is not distinguished as the left or right version of the key, and did not originate on the numeric keypad
        // (or did not originate with a virtual key corresponding to the numeric keypad).
        public static const STANDARD:uint = 0;

    }
}
