// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/MouseCursor.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.ui
{

    public final class MouseCursor
    {
        // Used to specify that the arrow cursor should be used.
        public static const ARROW:String = "arrow";

        // Used to specify that the cursor should be selected automatically based on the object under the mouse.
        public static const AUTO:String = "auto";

        // Used to specify that the button pressing hand cursor should be used.
        public static const BUTTON:String = "button";

        // Used to specify that the dragging hand cursor should be used.
        public static const HAND:String = "hand";

        // Used to specify that the I-beam cursor should be used.
        public static const IBEAM:String = "ibeam";

    }
}
