about-ruffle = Ruffle 정보
about-ruffle-version = 버전
about-ruffle-channel = 채널
about-ruffle-build-time = 빌드 시간
about-ruffle-build-features = 빌드 기능
about-ruffle-commit-ref = 커밋 레퍼런스
about-ruffle-commit-time = 커밋 시간
about-ruffle-visit-website = 웹사이트
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = 디스코드
about-ruffle-visit-sponsor = 후원
