file-picker-title-open-file = 단일 파일 열기
file-picker-title-open-directory = 폴더 열기
file-picker-filter-supported = 지원되는 모든 파일
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash 애니메이터 (*.spl)
file-picker-filter-ruf = Ruffle 번들 (*.ruf)
file-picker-filter-all = 모든 파일
file-picker-select-root-movie-title = 루트 무비 선택
file-picker-select-root-movie-message = 열려있는 디렉토리에서 루트 무비 선택.
file-picker-select-root-movie-select = 선택
