preferences-dialog = Ruffle 환경설정
preference-locked-by-cli = 읽기 전용 (CLI로 설정)
graphics-backend = 그래픽 백엔드
graphics-backend-default = 기본
graphics-power = 파워 환경설정
graphics-power-low = 낮음 (예: iGPU)
graphics-power-high = 높음 (예: GPU)
language = 언어
audio-output-device = 오디오 출력 장치
audio-output-device-default = 시스템 기본
enable-openh264 = OpenH264 활성화
show-license = 라이선스 보기
openh264-license = OpenH264 라이선스
log-filename-pattern = 로그 파일명
log-filename-pattern-single-file = 단일 파일 (ruffle.log)
log-filename-pattern-with-timestamp = 타임스탬프 포함
storage-backend = 파일 저장 위치
storage-backend-disk = 디스크
storage-backend-memory = 메모리
recent-limit = 최대 최근 항목 수
recent-clear = 비우기
