network-settings = 네트워크 설정
player-settings = 플레이어 설정
movie-parameters = 무비 파라미터
custom-base-url = 사용자 지정 기본 URL
spoof-swf-url = SWF URL 스푸핑
proxy = 프록시
upgrade-http = HTTP를 HTTPS로 업그레이드
upgrade-http-check = 업그레이드
open-url-mode = URL 열기 모드
open-url-mode-allow = 허용
open-url-mode-confirm = 확인
open-url-mode-deny = 거부
load-behavior = 로드 동작
load-behavior-streaming = 스트리밍
load-behavior-delayed = 지연됨
load-behavior-blocking = 차단
max-execution-duration = 최대 실행 지속시간
max-execution-duration-suffix = { " " } 초
quality = 품질
quality-low = 낮음
quality-medium = 보통
quality-high = 높음
quality-best = 최고
quality-high8x8 = 높음 (8x8)
quality-high8x8linear = 높음 (8x8) 선형
quality-high16x16 = 높음 (16x16)
quality-high16x16linear = 높음 (16x16) 선형
scale-mode = 스케일 모드
scale-mode-exactfit = 정확히 맞추기
scale-mode-noborder = 테두리 없음
scale-mode-noscale = 배율 조정 없음
scale-mode-showall = 모두 표시
force-scale-mode = 강제 스케일 모드
force-scale-mode-check = 강제
warn-if-unsupported = 지원되지 않을 경우 경고
warn-if-unsupported-check = 경고
player-version = 플레이어 버전
custom-framerate = 사용자 지정 프레임레이트
custom-framerate-suffix = { " " } fps
