network-settings = 네트워크 설정
player-settings = 플레이어 설정
movie-parameters = 무비 파라미터
custom-base-url = 사용자 지정 기본 URL
spoof-swf-url = SWF URL 스푸핑
referer-url = 레퍼러 URL
cookie = 쿠키
proxy = 프록시
upgrade-http = HTTP를 HTTPS로 업그레이드
tcp-connections = TCP 연결
tcp-connections-allow = 허용
tcp-connections-ask = 물어보기
tcp-connections-deny = 거부
open-url-mode = 링크 열기
open-url-mode-allow = 허용
open-url-mode-confirm = 묻기
open-url-mode-deny = 거부
load-behavior = 로드 동작
load-behavior-streaming = 스트리밍
load-behavior-delayed = 지연됨
load-behavior-blocking = 차단
max-execution-duration = 최대 실행 지속시간
max-execution-duration-suffix = { " " } 초
quality = 품질
quality-low = 낮음
quality-medium = 보통
quality-high = 높음
quality-best = 최고
quality-high8x8 = 높음 (8x8)
quality-high8x8linear = 높음 (8x8) 선형
quality-high16x16 = 높음 (16x16)
quality-high16x16linear = 높음 (16x16) 선형
letterbox = 레터박스
letterbox-on = 켜기
letterbox-fullscreen = 전체화면만
letterbox-off = 끄기
align = 스테이지 정렬
align-center = 중앙
align-left = 좌측
align-right = 우측
align-top = 상단
align-bottom = 하단
align-top-left = 상단 좌측
align-bottom-left = 하단 좌측
align-top-right = 상단 우측
align-bottom-right = 하단 우측
align-force = 강제
scale-mode = 스케일 모드
scale-mode-exactfit = 정확히 맞추기
scale-mode-noborder = 테두리 없음
scale-mode-noscale = 배율 조정 없음
scale-mode-showall = 모두 표시
scale-mode-force = 강제
player-version = 플레이어 버전
player-runtime = 플레이어 런타임
player-runtime-flash = 플래시 플레이어
player-runtime-air = Abode AIR
custom-framerate = 사용자 지정 프레임레이트
custom-framerate-suffix = { " " } fps
dummy-external-interface = 더미 외부 인터페이스
