context-menu-play = Воспроизведение
context-menu-rewind = Перемотать назад
context-menu-forward = Вперёд
context-menu-back = Назад
context-menu-quality-low = Качество: низкое
context-menu-quality-medium = Качество: среднее
context-menu-quality-high = Качество: высокое
context-menu-cut = Вырезать
context-menu-copy = Скопировать
context-menu-paste = Вставить
context-menu-delete = Удалить
context-menu-select-all = Выделить всё
