about-ruffle = Über Ruffle
about-ruffle-version = Version
about-ruffle-channel = Kanal
about-ruffle-build-time = Bauzeit
about-ruffle-build-features = Bau Funktionen
about-ruffle-visit-website = Webseite
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Sponsor
