preferences-dialog = Ruffle Einstellungen
preference-locked-by-cli = Schreibgeschützt (durch Befehlszeile gesetzt)
graphics-backend = Grafik-Schnittstelle
graphics-backend-default = Standard
graphics-power = Energieeinstellung
graphics-power-low = Niedrig (iGPU)
graphics-power-high = Hoch (GPU)
language = Sprache
audio-output-device = Audio-Ausgabegerät
audio-output-device-default = Systemvorgabe
enable-openh264 = OpenH264 aktivieren
show-license = Lizenz anzeigen
openh264-license = OpenH264 Lizenz
log-filename-pattern = Logdateiname
log-filename-pattern-single-file = Einzelne Datei (ruffle.log)
log-filename-pattern-with-timestamp = Mit Zeitstempel
storage-backend = Datei Speicherort
storage-backend-disk = Festplatte
storage-backend-memory = Arbeitsspeicher
recent-limit = Letztes Limit
recent-clear = Löschen
theme = Thema
theme-system = Systemstandard
theme-light = Hell
theme-dark = Dunkel
gamemode-default = Standard
