preferences-dialog = Ruffle Einstellungen
preference-locked-by-cli = Schreibgeschützt (durch Befehlszeile gesetzt)
graphics-backend = Grafik-Schnittstelle
graphics-backend-default = Standard
graphics-power = Energieeinstellung
graphics-power-low = Niedrig (iGPU)
graphics-power-high = Hoch (GPU)
language = Sprache
audio-output-device = Audio-Ausgabegerät
audio-output-device-default = Systemvorgabe
log-filename-pattern = Logdateiname
log-filename-pattern-single-file = Einzelne Datei (ruffle.log)
log-filename-pattern-with-timestamp = Mit Zeitstempel
