network-settings = Netzwerkeinstellungen
player-settings = Spieler-Einstellungen
movie-parameters = Filmparameter
custom-base-url = Benutzerdefinierte Base-URL
spoof-swf-url = Gefälschte SWF-URL
cookie = Cookie
proxy = Proxy
upgrade-http = HTTP auf HTTPS upgraden
tcp-connections = TCP-Verbindungen
tcp-connections-allow = Erlauben
tcp-connections-ask = Fragen
tcp-connections-deny = Verbieten
open-url-mode = Links öffnen
open-url-mode-allow = Erlauben
open-url-mode-confirm = Fragen
open-url-mode-deny = Verbieten
load-behavior = Ladeverhalten
load-behavior-streaming = Streamen
load-behavior-delayed = Verzögert
load-behavior-blocking = Blocken
max-execution-duration = Maximale Ausführungsdauer
max-execution-duration-suffix = { " " } Sekunden
quality = Qualität
quality-low = Niedrig
quality-medium = Mittel
quality-high = Hoch
quality-best = Am besten
quality-high8x8 = Hoch (8x8)
quality-high8x8linear = Hoch (8x8) Linear
quality-high16x16 = Hoch (16x16)
quality-high16x16linear = Hoch (16x16) Linear
letterbox = Letterbox
letterbox-on = An
letterbox-fullscreen = Nur Vollbild
letterbox-off = Aus
align = Bühnenausrichtung
align-center = Zentriert
align-left = Links
align-right = Rechts
align-top = Oben
align-bottom = Unten
align-top-left = Oben-Links
align-bottom-left = Unten-Links
align-top-right = Oben-Rechts
align-bottom-right = Unten-Rechts
align-force = Erzwingen
scale-mode = Skalierungsmodus
scale-mode-force = Erzwingen
player-version = Spieler Version
player-runtime = Spieler-Laufzeitumgebung
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Benutzerdefinierte Bildfrequenz
custom-framerate-suffix = { " " } fps
dummy-external-interface = Dummy Externe-Schnittstelle
