file-picker-title-open-file = 開啟單一檔案
file-picker-title-open-directory = 開啟資料夾
file-picker-filter-supported = 所有支援的檔案
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Ruffle 包裹(*.ruf)
file-picker-filter-all = 所有檔案
file-picker-select-root-movie-title = 選取主動畫
file-picker-select-root-movie-message = 從開啟的目錄中選取主動畫。
file-picker-select-root-movie-select = 選擇
