preferences-dialog = Ruffle偏好設定
preference-locked-by-cli = 唯讀 (CLI設定)
graphics-backend = 圖形顯示後端
graphics-backend-default = 預設
graphics-power = 圖形顯示效能
graphics-power-low = 低 (例如iGPU)
graphics-power-high = 高 (例如iGPU)
language = 語言
audio-output-device = 音訊輸出設備
audio-output-device-default = 系統預設
