preferences-dialog = Ruffle偏好設定
preference-locked-by-cli = 唯讀 (CLI設定)
graphics-backend = 圖形顯示後端
graphics-backend-default = 預設
graphics-power = 圖形顯示效能
graphics-power-low = 低 (例如iGPU)
graphics-power-high = 高 (例如GPU)
language = 語言
audio-output-device = 音訊輸出設備
audio-output-device-default = 系統預設
enable-openh264 = 開啟OpenH264
show-license = 顯示授權條款
openh264-license = OpenH264授權
log-filename-pattern = 記錄檔名
log-filename-pattern-single-file = 統一檔案 (ruffle.log)
log-filename-pattern-with-timestamp = 包含時間點
storage-backend = 存檔地點
storage-backend-disk = 硬碟
storage-backend-memory = 記憶體
recent-limit = 最近上限
recent-clear = 清除
theme = 主題
theme-system = 系統預設
theme-light = 明亮
theme-dark = 黑暗
