network-settings = 網路設定
player-settings = 播放器設定
movie-parameters = 參數
custom-base-url = 自訂的基本 URL
spoof-swf-url = 欺騙 URL
referer-url = 參照位址
cookie = Cookie
proxy = 代理伺服器
upgrade-http = 升級HTTP至HTTPS
tcp-connections = TCP 連接
tcp-connections-allow = 允許
tcp-connections-ask = 詢問
tcp-connections-deny = 拒絕
open-url-mode = 打開連結
open-url-mode-allow = 允許
open-url-mode-confirm = 詢問
open-url-mode-deny = 拒絕
load-behavior = 載入行為
load-behavior-streaming = 串流
load-behavior-delayed = 延遲
load-behavior-blocking = 阻止
max-execution-duration = 最大執行次數
max-execution-duration-suffix = { " " } 秒
quality = 品質
quality-low = 低
quality-medium = 中
quality-high = 高
quality-best = 最佳
quality-high8x8 = 高 (8x8)
quality-high8x8linear = 高 (8x8) 線性
quality-high16x16 = 高 (16x16)
quality-high16x16linear = 高 (16x16) 線性
letterbox = 信箱模式
letterbox-on = 開啟
letterbox-fullscreen = 全螢幕專用
letterbox-off = 關閉
align = 背景設置
align-center = 置中
align-left = 左側
align-right = 右側
align-top = 頂部
align-bottom = 底部
align-top-left = 左上角
align-bottom-left = 左下方
align-top-right = 右上角
align-bottom-right = 右下方
align-force = 強制
scale-mode = 縮放模式
scale-mode-noscale = 未縮放 (100%)
scale-mode-showall = 縮放至適當比例
scale-mode-exactfit = 伸長到適合
scale-mode-noborder = 裁剪以適應寬高比
scale-mode-force = 強制
player-version = 播放器版本
player-runtime = 執行環境
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = 客製化偵數
custom-framerate-suffix = { " " } fps
dummy-external-interface = 虛設外部接口
