network-settings = 網路設定
player-settings = 播放器設定
movie-parameters = 參數
custom-base-url = 自訂的基本 URL
spoof-swf-url = 欺騙 URL
proxy = 代理伺服器
upgrade-http = 升級HTTP至HTTPS
upgrade-http-check = 升級
open-url-mode = 開啟 URL 模式
open-url-mode-allow = 允許
open-url-mode-confirm = 確認
open-url-mode-deny = 拒絕
load-behavior = 載入行為
load-behavior-streaming = 串流
load-behavior-delayed = 延遲
load-behavior-blocking = 阻止
max-execution-duration = 最大執行次數
max-execution-duration-suffix = { " " } 秒
quality = 品質
quality-low = 低
quality-medium = 中
quality-high = 高
quality-best = 最佳
quality-high8x8 = 高 (8x8)
quality-high8x8linear = 高 (8x8) 線性
quality-high16x16 = 高 (16x16)
quality-high16x16linear = 高 (16x16) 線性
scale-mode = 縮放模式
scale-mode-exactfit = 正適合
scale-mode-noborder = 無邊
scale-mode-noscale = 無縮放
scale-mode-showall = 顯示全部
force-scale-mode = 强制縮放模式
force-scale-mode-check = 強制
warn-if-unsupported = 警告未支援
warn-if-unsupported-check = 警告
player-version = 播放器版本
custom-framerate = 客製化偵數
custom-framerate-suffix = { " " } fps
dummy-external-interface = 虛設外部接口
dummy-external-interface-check = 啟用
