network-settings = Postavke mreže
player-settings = Postavke playera
movie-parameters = Parametri filma
custom-base-url = Prilagođeni osnovni URL
spoof-swf-url = URL lažnog SWF-a
referer-url = URL reference
cookie = Kolačić
proxy = Proxy
upgrade-http = Nadogradite HTTP na HTTPS
tcp-connections = TCP veze
tcp-connections-allow = Dopusti
tcp-connections-ask = Pitajte
tcp-connections-deny = Odbij
open-url-mode = Otvori poveznice
open-url-mode-allow = Dopusti
open-url-mode-confirm = Pitajte
open-url-mode-deny = Odbij
load-behavior = Ponašanje opterećenja
load-behavior-streaming = Tokovanje
load-behavior-delayed = Odgođeno
max-execution-duration = Maksimalno trajanje izvršenja
max-execution-duration-suffix = { " " } sekundi
quality = Kvaliteta
quality-high8x8 = Visoka (8x8)
quality-high8x8linear = Visoka (8x8) linearna
quality-high16x16 = Visoka (16x16)
letterbox = Poštanski sandučić
letterbox-on = Uključeno
letterbox-fullscreen = Samo cijeli zaslon
letterbox-off = Isključeno
align = Poravnanje pozornice
align-center = Centar
align-left = Lijevo
align-right = Desno
align-top = Vrh
align-bottom = Dno
align-top-left = Gore lijevo
align-bottom-left = Dolje lijevo
align-top-right = Gore desno
align-bottom-right = Dolje desno
scale-mode = Način skaliranja
scale-mode-noscale = Neskalirano (100%)
player-version = Verzija igrača
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Prilagođena brzina sličica u sekundi
custom-framerate-suffix = { " " } sličica u sekundi
dummy-external-interface = Lažno vanjsko sučelje
