context-menu-play = Mainkan
context-menu-rewind = Mundur
context-menu-forward = Maju
context-menu-back = Kembali
context-menu-quality-low = Kualitas: Rendah
context-menu-quality-medium = Kualitas: Sedang
context-menu-quality-high = Kualitas: Tinggi
context-menu-cut = Potong
context-menu-copy = Salin
context-menu-paste = Tempel
context-menu-delete = Hapus
context-menu-select-all = Pilih semua
