file-picker-title-open-file = Buka satu berkas
file-picker-title-open-directory = Buka satu folder
file-picker-filter-supported = Semua Berkas yang Didukung
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Bundel Ruffle (*.ruf)
file-picker-filter-all = Semua Berkas
file-picker-select-root-movie-title = Pilih SWF Utama
file-picker-select-root-movie-message = Silakan pilih SWF utama pada direktori yang dibuka.
file-picker-select-root-movie-select = Pilih
