preferences-dialog = Pengaturan Ruffle
preference-locked-by-cli = Mode Hanya-Baca (Ditetapkan oleh CLI)
graphics-backend = Backend Grafik
graphics-backend-default = Default
graphics-power = Pengaturan Power
graphics-power-low = Rendah (menggunakan iGPU)
graphics-power-high = Tinggi (menggunakan GPU)
language = Bahasa
audio-output-device-default = Bawaan Sistem
enable-openh264 = Aktifkan OpenH264
show-license = Tunjukkan Lisensi
openh264-license = Lisensi OpenH264
log-filename-pattern-single-file = Satu Berkas (ruffle.log)
log-filename-pattern-with-timestamp = Dengan Timestamp
storage-backend = Lokasi Penyimpanan
storage-backend-disk = Disk
storage-backend-memory = Memori
recent-clear = Bersihkan
theme = Tema
theme-system = Bawaan Sistem
theme-light = Terang
theme-dark = Gelap
# See for context https://github.com/FeralInteractive/gamemode
gamemode = GameMode
gamemode-default = Default
ime-enabled-experimental = (eksperimental)
ime-enabled-default = Default
device-font-renderer-tooltip = Memilih backend yang digunakan untuk merender font perangkat.
device-font-renderer-default = Default
device-font-renderer-embedded = Tersemat
device-font-renderer-freetype = FreeType
