network-settings = Pengaturan Jaringan
player-settings = Pengaturan Pemutar
movie-parameters = Parameter Film Flash
custom-base-url = URL dasar khusus
spoof-swf-url = URL SWF Buatan
proxy = Proksi
upgrade-http = Tingkatkan HTTP ke HTTPS
tcp-connections = Koneksi TCP
tcp-connections-allow = Izinkan
tcp-connections-ask = Tanya
tcp-connections-deny = Tolak
open-url-mode = Buka Link
open-url-mode-allow = Izinkan
open-url-mode-confirm = Tanya
open-url-mode-deny = Tolak
load-behavior = Sikap pemuat
load-behavior-streaming = Mengalir
load-behavior-delayed = Tertunda
load-behavior-blocking = Menghalang
max-execution-duration = Batas Waktu Eksekusi
max-execution-duration-suffix = { " " } detik
quality = Kualitas
quality-low = Rendah
quality-medium = Sedang
quality-high = Tinggi
quality-best = Terbaik
quality-high8x8 = Tinggi (8x8)
quality-high8x8linear = Tinggi (8x8) Linear
quality-high16x16 = Tinggi (16x16)
quality-high16x16linear = Tinggi (16x16) Linear
letterbox = Letterbox
letterbox-on = Aktif
letterbox-fullscreen = Layar penuh
letterbox-off = Nonaktif
align = Penjajaran Halaman
align-center = Tengah
align-left = Kiri
align-right = Kanan
align-top = Atas
align-bottom = Bawah
align-top-left = Atas-kiri
align-bottom-left = Bawah-kiri
align-top-right = Atas-kanan
align-bottom-right = Bawah-kanan
align-force = Paksa
scale-mode = Moda Skala
scale-mode-force = Paksa
player-version = Versi Pemutar
custom-framerate = Framerate Khusus
custom-framerate-suffix = { " " } fps
dummy-external-interface = External Interface Buatan
