var o = new TextField();
trace(TextField);
trace(typeof TextField);
trace(TextField.prototype);
trace(typeof TextField.prototype);

trace(o);
trace(typeof o);

trace("Enumerated");
for (var p in o) {
    trace(p);
}

trace("Enumerated prototype");
for (var p in TextField.prototype) {
    trace(p);
}

trace("Props");
trace(o.styleSheet);
trace(o.mouseWheelEnabled);
trace(o.condenseWhite);
trace(o.restrict);
trace(o.textHeight);
trace(o.textWidth);
trace(o.bottomScroll);
trace(o.length);
trace(o.selectable);
trace(o.multiline);
trace(o.password);
trace(o.wordWrap);
trace(o.background);
trace(o.border);
trace(o.html);
trace(o.embedFonts);
trace(o.maxChars);
trace(o.maxhscroll);
trace(o.hscroll);
trace(o.variable);
trace(o.htmlText);
trace(o.type);
trace(o.text);
trace(o.autoSize);
trace(o.tabIndex);
trace(o.textColor);
trace(o.backgroundColor);
trace(o.borderColor);
trace(o.maxscroll);
trace(o.scroll);
trace(o.filters);
trace(o.sharpness);
trace(o.thickness);
trace(o.antiAliasType);
trace(o.gridFitType);
trace(o.replaceSel);
trace(o.getTextFormat);
trace(o.setTextFormat);
trace(o.removeTextField);
trace(o.getNewTextFormat);
trace(o.setNewTextFormat);
trace(o.getDepth);
trace(o.replaceText);

trace("After set");
o.styleSheet = "test";
o.mouseWheelEnabled = "test";
o.condenseWhite = "test";
o.restrict = "test";
o.textHeight = "test";
o.textWidth = "test";
o.bottomScroll = "test";
o.length = "test";
o.selectable = "test";
o.multiline = "test";
o.password = "test";
o.wordWrap = "test";
o.background = "test";
o.border = "test";
o.html = "test";
o.embedFonts = "test";
o.maxChars = "test";
o.maxhscroll = "test";
o.hscroll = "test";
o.variable = "test";
o.htmlText = "test";
o.type = "test";
o.text = "test";
o.autoSize = "test";
o.tabIndex = "test";
o.textColor = "test";
o.backgroundColor = "test";
o.borderColor = "test";
o.maxscroll = "test";
o.scroll = "test";
o.filters = "test";
o.sharpness = "test";
o.thickness = "test";
o.antiAliasType = "test";
o.gridFitType = "test";
o.replaceSel = "test";
o.getTextFormat = "test";
o.setTextFormat = "test";
o.removeTextField = "test";
o.getNewTextFormat = "test";
o.setNewTextFormat = "test";
o.getDepth = "test";
o.replaceText = "test";
trace(o.styleSheet);
trace(o.mouseWheelEnabled);
trace(o.condenseWhite);
trace(o.restrict);
trace(o.textHeight);
trace(o.textWidth);
trace(o.bottomScroll);
trace(o.length);
trace(o.selectable);
trace(o.multiline);
trace(o.password);
trace(o.wordWrap);
trace(o.background);
trace(o.border);
trace(o.html);
trace(o.embedFonts);
trace(o.maxChars);
trace(o.maxhscroll);
trace(o.hscroll);
trace(o.variable);
trace(o.htmlText);
trace(o.type);
trace(o.text);
trace(o.autoSize);
trace(o.tabIndex);
trace(o.textColor);
trace(o.backgroundColor);
trace(o.borderColor);
trace(o.maxscroll);
trace(o.scroll);
trace(o.filters);
trace(o.sharpness);
trace(o.thickness);
trace(o.antiAliasType);
trace(o.gridFitType);
trace(o.replaceSel);
trace(o.getTextFormat);
trace(o.setTextFormat);
trace(o.removeTextField);
trace(o.getNewTextFormat);
trace(o.setNewTextFormat);
trace(o.getDepth);
trace(o.replaceText);

trace("After delete");
delete o.styleSheet;
delete o.mouseWheelEnabled;
delete o.condenseWhite;
delete o.restrict;
delete o.textHeight;
delete o.textWidth;
delete o.bottomScroll;
delete o.length;
delete o.selectable;
delete o.multiline;
delete o.password;
delete o.wordWrap;
delete o.background;
delete o.border;
delete o.html;
delete o.embedFonts;
delete o.maxChars;
delete o.maxhscroll;
delete o.hscroll;
delete o.variable;
delete o.htmlText;
delete o.type;
delete o.text;
delete o.autoSize;
delete o.tabIndex;
delete o.textColor;
delete o.backgroundColor;
delete o.borderColor;
delete o.maxscroll;
delete o.scroll;
delete o.filters;
delete o.sharpness;
delete o.thickness;
delete o.antiAliasType;
delete o.gridFitType;
delete o.replaceSel;
delete o.getTextFormat;
delete o.setTextFormat;
delete o.removeTextField;
delete o.getNewTextFormat;
delete o.setNewTextFormat;
delete o.getDepth;
delete o.replaceText;
trace(o.styleSheet);
trace(o.mouseWheelEnabled);
trace(o.condenseWhite);
trace(o.restrict);
trace(o.textHeight);
trace(o.textWidth);
trace(o.bottomScroll);
trace(o.length);
trace(o.selectable);
trace(o.multiline);
trace(o.password);
trace(o.wordWrap);
trace(o.background);
trace(o.border);
trace(o.html);
trace(o.embedFonts);
trace(o.maxChars);
trace(o.maxhscroll);
trace(o.hscroll);
trace(o.variable);
trace(o.htmlText);
trace(o.type);
trace(o.text);
trace(o.autoSize);
trace(o.tabIndex);
trace(o.textColor);
trace(o.backgroundColor);
trace(o.borderColor);
trace(o.maxscroll);
trace(o.scroll);
trace(o.filters);
trace(o.sharpness);
trace(o.thickness);
trace(o.antiAliasType);
trace(o.gridFitType);
trace(o.replaceSel);
trace(o.getTextFormat);
trace(o.setTextFormat);
trace(o.removeTextField);
trace(o.getNewTextFormat);
trace(o.setNewTextFormat);
trace(o.getDepth);
trace(o.replaceText);
