use super::AvmAtom;
use gc_arena::Collect;

macro_rules! define_common_strings_impl {
    (
        $ascii:ident,
        $($field:ident: $str:literal,)*
    ) => {
        #[allow(non_snake_case)]
        #[derive(Collect)]
        #[collect(no_drop)]
        pub struct CommonStrings<'gc> {
            pub $ascii: [AvmAtom<'gc>; ASCII_CHARS_LEN],

            $(
                pub $field: AvmAtom<'gc>,
            )*
        }

        impl<'gc> CommonStrings<'gc> {
            pub(super) fn new(mut intern_from_static: impl FnMut(&'static [u8]) -> AvmAtom<'gc>) -> Self {
                Self {
                    $ascii: std::array::from_fn(|i| {
                        let c = &ASCII_CHARS[i];
                        intern_from_static(std::slice::from_ref(c))
                    }),
                    $($field: intern_from_static($str)),*
                }
            }
        }
    };
}

const ASCII_CHARS_LEN: usize = 0x80;
static ASCII_CHARS: [u8; ASCII_CHARS_LEN] = {
    let mut chs = [0; ASCII_CHARS_LEN];
    let mut i = 0;
    while i < chs.len() {
        chs[i] = i as u8;
        i += 1;
    }
    chs
};

ruffle_macros::define_common_strings! {
    ascii_chars,

    // Order alphabetically.
    //
    // The generated field name is the string prefixed with `str_` with
    // non-alphanumeric characters escaped using `_`.
    "",
    "__constructor__",
    "__proto__",
    "__resolve",
    "_bytesLoaded",
    "_bytesTotal",
    "_css",
    "_listeners",
    "_styles",
    "-Infinity",
    "[object Object]",
    "[type Function]",
    "[type Object]",
    "aa",
    "ab",
    "access",
    "accessors",
    "addListener",
    "advanced",
    "album",
    "alphaMultiplier",
    "alphaOffset",
    "always",
    "arguments",
    "artist",
    "ascent",
    "asyncError",
    "attributeAdded",
    "attributeChanged",
    "auto",
    "ba",
    "baseline",
    "baselineConstrained",
    "baselineExtended",
    "bases",
    "bb",
    "bigEndian",
    "block",
    "blueMultiplier",
    "blueOffset",
    "bold",
    "boldItalic",
    "boolean",
    "Boolean",
    "broadcastMessage",
    "builtInItems",
    "bytesLoaded",
    "bytesTotal",
    "callee",
    "caller",
    "caption",
    "center",
    "clamp",
    "click",
    "code",
    "color",
    "comment",
    "complete",
    "constructor",
    "customItems",
    "data",
    "declaredBy",
    "decode",
    "descent",
    "description",
    "device",
    "doubleClick",
    "duration",
    "dynamic",
    "embedded",
    "embeddedCFF",
    "enabled",
    "error",
    "extension",
    "false",
    "flushed",
    "focusEnabled",
    "fontStyle",
    "fontWeight",
    "forward_back",
    "full",
    "fullScreen",
    "function",
    "ga",
    "gb",
    "genre",
    "global",
    "greenMultiplier",
    "greenOffset",
    "height",
    "httpStatus",
    "id3",
    "ignore",
    "ignoreWhite",
    "index",
    "Infinity",
    "inline",
    "inner",
    "input",
    "interfaces",
    "ioError",
    "isDynamic",
    "isFinal",
    "isStatic",
    "italic",
    "justify",
    "key",
    "Key",
    "keyDown",
    "keyUp",
    "left",
    "length",
    "level",
    "littleEndian",
    "ll",
    "loaded",
    "localhost",
    "localName",
    "loop",
    "lr",
    "macType",
    "matrixType",
    "menu",
    "menuItemSelect",
    "menuSelect",
    "message",
    "metadata",
    "methods",
    "middleClick",
    "middleMouseDown",
    "middleMouseUp",
    "Mouse",
    "mouseDown",
    "mouseMove",
    "mouseOut",
    "mouseOver",
    "mouseUp",
    "mouseWheel",
    "movieclip",
    "name",
    "nameSet",
    "NaN",
    "netStatus",
    "never",
    "none",
    "normal",
    "null",
    "number",
    "Number",
    "object",
    "onCancel",
    "onChanged",
    "onClose",
    "onComplete",
    "onConnect",
    "onConstruct",
    "onData",
    "onDragOut",
    "onDragOver",
    "onEnterFrame",
    "onFullScreen",
    "onHTTPError",
    "onHTTPStatus",
    "onID3",
    "onIOError",
    "onKeyDown",
    "onKeyUp",
    "onLoad",
    "onLoadComplete",
    "onLoadError",
    "onLoadInit",
    "onLoadProgress",
    "onLoadStart",
    "onMouseDown",
    "onMouseMove",
    "onMouseUp",
    "onMouseWheel",
    "onOpen",
    "onPress",
    "onProgress",
    "onRelease",
    "onReleaseOutside",
    "onResize",
    "onResult",
    "onRollOut",
    "onRollOver",
    "onScroller",
    "onSelect",
    "onSetFocus",
    "onStatus",
    "onUnload",
    "onXML",
    "optional",
    "outer",
    "parameters",
    "parse",
    "parseXML",
    "pixel",
    "play",
    "position",
    "prefix",
    "print",
    "prototype",
    "push",
    "quality",
    "ra",
    "rb",
    "readonly",
    "readwrite",
    "redMultiplier",
    "redOffset",
    "regular",
    "releaseOutside",
    "removeListener",
    "returnType",
    "rewind",
    "right",
    "rightClick",
    "rightMouseDown",
    "rightMouseUp",
    "rl",
    "rollOut",
    "rollOver",
    "rr",
    "save",
    "Selection",
    "separatorBefore",
    "songname",
    "splice",
    "Stage",
    "standard",
    "standardConstrained",
    "standardExtended",
    "status",
    "string",
    "String",
    "subpixel",
    "subtract",
    "success",
    "super",
    "tabChildren",
    "tabEnabled",
    "target",
    "textFieldHeight",
    "textFieldWidth",
    "TextSnapshot",
    "toJSON",
    "toString",
    "toXMLString",
    "track",
    "traits",
    "transform",
    "true",
    "tx",
    "ty",
    "type",
    "undefined",
    "uri",
    "useHandCursor",
    "value",
    "valueOf",
    "variables",
    "visible",
    "void",
    "width",
    "wrap",
    "writeonly",
    "xMax",
    "xMin",
    "xml",
    "year",
    "yMax",
    "yMin",
    "zoom",
}
