[package]
name = "flv-rs"
version.workspace = true
authors = ["David Wendt <dcrkid@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = { workspace = true }
thiserror = { workspace = true }
