context-menu-play = Afspelen
context-menu-rewind = Terugspoelen
context-menu-forward = Doorspoelen
context-menu-back = Terug
context-menu-quality-low = Kwaliteit: laag
context-menu-quality-medium = Kwaliteit: midden
context-menu-quality-high = Kwaliteit: hoog
context-menu-cut = Knippen
context-menu-copy = Kopiëren
context-menu-paste = Plakken
context-menu-delete = Verwijderen
context-menu-select-all = Alles selecteren
