// =============================================================================
// wasm64 vendoring shim — TEMPORARY. REMOVE WHEN UPSTREAM SHIPS wasm64 SUPPORT.
//
// Each crate listed in VENDORED below has cfg gates written `target_arch =
// "wasm32"` where it actually means "any WebAssembly". On wasm64 those gates do
// not fire, so the crate's web code paths (and web-only dependencies) are
// excluded and the build fails. This shim fetches the crate source, widens
// `target_arch = "wasm32"` -> `target_family = "wasm"` (which covers wasm32 AND
// wasm64), and wires the patched copy through [patch.crates-io].
//
// HOW TO REMOVE PROGRESSIVELY: when a crate publishes a wasm64-aware release,
// delete its entry from VENDORED. The [patch.crates-io] block (regenerated from
// this table, between the markers in the root Cargo.toml) shrinks automatically.
// When VENDORED is empty, delete this file, its call in build_wasm.ts, and the
// marker block in Cargo.toml.
//
// NOTE: `getrandom` is NOT handled here — its upstream wasm64 fix (PR #848) only
// exists in the 0.4.x series while `rand 0.9` pins 0.3.x, so it uses a custom
// backend instead (web/src/getrandom_custom.rs).
// =============================================================================

import { execFileSync } from "child_process";
import {
    cpSync,
    existsSync,
    mkdirSync,
    readFileSync,
    readdirSync,
    rmSync,
    writeFileSync,
} from "fs";
import * as os from "os";
import * as path from "path";

interface VendoredCrate {
    name: string;
    // Prepend `#![allow(warnings)]` to lib.rs to silence this third-party crate's
    // own lints (they surface only because it becomes a path dependency here).
    allowWarnings?: boolean;
    // Substring-matched path filters. When set, files whose absolute path
    // contains any of these substrings are NOT cfg-widened. Use this for crates
    // where only some `target_arch = "wasm32"` gates mean "any wasm" — e.g.
    // jpeg-decoder's `src/arch/` uses wasm32-specific SIMD intrinsics that
    // simply don't exist on wasm64; only the worker-threading gates outside
    // that subtree should be widened.
    skipPaths?: string[];
}

// The crates to vendor+patch. Trim this as upstreams gain native wasm64 support.
const VENDORED: VendoredCrate[] = [
    { name: "wgpu" },
    { name: "wgpu-types" },
    { name: "wgpu-core" },
    { name: "wgpu-hal" },
    { name: "wgpu-core-deps-wasm" },
    { name: "chrono" },
    { name: "glow", allowWarnings: true },
    { name: "rfd", allowWarnings: true },
    // jpeg-decoder: the multi-threaded worker is `not(wasm32)`-gated, so on
    // wasm64 it gets compiled and tries to use threads → "Invalid JPEG" at
    // runtime. Widen the worker gates only; leave `src/arch/` alone because
    // its SIMD code uses `std::arch::wasm32::*` intrinsics.
    {
        name: "jpeg-decoder",
        skipPaths: ["src/arch/"],
        allowWarnings: true,
    },
];

const PATCH_BEGIN =
    "# >>> wasm64-vendor (auto-generated by tools/vendor_wasm64.ts — REMOVE WHEN UPSTREAM SHIPS wasm64) >>>";
const PATCH_END = "# <<< wasm64-vendor <<<";

const REPO_ROOT = path.resolve(__dirname, "../../../..");
const VENDOR_DIR = path.join(REPO_ROOT, "vendor");
const CARGO_LOCK = path.join(REPO_ROOT, "Cargo.lock");
const CARGO_TOML = path.join(REPO_ROOT, "Cargo.toml");

const WASM32 = 'target_arch = "wasm32"';
const WASM_FAMILY = 'target_family = "wasm"';

/** Resolve the exact version cargo picked for a crate, from Cargo.lock. */
function lockedVersion(crate: string): string {
    const lock = readFileSync(CARGO_LOCK, "utf8");
    const re = new RegExp(
        `\\[\\[package\\]\\]\\nname = "${crate}"\\nversion = "([^"]+)"`,
    );
    const m = lock.match(re);
    if (!m) {
        throw new Error(`vendor_wasm64: "${crate}" not found in Cargo.lock`);
    }
    return m[1]!;
}

/** Get the crate source into `dest`: prefer the offline cargo cache, else download. */
function fetchSource(crate: string, version: string, dest: string) {
    rmSync(dest, { recursive: true, force: true });

    const registries = path.join(os.homedir(), ".cargo", "registry", "src");
    if (existsSync(registries)) {
        for (const idx of readdirSync(registries)) {
            const cached = path.join(registries, idx, `${crate}-${version}`);
            if (existsSync(cached)) {
                cpSync(cached, dest, { recursive: true });
                return;
            }
        }
    }

    console.log(`    downloading ${crate} ${version} from crates.io`);
    const url = `https://static.crates.io/crates/${crate}/${crate}-${version}.crate`;
    const tmp = path.join(os.tmpdir(), `${crate}-${version}.crate`);
    execFileSync("curl", ["-sSfL", url, "-o", tmp], { stdio: "inherit" });
    mkdirSync(dest, { recursive: true });
    // A .crate is a .tar.gz whose entries live under `<crate>-<version>/`.
    execFileSync("tar", ["-xzf", tmp, "-C", dest, "--strip-components=1"], {
        stdio: "inherit",
    });
    rmSync(tmp, { force: true });
}

/** Widen every `target_arch="wasm32"` to `target_family="wasm"`. Returns count. */
function widenCfgGates(dir: string, skipPaths?: string[]): number {
    let count = 0;
    const walk = (d: string) => {
        for (const entry of readdirSync(d, { withFileTypes: true })) {
            const p = path.join(d, entry.name);
            if (entry.isDirectory()) {
                walk(p);
            } else if (entry.name.endsWith(".rs") || entry.name === "Cargo.toml") {
                if (skipPaths?.some((s) => p.includes(path.normalize(s)))) {
                    continue;
                }
                const before = readFileSync(p, "utf8");
                const occurrences = before.split(WASM32).length - 1;
                if (occurrences > 0) {
                    writeFileSync(p, before.split(WASM32).join(WASM_FAMILY));
                    count += occurrences;
                }
            }
        }
    };
    walk(dir);
    return count;
}

function prependAllowWarnings(dir: string) {
    const libRs = path.join(dir, "src", "lib.rs");
    if (!existsSync(libRs)) {
        return;
    }
    const content = readFileSync(libRs, "utf8");
    if (content.includes("#![allow(warnings)]")) {
        return;
    }
    writeFileSync(
        libRs,
        `#![allow(warnings)] // wasm64 vendoring: silence vendored-crate lints\n${content}`,
    );
}

function isPatched(dir: string, version: string): boolean {
    const marker = path.join(dir, ".wasm64-patched");
    return existsSync(marker) && readFileSync(marker, "utf8").trim() === version;
}

/** Rewrite the [patch.crates-io] block (between markers) from VENDORED. */
function regeneratePatchBlock() {
    const block = [
        PATCH_BEGIN,
        "# The vendor/ directories below are gitignored and populated on demand.",
        "# Run `tsx web/packages/core/tools/vendor_wasm64.ts` from the repo root before",
        "# any standalone cargo build (the web pipeline runs this automatically).",
        "[patch.crates-io]",
        ...VENDORED.map((c) => `${c.name} = { path = "vendor/${c.name}" }`),
        PATCH_END,
    ].join("\n");

    const original = readFileSync(CARGO_TOML, "utf8");
    let toml = original;
    const begin = toml.indexOf(PATCH_BEGIN);
    const end = toml.indexOf(PATCH_END);
    if (begin !== -1 && end !== -1) {
        toml = toml.slice(0, begin) + block + toml.slice(end + PATCH_END.length);
    } else {
        toml = `${toml.trimEnd()}\n\n${block}\n`;
    }
    // Only touch the file when something actually changed — keeps cargo's
    // workspace cache fresh and avoids dirtying `git status` on no-op runs.
    if (toml !== original) {
        writeFileSync(CARGO_TOML, toml);
    }
}

/**
 * Ensure all vendored+patched crates exist and the [patch.crates-io] block is
 * in sync. Idempotent: already-patched crates (matching the locked version) are
 * skipped. Call this before any cargo invocation that relies on the patches.
 */
export function ensureWasm64Vendored() {
    console.log("Preparing wasm64 vendored crates...");
    mkdirSync(VENDOR_DIR, { recursive: true });
    let newlyVendored = 0;
    for (const c of VENDORED) {
        const version = lockedVersion(c.name);
        const dest = path.join(VENDOR_DIR, c.name);
        if (isPatched(dest, version)) {
            continue;
        }
        console.log(`  vendoring ${c.name} ${version}`);
        fetchSource(c.name, version, dest);
        const replaced = widenCfgGates(dest, c.skipPaths);
        if (replaced === 0) {
            throw new Error(
                `vendor_wasm64: no '${WASM32}' found in ${c.name} ${version} — the crate ` +
                    `likely changed or already supports wasm64. Review and remove its VENDORED entry.`,
            );
        }
        if (c.allowWarnings) {
            prependAllowWarnings(dest);
        }
        writeFileSync(path.join(dest, ".wasm64-patched"), version);
        newlyVendored++;
    }
    regeneratePatchBlock();
    if (newlyVendored > 0) {
        // Cargo.lock pins each crate to its source. When a new entry appears in
        // VENDORED above, the lock still points at registry+...; subsequent
        // `cargo build --locked` invocations then refuse to update it. Sync the
        // lock offline now (the just-vendored sources are already in the cargo
        // cache) so the very next `cargo build --locked` succeeds without
        // manual intervention.
        console.log("Realigning Cargo.lock with the new patches...");
        execFileSync("cargo", ["update", "--workspace", "--offline"], {
            cwd: REPO_ROOT,
            stdio: "inherit",
        });
    }
    console.log("wasm64 vendored crates ready.");
}

// Allow running standalone (e.g. before a non-web cargo build): `tsx tools/vendor_wasm64.ts`.
if (require.main === module) {
    ensureWasm64Vendored();
}
