// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/sensors/Geolocation.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.sensors
{
    import flash.events.EventDispatcher;
    import flash.permissions.PermissionStatus;
    import __ruffle__.stub_getter;
    import __ruffle__.stub_setter;

    public class Geolocation extends EventDispatcher
    {
        // <<< iOS only
        // The best level of accuracy available.
        public static const LOCATION_ACCURACY_BEST:String = "locationAccuracyBest"

        // The highest possible accuracy that uses additional sensor data to facilitate navigation apps.
        public static const LOCATION_ACCURACY_BEST_FOR_NAVIGATION:String = "locationAccuracyBestForNavigation";

        // Accurate to within one hundred meters.
        public static const LOCATION_ACCURACY_HUNDRED_METERS:String = "locationAccuracyHundredMeters";

        // Accurate to the nearest kilometer.
        public static const LOCATION_ACCURACY_KILOMETER:String = "locationAccuracyKilometer";

        // Accurate to within ten meters of the desired target.
        public static const LOCATION_ACCURACY_NEAREST_TEN_METERS:String = "locationAccuracyNearestTenMeters";

        // Accurate to the nearest three kilometers.
        public static const LOCATION_ACCURACY_THREE_KILOMETERS:String = "locationAccuracyThreeKilometers";
        // iOS only >>>

        public function Geolocation()
        {
            this.init();
        }

        private native function init():void;

        // Shows a geolocation permission dialog on mobile devices
        // We actually don't need to implement this function because
        // we ask permission right when a class is created
        public function requestPermission():void {};

        // A status of geolocation permission on mobile devices
        public native static function get permissionStatus():String;

        // Whether a location sensor is available on the device (true); otherwise false.
        public native static function get isSupported():Boolean;

        // Specifies whether the user has denied access to the geolocation (true) or allowed access (false).
        public native function get muted():Boolean;

        // Used to set the time interval for updates, in milliseconds.
        // The actual time between geolocation updates may be greater or lesser than this value.
        // https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/sensors/Geolocation.html#setRequestedUpdateInterval()
        public native function setRequestedUpdateInterval(interval:Number):void;

        // This property determines the access permission type usage of geolocation.
        public function get locationAlwaysUsePermission():Boolean {
            stub_getter("flash.sensors.Geolocation", "locationAlwaysUsePermission");
            return false;
        }

        public function set locationAlwaysUsePermission(value:Boolean):void {
            stub_setter("flash.sensors.Geolocation", "locationAlwaysUsePermission");
        }

        // This property determines the accuracy of the geolocation data on iOS.
        public function get desiredAccuracy():String {
            stub_getter("flash.sensors.Geolocation", "desiredAccuracy");
            return Geolocation.LOCATION_ACCURACY_BEST;
        }

        public function set desiredAccuracy(value:String):void {
            stub_setter("flash.sensors.Geolocation", "desiredAccuracy");
        }

        // This property determines whether the geolocation services should pause due to app inactivity when application goes into background (on iOS).
        public function get pausesLocationUpdatesAutomatically():Boolean {
            stub_getter("flash.sensors.Geolocation", "pausesLocationUpdatesAutomatically");
            return true;
        }

        public function set pausesLocationUpdatesAutomatically(value:Boolean):void {
            stub_setter("flash.sensors.Geolocation", "pausesLocationUpdatesAutomatically");
        }
    }
}
