about-ruffle = Ruffleについて
about-ruffle-version = バージョン
about-ruffle-channel = チャンネル
about-ruffle-build-time = ビルド日時
about-ruffle-build-features = 含まれる機能
about-ruffle-commit-ref = コミット ハッシュ
about-ruffle-commit-time = コミット日時
about-ruffle-visit-website = ウェブサイト
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = スポンサー
