network-settings = ネットワーク設定
player-settings = プレイヤー設定
movie-parameters = 映像パラメーター
custom-base-url = カスタムベースURL
spoof-swf-url = SWFのURLを偽装
referer-url = リファラ URL
cookie = Cookie
proxy = プロキシ
upgrade-http = HTTPをHTTPSに置き換え
tcp-connections = TCP接続
tcp-connections-allow = 許可する
tcp-connections-ask = 要求する
tcp-connections-deny = 拒否する
open-url-mode = リンクを開く
open-url-mode-allow = 許可する
open-url-mode-confirm = 聞く
open-url-mode-deny = 拒否する
load-behavior = 読み込み方法
load-behavior-streaming = ストリーミング
load-behavior-delayed = 遅延
load-behavior-blocking = ブロック
max-execution-duration = 最大実行時間
max-execution-duration-suffix = { " " } 秒
quality = クオリティ
quality-low = 低
quality-medium = 中
quality-high = 高
quality-best = 最適
quality-high8x8 = 高(8x8)
quality-high8x8linear = 高(8x8) リニアsRGB
quality-high16x16 = 高(16x16)
quality-high16x16linear = 高(16x16) リニアsRGB
letterbox = レターボックス
letterbox-on = オン
letterbox-fullscreen = フルスクリーンのみ
letterbox-off = オフ
align = ステージ位置
align-center = 中心
align-left = 左
align-right = 右
align-top = 上
align-bottom = 下
align-top-left = 左上
align-bottom-left = 左下
align-top-right = 右上
align-bottom-right = 右下
align-force = 強制
scale-mode = スケールモード
scale-mode-noscale = 拡大しない(100%)
scale-mode-noscale-tooltip =
    ムービーを拡大せず、オリジナルのサイズで表示する。
    
    StageScaleMode.NO_SCALEに一致します。
scale-mode-showall = ウィンドウに合わせる
scale-mode-exactfit = 引き伸ばす
scale-mode-force = 強制
scale-mode-force-tooltip = ムービーによるスケールモードの変更を抑制し、現在の設定を保持する。
player-version = プレイヤーのバージョン
player-runtime = プレイヤーのランタイム環境
player-runtime-flash = Flashプレイヤー
player-runtime-air = Adobe AIR
custom-framerate = カスタムフレームレート
custom-framerate-suffix = { " " } fps
dummy-external-interface = ダミー外部インターフェース
