file-picker-title-open-file = Öppna en fil
file-picker-title-open-directory = Öppna en mapp
file-picker-filter-supported = Alla stödda filer
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Ruffle-paket (*.ruf)
file-picker-filter-all = Alla filer
file-picker-select-root-movie-title = Välj rotfilm
file-picker-select-root-movie-message = Välj rotfilmen i den öppnade mappen.
file-picker-select-root-movie-select = Välj
