file-picker-title-open-file = Öppna en fil
file-picker-title-open-directory = Öppna en mapp
file-picker-filter-supported = Alla stödda filer
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Ruffle Bundle (*.ruf)
file-picker-filter-all = Alla filer
file-picker-select-root-movie-title = Välj rot-film
file-picker-select-root-movie-message = Välj rot-film för den öppna filkatalogen.
file-picker-select-root-movie-select = Välj
