preferences-dialog = Ruffle-inställningar
preference-locked-by-cli = Endast läsbar (sätt av CLI:n)
graphics-backend = Grafik-backend
graphics-backend-default = Standard
graphics-power = Energialternativ
graphics-power-low = Låg (t.ex. iGPU)
graphics-power-high = Hög (t.ex. GPU)
language = Språk
audio-output-device = Ljudutgångsenhet
audio-output-device-default = Systemstandard
