network-settings = Nätverksinställningar
player-settings = Spelarinställningar
movie-parameters = Filmparametrar
custom-base-url = Anpassad Bas-URL
spoof-swf-url = Förfalska SWF-URL
proxy = Proxy
upgrade-http = Uppgradera HTTP till HTTPS
tcp-connections = TCP-anslutningar
tcp-connections-allow = Tillåt
tcp-connections-ask = Fråga
tcp-connections-deny = Neka
open-url-mode = Öppna Länkar
open-url-mode-allow = Tillåt
open-url-mode-confirm = Fråga
open-url-mode-deny = Neka
load-behavior = Laddningsbeteende
load-behavior-streaming = Streamad
load-behavior-delayed = Fördröjd
load-behavior-blocking = Blockerad
max-execution-duration = Max Exekveringstid
max-execution-duration-suffix = { " " } sekunder
quality = Kvalitet
quality-low = Låg
quality-medium = Medel
quality-high = Hög
quality-best = Bäst
quality-high8x8 = Hög (8x8)
quality-high8x8linear = Hög (8x8) Linjär
quality-high16x16 = Hög (16x16)
quality-high16x16linear = Hög (16x16) Linjär
letterbox = Letterbox
letterbox-on = På
letterbox-fullscreen = Endast Helskärm
letterbox-off = Av
align = Scenplacering
align-center = Centrerat
align-left = Vänster
align-right = Höger
align-top = Överst
align-bottom = Nederst
align-top-left = Överst till vänster
align-bottom-left = Nederst till vänster
align-top-right = Överst till höger
align-bottom-right = Nederst till höger
align-force = Tvinga
scale-mode = Skalningsläge
scale-mode-force = Tvinga
player-version = Spelarversion
custom-framerate = Anpassad Bildhastighet
custom-framerate-suffix = { " " } fps
dummy-external-interface = Dummy Externt Gränssnitt
