network-settings = Nätverksinställningar
player-settings = Spelarinställningar
movie-parameters = Filmparametrar
custom-base-url = Anpassad Bas-URL
spoof-swf-url = Förfalska SWF URL
proxy = Proxy
upgrade-http = Uppgradera HTTP till HTTPS
upgrade-http-check = Uppgradera
open-url-mode = Öppna URL-läge
open-url-mode-allow = Tillåt
open-url-mode-confirm = Bekräfta
open-url-mode-deny = Neka
load-behavior = Laddningsbeteende
load-behavior-streaming = Streamad
load-behavior-delayed = Fördröjd
load-behavior-blocking = Blockerad
max-execution-duration = Max Exekveringstid
max-execution-duration-suffix = { " " } sekunder
quality = Kvalitet
quality-low = Låg
quality-medium = Medel
quality-high = Hög
quality-best = Bäst
quality-high8x8 = Hög (8x8)
quality-high8x8linear = Hög (8x8) Linjär
quality-high16x16 = Hög (16x16)
quality-high16x16linear = Hög (16x16) Linjär
align = Scenplacering
align-center = Center
align-left = Vänster
align-right = Höger
align-top = Topp
align-bottom = Nederst
align-top-left = Överst till vänster
align-bottom-left = Nederst till vänster
align-top-right = Överst till höger
align-bottom-right = Nederst till höger
align-force = Tvinga
scale-mode = Skalningsläge
scale-mode-exactfit = Exakt Passform
scale-mode-noborder = Ingen Ram
scale-mode-noscale = Ingen Skalning
scale-mode-showall = Visa Allt
scale-mode-force = Tvinga
warn-if-unsupported = Varna om ej stöds
warn-if-unsupported-check = Varna
player-version = Spelarversion
custom-framerate = Anpassad Bildfrekvens
custom-framerate-suffix = { " " } fps
dummy-external-interface = Dummy Externt Gränssnitt
dummy-external-interface-check = Aktivera
