context-menu-play = Reproducir
context-menu-rewind = Rebobinar
context-menu-forward = Avanzar
context-menu-back = Retroceder
context-menu-quality-low = Calidad: baja
context-menu-quality-medium = Calidad: media
context-menu-quality-high = Calidad: alta
context-menu-cut = Cortar
context-menu-copy = Copiar
context-menu-paste = Pegar
context-menu-delete = Borrar
context-menu-select-all = Seleccionar todo
