context-menu-play = Покрените
context-menu-rewind = Премотај уназад
context-menu-forward = Напред
context-menu-back = Назад
context-menu-quality-low = Квалитет: низак
context-menu-quality-medium = Квалитет: средњи
context-menu-quality-high = Квалитет: висок
context-menu-cut = Исеци
context-menu-copy = Копија
context-menu-paste = Залепи
context-menu-delete = Обриши
context-menu-select-all = Изабери све
