network-settings = Настройки сети
player-settings = Настройки проигрывателя
movie-parameters = Параметры ролика
custom-base-url = Польз. базовый URL
spoof-swf-url = Поддельный URL для SWF
proxy = Прокси
upgrade-http = Заменять HTTP на HTTPS
upgrade-http-check = Заменять
open-url-mode = Режим открытия URL
open-url-mode-allow = Разрешать
open-url-mode-confirm = Подтверждать
open-url-mode-deny = Отклонять
load-behavior = Поведение при загрузке
load-behavior-streaming = Транслировать
load-behavior-delayed = Задерживать
load-behavior-blocking = Блокировать
max-execution-duration = Макс. длительность загрузки
max-execution-duration-suffix = { " " } сек.
quality = Качество
quality-low = Низкое
quality-medium = Среднее
quality-high = Высокое
quality-best = Лучшее
quality-high8x8 = Высокое (8x8)
quality-high8x8linear = Высокое (8x8) линейное
quality-high16x16 = Высокое (16х16)
quality-high16x16linear = Высокое (16x16) линейное
letterbox = Каширование (леттербоксинг)
letterbox-on = Включено
letterbox-fullscreen = Только на весь экран
letterbox-off = Выкл.
align = Выравнивание сцены
align-center = По центру
align-left = Влево
align-right = Вправо
align-top = Вверх
align-bottom = Вниз
align-top-left = Вверх влево
align-bottom-left = Вниз влево
align-top-right = Вверх вправо
align-bottom-right = Вниз вправо
align-force = Принудительно
scale-mode = Режим масштабирования
scale-mode-exactfit = Точный размер
scale-mode-noborder = Без рамок
scale-mode-noscale = Без масштабирования
scale-mode-showall = Показать всё
scale-mode-force = Принудительно
warn-if-unsupported = Предупреждать о несовместимости
warn-if-unsupported-check = Предупреждать
player-version = Версия Flash Player'а
custom-framerate = Польз. частота кадров
custom-framerate-suffix = { " " } FPS
dummy-external-interface = Фиктивный внешний интерфейс
dummy-external-interface-check = Включить
