network-settings = Настройки сети
player-settings = Настройки проигрывателя
movie-parameters = Параметры видео
custom-base-url = Пользовательский базовый URL
spoof-swf-url = Поддельный URL SWF
proxy = Прокси
upgrade-http = Обновить HTTP до HTTPS
upgrade-http-check = Обновить
open-url-mode = Открыть режим URL
open-url-mode-allow = Разрешить
open-url-mode-confirm = Подтвердить
open-url-mode-deny = Отклонить
load-behavior = Поведение при загрузке
load-behavior-streaming = Трансляция
load-behavior-delayed = Задержка
load-behavior-blocking = Блокировка
max-execution-duration = Максимальная продолжительность
max-execution-duration-suffix = { " " } сек
quality = Качество
quality-low = Низкое
quality-medium = Среднее
quality-high = Высокое
quality-best = Лучшее
quality-high8x8 = Высокое (8x8)
quality-high8x8linear = Высокое (8x8) линейное
quality-high16x16 = Высокое (16х16)
quality-high16x16linear = Высокое (16x16) линейное
scale-mode = Режим масштабирования
scale-mode-exactfit = Точный размер
scale-mode-noborder = Без рамок
scale-mode-noscale = Без масштабирования
scale-mode-showall = Показать все
force-scale-mode = Принудительный режим масштабирования
force-scale-mode-check = Принудительный
warn-if-unsupported = Предупредить, если не поддерживается
warn-if-unsupported-check = Предупредить
player-version = Версия проигрывателя
custom-framerate = Пользовательская частота кадров
custom-framerate-suffix = { " " } FPS
