about-ruffle = Sobre o Ruffle
about-ruffle-version = Versão
about-ruffle-channel = Canal
about-ruffle-build-time = Tempo de construção
about-ruffle-build-features = Novidades da Versão
about-ruffle-commit-ref = Referencia do envio
about-ruffle-commit-time = Tempo do envio
about-ruffle-visit-website = Site
about-ruffle-visit-github = Github
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Patrocinador
