about-ruffle = Sobre o Ruffle
about-ruffle-version = Versão
about-ruffle-channel = Canal
about-ruffle-build-time = Data de Compilação
about-ruffle-build-features = Novidades da Versão
about-ruffle-commit-ref = Referência do Envio
about-ruffle-commit-time = Data do Envio
about-ruffle-visit-website = Site
about-ruffle-visit-github = Github
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Patrocinar
