export-bundle-dialog-title = Exportar pacote Ruffle
export-bundle-dialog-bundle-name = Nome do pacote:
export-bundle-dialog-files-description = Selecione os ficheiros a empacotar:
export-bundle-dialog-files-select-all = Selecionar tudo
export-bundle-dialog-export = Exportar
export-bundle-dialog-exporting = A exportar...
export-bundle-dialog-exporting-failed = Falha na exportação.
export-bundle-dialog-error-user-canceled = Cancelado pelo utilizador.
export-bundle-dialog-error-failed-to-show-picker = Falha ao mostrar o seletor de ficheiros.
export-bundle-dialog-error-io-error = Erro ao gravar o pacote.
export-bundle-dialog-info-title = O que é um pacote Ruffle?
export-bundle-dialog-info-description = Um pacote Ruffle é um pacote universal que inclui tudo o que é necessário para executar um ficheiro SWF — todos os recursos e configurações. Com um pacote, o seu SWF funciona à primeira — sem ficheiros em falta nem ajustes manuais, prontinho a usar.
