preferences-dialog = Preferências do Ruffle
preference-locked-by-cli = Apenas leitura (definido por CLI)
graphics-backend = Motor gráfico
graphics-backend-default = Padrão
graphics-power = Preferência de energia
graphics-power-low = Baixa (por exemplo, iGPU)
graphics-power-high = Alta (por exemplo, GPU)
language = Idioma
audio-output-device = Dispositivo de saída de áudio
audio-output-device-default = Padrão do sistema
enable-openh264 = Ativar OpenH264
show-license = Mostrar licença
openh264-license = Licença do OpenH264
log-filename-pattern = Nome do ficheiro de registo
log-filename-pattern-single-file = Ficheiro único (ruffle.log)
log-filename-pattern-with-timestamp = Com data e hora
storage-backend = Localização dos ficheiros de gravação
storage-backend-disk = Disco
storage-backend-memory = Memória
recent-limit = Limite de recentes
recent-clear = Limpar
theme = Tema
theme-system = Padrão do sistema
theme-light = Claro
theme-dark = Escuro
# See for context https://github.com/FeralInteractive/gamemode
gamemode = GameMode
gamemode-tooltip = O GameMode aplica temporariamente um conjunto de otimizações ao computador e/ou ao Ruffle. O Ruffle apenas chama o GameMode quando um filme é reproduzido.
gamemode-default = Padrão
gamemode-default-tooltip = O GameMode só será ativado quando a preferência de energia estiver definida como alta.
# See for context https://wiki.archlinux.org/title/Input_method
ime-enabled = Método de entrada
ime-enabled-experimental = (experimental)
ime-enabled-tooltip = Um método de entrada permite inserir caracteres não disponíveis no teclado, como caracteres chineses, japoneses ou coreanos.
ime-enabled-default = Predefinição
