preferences-dialog = Preferências do Ruffle
preference-locked-by-cli = Apenas leitura (Definido por CLI)
graphics-backend = Saída Gráfica
graphics-backend-default = Padrão
graphics-power = Preferência de Energia
graphics-power-low = Baixa (por exemplo, iGPU)
graphics-power-high = Alta (por exemplo, GPU)
language = Idioma
audio-output-device = Dispositivo de Saída de Áudio
audio-output-device-default = Padrão do Sistema
enable-openh264 = Ativar OpenH264
show-license = Mostrar Licença
openh264-license = Licença do OpenH264
log-filename-pattern = Nome do Ficheiro de Registo
log-filename-pattern-single-file = Ficheiro Único (ruffle.log)
log-filename-pattern-with-timestamp = Com data e hora
storage-backend = Localização dos ficheiros de gravação
storage-backend-disk = Disco
storage-backend-memory = Memória
recent-limit = Limite de Recentes
recent-clear = Limpar
theme = Tema
theme-system = Padrão do Sistema
theme-light = Claro
theme-dark = Escuro
