network-settings = Configurações de Rede
player-settings = Opções do Leitor
movie-parameters = Parâmetros de Filme
custom-base-url = URL Base Personalizado
spoof-swf-url = Disfarçar URL do SWF
proxy = Proxy
upgrade-http = Converter HTTP em HTTPS
tcp-connections = Conexões TCP
tcp-connections-allow = Permitir
tcp-connections-ask = Perguntar
tcp-connections-deny = Recusar
open-url-mode = Abrir Ligações
open-url-mode-allow = Permitir
open-url-mode-confirm = Perguntar
open-url-mode-deny = Negar
load-behavior = Ação ao Abrir
load-behavior-streaming = Transmissão
load-behavior-delayed = Com atraso
load-behavior-blocking = Bloquear
max-execution-duration = Duração Máx. de Execução
max-execution-duration-suffix = { " " } segundos
quality = Qualidade
quality-low = Baixa
quality-medium = Média
quality-high = Alta
quality-best = Máxima
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) Linear
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (16x16) Linear
letterbox = Letterbox
letterbox-on = Ligado
letterbox-fullscreen = Apenas Fullscreen
letterbox-off = Desligado
align = Alinhamento do Palco
align-center = Centro
align-left = Esquerda
align-right = Direita
align-top = Cima
align-bottom = Baixo
align-top-left = Superior esquerdo
align-bottom-left = Inferior esquerdo
align-top-right = Superior direito
align-bottom-right = Inferior direito
align-force = Forçar
scale-mode = Modo de Escala
scale-mode-force = Forçar
player-version = Versão do Leitor
custom-framerate = Taxa de Frames Personalizada
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interface Externa Fictícia
