network-settings = Configurações de Rede
player-settings = Configurações do Jogador
movie-parameters = Parâmetros do filme
custom-base-url = Base URL personalizada
spoof-swf-url = Disfarçar SWF URL
proxy = Opções de procurador
upgrade-http = Atualizar HTTP para HTTPS
upgrade-http-check = Aprimorar
open-url-mode = Abrir modo de URL
open-url-mode-allow = Permitir
open-url-mode-confirm = Confirmar
open-url-mode-deny = Negar
load-behavior = Carregar comportamento
load-behavior-streaming = Transmissão
load-behavior-delayed = Atraso
load-behavior-blocking = Bloqueando
max-execution-duration = Duração máxima de execução
max-execution-duration-suffix = { " " } segundos
quality = Qualidade
quality-low = Baixo
quality-medium = Médio
quality-high = Alto
quality-best = Ótimo
quality-high8x8 = Alto (8x8)
quality-high8x8linear = Alto (8x8) Linear
quality-high16x16 = Alto (16x16)
quality-high16x16linear = Alto (16x16) Linear
align = Alinhamento de fase
align-center = Centralizado
align-left = Esquerda
align-right = Direita
align-top = Cima
align-bottom = Abaixo
align-top-left = Superior-Esquerdo
align-bottom-left = Inferior à Esquerda
align-top-right = Superior direito
align-bottom-right = Inferior direito
align-force = Forçar
scale-mode = Modo de Escala
scale-mode-exactfit = Ajuste exato
scale-mode-noborder = Sem Borda
scale-mode-noscale = Nenhuma Escala
scale-mode-showall = Mostrar tudo
scale-mode-force = Forçar
warn-if-unsupported = Avisar se não suportado
warn-if-unsupported-check = Aviso
player-version = Versão do Jogador
custom-framerate = Fps personalizado
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interface externa falsa
dummy-external-interface-check = Ligar
