context-menu-play = Spill av
context-menu-rewind = Spol tilbake
context-menu-forward = Spole fremover
context-menu-back = Tilbake
context-menu-quality-low = Kvalitet: lav
context-menu-quality-medium = Kvalitet: medium
context-menu-quality-high = Kvalitet: høy
context-menu-copy = Kopier
context-menu-paste = Lim inn
context-menu-delete = Slett
context-menu-select-all = Marker alt
