context-menu-rewind = Premotavanje unazad
context-menu-forward = Naprijed
context-menu-back = Nazad
context-menu-quality-low = Kvalitet: nizak
context-menu-quality-medium = Kvalitet: srednji
context-menu-quality-high = Kvalitet: visok
context-menu-cut = Izrezati
context-menu-copy = Kopiraj
context-menu-paste = Zalijepi
context-menu-delete = Izbriši
context-menu-select-all = Odaberi sve
