context-menu-play = Reprodueix
context-menu-rewind = Rebobina
context-menu-forward = Endavant
context-menu-back = Enrere
context-menu-quality-low = Qualitat: Baixa
context-menu-quality-medium = Qualitat: Mitjana
context-menu-quality-high = Qualitat: Alta
context-menu-cut = Retalla
context-menu-copy = Copia
context-menu-paste = Enganxa
context-menu-delete = Elimina
context-menu-select-all = Selecciona tot
