network-settings = Opcions de xarxa
player-settings = Paràmetres del reproductor
movie-parameters = Paràmetres de pel·lícula
custom-base-url = URL base personalitzada
spoof-swf-url = URL SWF falsa
proxy = Servidor intermediari
upgrade-http = Canvia HTTP a HTTPS
tcp-connections = Connexions TCP
tcp-connections-allow = Permet
tcp-connections-ask = Demana
tcp-connections-deny = Denega
open-url-mode = Obertura d'enllaços
open-url-mode-allow = Permet
open-url-mode-confirm = Demana
open-url-mode-deny = Denega
load-behavior = Comportament de la càrrega
load-behavior-streaming = Transmissió
load-behavior-delayed = Endarrerida
load-behavior-blocking = Bloquejant
max-execution-duration = Durada màxima d'execució
max-execution-duration-suffix = { " " } segons
quality = Qualitat
quality-low = Baixa
quality-medium = Mitjana
quality-high = Alta
quality-best = Millor
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) lineal
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (16x16) lineal
letterbox = Format "letterbox"
letterbox-on = Activa
letterbox-fullscreen = Només en pantalla completa
letterbox-off = Desactiva
align = Alineació de l'escena
align-center = Al centre
align-left = A l'esquerra
align-right = A la dreta
align-top = A dalt
align-bottom = A baix
align-top-left = A dalt a l'esquerra
align-bottom-left = A baix a l'esquerra
align-top-right = A dalt a la dreta
align-bottom-right = A baix a la dreta
align-force = Força
scale-mode = Mode d'escalat
scale-mode-force = Força
player-version = Versió del reproductor
custom-framerate = Freqüència d'imatges personalitzada
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interfície externa fictícia
