about-ruffle = Sobre o Ruffle
about-ruffle-version = Versão
about-ruffle-channel = Canal
about-ruffle-build-time = Data de compilação
about-ruffle-build-features = Recursos de compilação
about-ruffle-commit-ref = Referência do envio
about-ruffle-commit-time = Data do envio
about-ruffle-visit-website = Site
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Patrocinar
