about-ruffle = Sobre o Ruffle
about-ruffle-version = Versão
about-ruffle-channel = Canal
about-ruffle-build-time = Data de compilação
about-ruffle-build-features = Funcionalidades da build
about-ruffle-commit-ref = Referência do commit
about-ruffle-commit-time = Horário do commit
about-ruffle-visit-website = Site
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Patrocinar
