preferences-dialog = Preferências do Ruffle
preference-locked-by-cli = Apenas leitura (Definido por CLI)
graphics-backend = Saída Gráfica
graphics-backend-default = Padrão
graphics-power = Preferência de energia
graphics-power-low = Baixo (por exemplo, iGPU)
graphics-power-high = Alto (por exemplo, GPU)
language = Idioma
audio-output-device = Dispositivo de Saída de Áudio
audio-output-device-default = Padrão do sistema
enable-openh264 = Habilitar OpenH264
show-license = Mostrar licença
openh264-license = Licença do OpenH264
log-filename-pattern = Nome do arquivo de registro
log-filename-pattern-single-file = Arquivo Único (ruffle.log)
log-filename-pattern-with-timestamp = Com data e hora
storage-backend = Localização dos arquivos de save
storage-backend-disk = Disco
storage-backend-memory = Memória
recent-clear = Limpar
theme = Tema
theme-system = Padrão do sistema
theme-light = Claro
theme-dark = Escuro
