network-settings = Configurações de Rede
player-settings = Configurações do Reprodutor
movie-parameters = Parâmetros do Filme
custom-base-url = URL Base personalizada
spoof-swf-url = Disfarçar URL do SWF
proxy = Proxy
upgrade-http = Atualizar HTTP para HTTPS
tcp-connections = Conexões TCP
tcp-connections-allow = Permitir
tcp-connections-ask = Perguntar
tcp-connections-deny = Recusar
open-url-mode = Abrir Links
open-url-mode-allow = Autorizar
open-url-mode-confirm = Perguntar
open-url-mode-deny = Recusar
load-behavior = Comportamento de Carregamento
load-behavior-streaming = Transmissão
load-behavior-delayed = Com atraso
load-behavior-blocking = Bloquear
max-execution-duration = Duração Máxima de Execução
max-execution-duration-suffix = { " " } segundos
quality = Qualidade
quality-low = Baixa
quality-medium = Média
quality-high = Alta
quality-best = Melhor
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) Linear
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (16x16) Linear
letterbox = Tarja Preta
letterbox-on = Ativada
letterbox-fullscreen = Somente Tela Cheia
letterbox-off = Desativada
align = Alinhamento da Fase
align-center = Centro
align-left = Esquerda
align-right = Direita
align-top = Superior
align-bottom = Inferior
align-top-left = Superior-Esquerdo
align-bottom-left = Inferior-Esquerdo
align-top-right = Superior-Direito
align-bottom-right = Inferior-Direito
align-force = Forçar
scale-mode = Modo de Escala
scale-mode-force = Forçar
player-version = Versão do Reprodutor
custom-framerate = Taxa de quadros personalizada
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interface Externa Fictícia
