about-ruffle = 关于 Ruffle
about-ruffle-version = 版本
about-ruffle-channel = 频道
about-ruffle-build-time = 构建时间
about-ruffle-build-features = 构建版本特性
about-ruffle-commit-ref = 提交编号
about-ruffle-commit-time = 提交时间
about-ruffle-visit-website = 网站
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = 赞助
