preferences-dialog = Ruffle 首选项
preference-locked-by-cli = 只读（由 CLI 指定）
graphics-backend = 图形后端
graphics-backend-default = 默认
graphics-power = 性能偏好
graphics-power-low = 低（例如，集成显卡）
graphics-power-high = 高（例如，独立显卡）
language = 语言
audio-output-device = 音频输出设备
audio-output-device-default = 系统默认
enable-openh264 = 启用 OpenH264
show-license = 显示许可证
openh264-license = OpenH264 许可证
log-filename-pattern = 日志文件名
log-filename-pattern-single-file = 单一文件 (ruffle.log)
log-filename-pattern-with-timestamp = 带时间戳
storage-backend = 存档文件位置
storage-backend-disk = 磁盘
storage-backend-memory = 内存
recent-limit = 最近播放数量上限
recent-clear = 清空
theme = 主题
theme-system = 系统默认
theme-light = 浅色
theme-dark = 深色
# See for context https://github.com/FeralInteractive/gamemode
gamemode = GameMode
gamemode-tooltip = GameMode 会对你的电脑和/或 Ruffle 临时应用一系列优化。Ruffle 仅在播放影片时对 GameMode 进行请求。
gamemode-default = 默认
gamemode-default-tooltip = 只有当性能偏好被设置为高时，才会启用GameMode。
