network-settings = 网络设置
player-settings = 播放器设置
movie-parameters = 影片参数
custom-base-url = 自定义基础网址
spoof-swf-url = SWF 网址欺骗
referer-url = 来源链接(Referer)
cookie = Cookie
proxy = 代理
upgrade-http = 升级 HTTP 到 HTTPS
tcp-connections = TCP 连接
tcp-connections-allow = 允许
tcp-connections-ask = 询问
tcp-connections-deny = 拒绝
open-url-mode = 打开链接
open-url-mode-allow = 允许
open-url-mode-confirm = 询问
open-url-mode-deny = 拒绝
load-behavior = 加载方式
load-behavior-streaming = 流
load-behavior-delayed = 延迟
load-behavior-blocking = 阻止
max-execution-duration = 最大执行时长
max-execution-duration-suffix = { " " } 秒
quality = 质量
quality-low = 低
quality-medium = 中
quality-high = 高
quality-best = 最佳
quality-high8x8 = 高 (8x8)
quality-high8x8linear = 高 (8x8) 线性
quality-high16x16 = 高 (16x16)
quality-high16x16linear = 高 (16x16) 线性
letterbox = 宽屏填充黑边
letterbox-on = 开
letterbox-fullscreen = 仅全屏
letterbox-off = 关
align = 舞台对齐
align-center = 居中
align-left = 靠左
align-right = 靠右
align-top = 顶部
align-bottom = 底部
align-top-left = 左上
align-bottom-left = 左下
align-top-right = 右上
align-bottom-right = 右下
align-force = 强制
scale-mode = 缩放模式
scale-mode-exactfit = 精确填充
scale-mode-noborder = 无边框
scale-mode-noscale = 无缩放
scale-mode-showall = 显示全部
scale-mode-force = 强制
player-version = 播放器版本
player-runtime = 运行时系统
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = 自定义帧率
custom-framerate-suffix = { " " } fps
dummy-external-interface = 虚拟外部接口
