network-settings = 网络设置
player-settings = 播放器设置
movie-parameters = 视频参数
custom-base-url = 自定义基础网址
spoof-swf-url = SWF 网址欺骗
proxy = 代理
upgrade-http = 升级 HTTP 到 HTTPS
upgrade-http-check = 升级
open-url-mode = 打开网址模式
open-url-mode-allow = 允许
open-url-mode-confirm = 确认
open-url-mode-deny = 拒绝
load-behavior = 加载方式
load-behavior-streaming = 流
load-behavior-delayed = 延迟
load-behavior-blocking = 阻止
max-execution-duration = 最大执行时长
max-execution-duration-suffix = { " " } 秒
quality = 质量
quality-low = 低
quality-medium = 中
quality-high = 高
quality-best = 最佳
quality-high8x8 = 高 (8x8)
quality-high8x8linear = 高 (8x8) 线性
quality-high16x16 = 高 (16x16)
quality-high16x16linear = 高 (16x16) 线性
scale-mode = 缩放模式
scale-mode-exactfit = 正适合
scale-mode-noborder = 无边框
scale-mode-noscale = 无缩放
scale-mode-showall = 显示全部
force-scale-mode = 强制缩放模式
force-scale-mode-check = 强制
warn-if-unsupported = 不支持时警告
warn-if-unsupported-check = 警告
player-version = 播放器版本
custom-framerate = 自定义帧率
custom-framerate-suffix = { " " } fps
dummy-external-interface = 虚拟外部接口
dummy-external-interface-check = 启用
