// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/errors/IOError.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.errors
{

    public dynamic class IOError extends Error
    {
        prototype.name = "IOError";

        public function IOError(message:String = "", id:int = 0)
        {
            super(message, id);
        }

    }
}

