#[derive(Debug,PartialEq)]
pub enum Action {
    Add,
    And,
    AsciiToChar,
    Call,
    CharToAscii,
    CloneSprite,
    Divide,
    EndDrag,
    Equals,
    GetProperty,
    GetTime,
    GetUrl { url: String, target: String },
    GetUrl2 { send_vars_method: SendVarsMethod, is_target_sprite: bool, is_load_vars: bool },
    GetVariable,
    GotoFrame(u16),
    GotoFrame2 { set_playing: bool, scene_offset: u16 },
    GotoLabel(String),
    If { offset: i16 },
    Jump { offset: i16 },
    Less,
    MBAsciiToChar,
    MBCharToAscii,
    MBStringExtract,
    MBStringLength,
    Multiply,
    NextFrame,
    Not,
    Or,
    Play,
    Pop,
    PreviousFrame,
    Push(Vec<Value>),
    RandomNumber,
    RemoveSprite,
    SetProperty,
    SetTarget(String),
    SetTarget2,
    SetVariable,
    StartDrag,
    Stop,
    StopSounds,
    StringAdd,
    StringEquals,
    StringExtract,
    StringLength,
    StringLess,
    Subtract,
    ToInteger,
    ToggleQuality,
    Trace,
    WaitForFrame { frame: u16, num_actions_to_skip: u8 },
    WaitForFrame2 { num_actions_to_skip: u8 },
    Unknown { opcode: u8, data: Vec<u8> },
}

#[derive(Debug,PartialEq)]
pub enum Value {
    Undefined,
    Null,
    Bool(bool),
    Int(u32),
    Float(f32),
    Double(f64),
    Str(String),
    Register(u8),
    ConstantPool(u16),
}

#[derive(Clone,Copy,Debug,PartialEq,Eq)]
pub enum SendVarsMethod {
    None,
    Get,
    Post,
}