preferences-dialog = Rufflen asetukset
preference-locked-by-cli = Vain luku (komentorivin asettama)
graphics-backend = Grafiikan taustajärjestelmä
graphics-backend-default = Oletus
graphics-power = Tehotila
graphics-power-low = Matala (esim. iGPU)
graphics-power-high = Korkea (esim. GPU)
language = Kieli
audio-output-device = Äänen ulostulolaite
audio-output-device-default = Järjestelmän oletus
enable-openh264 = Käytä OpenH264:ää
show-license = Näytä lisenssi
openh264-license = OpenH264-lisenssi
log-filename-pattern = Lokin tiedostonimi
log-filename-pattern-single-file = Yksi tiedosto (ruffle.log)
log-filename-pattern-with-timestamp = Aikaleiman kera
storage-backend = Tallenna tiedosto -sijainti
storage-backend-disk = Levy
storage-backend-memory = Muisti
recent-limit = Viimeisimpien raja
recent-clear = Tyhjennä
theme = Teema
theme-system = Järjestelmän oletus
theme-light = Vaalea
theme-dark = Tumma
gamemode-default = Oletus
# See for context https://wiki.archlinux.org/title/Input_method
ime-enabled = Syötetapa
ime-enabled-experimental = (kokeellinen)
ime-enabled-default = Oletus
