network-settings = Verkkoasetukset
player-settings = Toistimen asetukset
referer-url = Viittaajan URL-osoite
cookie = Eväste
proxy = Välityspalvelin
upgrade-http = Päivitä HTTP-yhteys HTTPS-yhteydeksi
tcp-connections = TCP-yhteydet
tcp-connections-allow = Salli
tcp-connections-ask = Kysy
tcp-connections-deny = Estä
open-url-mode = Avaa linkit
open-url-mode-allow = Salli
open-url-mode-confirm = Kysy
open-url-mode-deny = Estä
load-behavior-streaming = Suoratoisto
quality = Laatu
quality-low = Matala
quality-medium = Keskitaso
quality-high = Korkea
quality-best = Paras
letterbox-on = Päällä
letterbox-fullscreen = Vain koko näyttö
letterbox-off = Pois
scale-mode = Skaalaustila
scale-mode-noscale = Skaalaamaton (100%)
player-version = Toistimen versio
player-runtime = Toistimen ajoaikainen
player-runtime-air = Adobe AIR
custom-framerate = Mukautettu kuvanopeus
