network-settings = Verkkoasetukset
player-settings = Toistimen asetukset
movie-parameters = Elokuvan parametrit
custom-base-url = Mukautettu pohja-URL
spoof-swf-url = Huijaa SWF:n URL-osoite
referer-url = Viittaajan URL-osoite
cookie = Eväste
proxy = Välityspalvelin
upgrade-http = Päivitä HTTP-yhteys HTTPS-yhteydeksi
tcp-connections = TCP-yhteydet
tcp-connections-allow = Salli
tcp-connections-ask = Kysy
tcp-connections-deny = Estä
open-url-mode = Avaa linkit
open-url-mode-allow = Salli
open-url-mode-confirm = Kysy
open-url-mode-deny = Estä
load-behavior = Latautumisen toiminta
load-behavior-streaming = Suoratoisto
load-behavior-delayed = Viivästetty
load-behavior-blocking = Estävä
max-execution-duration = Suorituksen enimmäiskesto
max-execution-duration-suffix = { " " } s
quality = Laatu
quality-low = Matala
quality-medium = Keskitaso
quality-high = Korkea
quality-best = Paras
quality-high8x8 = Korkea (8x8)
quality-high8x8linear = Korkea (8x8) lineaarinen
quality-high16x16 = Korkea (16x16)
quality-high16x16linear = Korkea (16x16) lineaarinen
letterbox-on = Päällä
letterbox-fullscreen = Vain koko näyttö
letterbox-off = Pois
align = Näyttämön kohdistus
align-center = Keskellä
align-left = Vasemmalla
align-right = Oikealla
align-top = Ylhäällä
align-bottom = Alhaalla
align-top-left = Ylhäällä vasemmalla
align-bottom-left = Alhaalla vasemmalla
align-top-right = Ylhäällä oikealla
align-bottom-right = Alhaalla oikealla
align-force = Pakota
scale-mode = Skaalaustila
scale-mode-noscale = Skaalaamaton (100%)
scale-mode-showall = Sovita lähentämällä
scale-mode-exactfit = Sovita venyttämällä
scale-mode-noborder = Sovita rajaamalla
scale-mode-force = Pakota
scale-mode-force-tooltip = Estää elokuvaa vaihtamasta skaalaustilaa, lukiten sen valittuun asetukseen.
player-version = Toistimen versio
player-runtime = Toistimen ajoaikainen
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Mukautettu kuvanopeus
custom-framerate-suffix = { " " } fps
