network-settings = Nastavenia siete
player-settings = Nastavenie prehrávača
movie-parameters = Parametre filmu
custom-base-url = Vlastná základná URL
spoof-swf-url = Falošná SWF URL
proxy = Proxy
upgrade-http = Zmeniť HTTP na HTTPS
upgrade-http-check = Zmeniť
open-url-mode-allow = Povoliť
open-url-mode-deny = Zamietnuť
load-behavior = Vybrať fungovanie
load-behavior-streaming = Streamovanie
load-behavior-delayed = Oneskorenie
load-behavior-blocking = Blokovanie
max-execution-duration = Maximálna doba vykonávania
max-execution-duration-suffix = { " " } sekúnd
quality = Kvalita
quality-low = Nízka
quality-medium = Stredná
quality-high = Vysoká
quality-best = Najlepšia
quality-high8x8 = Vysoká (8x8)
quality-high8x8linear = Vysoká (8x8) lineárna
quality-high16x16 = Vysoká (16x16)
quality-high16x16linear = Vysoká (16x16) lineárna
scale-mode = Režim natiahnutia
scale-mode-exactfit = Presné umiestnenie
scale-mode-noborder = Bez okrajov
scale-mode-noscale = Bez natiahnutia
scale-mode-showall = Zobraziť všetko
player-version = Verzia prehrávača
custom-framerate = Vlastný Framerate
custom-framerate-suffix = { " " } fps
