network-settings = Nastavenia siete
player-settings = Nastavenie prehrávača
movie-parameters = Parametre filmu
custom-base-url = Vlastná základná URL
spoof-swf-url = Falošná SWF URL
referer-url = Odkazujúci URL odkaz
cookie = Cookie
proxy = Proxy
upgrade-http = Zmeniť HTTP na HTTPS
tcp-connections = TCP pripojenia
tcp-connections-allow = Povoliť
tcp-connections-ask = Opýtať sa
tcp-connections-deny = Odmietnuť
open-url-mode = Otvoriť odkazy
open-url-mode-allow = Povoliť
open-url-mode-confirm = Opýtať sa
open-url-mode-deny = Zamietnuť
load-behavior = Vybrať fungovanie
load-behavior-streaming = Streamovanie
load-behavior-delayed = Oneskorenie
load-behavior-blocking = Blokovanie
max-execution-duration = Maximálna doba vykonávania
max-execution-duration-suffix = { " " } sekúnd
quality = Kvalita
quality-low = Nízka
quality-medium = Stredná
quality-high = Vysoká
quality-best = Najlepšia
quality-high8x8 = Vysoká (8x8)
quality-high8x8linear = Vysoká (8x8) lineárna
quality-high16x16 = Vysoká (16x16)
quality-high16x16linear = Vysoká (16x16) lineárna
letterbox = Letterbox
letterbox-on = Zapnuté
letterbox-fullscreen = Iba celá obrazovka
letterbox-off = Vypnuté
align = Zarovnanie scény
align-center = Stred
align-left = Vľavo
align-right = Vpravo
align-top = Hore
align-bottom = Dole
align-top-left = Vľavo hore
align-bottom-left = Vľavo dole
align-top-right = Vpravo hore
align-bottom-right = Vpravo dole
align-force = Vynútiť
scale-mode = Režim natiahnutia
scale-mode-force = Vynútiť
player-version = Verzia prehrávača
player-runtime = Doba behu prehrávača
player-runtime-flash = Flash prehrávač
player-runtime-air = Adobe AIR
custom-framerate = Vlastný Framerate
custom-framerate-suffix = { " " } fps
dummy-external-interface = Falošné externé rozhranie
