context-menu-play = Lejátszás
context-menu-rewind = Hátra
context-menu-forward = Előre
context-menu-back = Vissza
context-menu-quality-low = Minőség: alacsony
context-menu-quality-medium = Minőség: közepes
context-menu-quality-high = Minőség: magas
context-menu-cut = Kivágás
context-menu-copy = Másolás
context-menu-paste = Beillesztés
context-menu-delete = Törlés
context-menu-select-all = Mind kijelölése
