context-menu-play = Odtwórz
context-menu-rewind = Przewiń
context-menu-forward = Dalej
context-menu-back = Wstecz
context-menu-quality-low = Jakość: niska
context-menu-quality-medium = Jakość: średnia
context-menu-quality-high = Jakość: wysoka
context-menu-cut = Wytnij
context-menu-copy = Skopiuj
context-menu-paste = Wklej
context-menu-delete = Usuń
context-menu-select-all = Zaznacz wszystko
