context-menu-play = تشغيل
context-menu-rewind = إعادة
context-menu-forward = تقدم
context-menu-back = رجوع
context-menu-quality-low = الجودة: منخفضة
context-menu-quality-medium = الجودة: وسط
context-menu-quality-high = الجودة: عالية
context-menu-cut = قص
context-menu-copy = نسخ
context-menu-paste = لصق
context-menu-delete = حذف
context-menu-select-all = تحديد الكل
