context-menu-play = شغّل
context-menu-rewind = أعد
context-menu-forward = للأمام
context-menu-back = للخلف
context-menu-quality-low = الجودة: منخفضة
context-menu-quality-medium = الجودة: متوسطة
context-menu-quality-high = الجودة: عالية
context-menu-cut = قص
context-menu-copy = انسخ
context-menu-paste = الصق
context-menu-delete = احذف
context-menu-select-all = حدِّد الكل
