context-menu-play = تشغيل
context-menu-rewind = إعادة
context-menu-forward = تقدم
context-menu-back = رجوع
context-menu-quality-low = الجودة: منخفضة
context-menu-quality-medium = الجودة: متوسطة
context-menu-quality-high = الجودة: عالية
context-menu-cut = قص
context-menu-copy = إنسخ
context-menu-paste = إلصق
context-menu-delete = إحذف
context-menu-select-all = حدِّد الكل
