context-menu-play = Reproduzir
context-menu-rewind = Rebobinar
context-menu-forward = Avançar
context-menu-back = Recuar
context-menu-quality-low = Qualidade: baixa
context-menu-quality-medium = Qualidade: média
context-menu-quality-high = Qualidade: alta
context-menu-cut = Cortar
context-menu-copy = Copiar
context-menu-paste = Colar
context-menu-delete = Eliminar
context-menu-select-all = Selecionar tudo
