about-ruffle = O Ruffle
about-ruffle-version = Različica
about-ruffle-channel = Kanal
about-ruffle-build-time = Čas gradnje
about-ruffle-build-features = Značilnosti gradnje
about-ruffle-commit-ref = Sklic commita
about-ruffle-commit-time = Čas commita
about-ruffle-visit-website = Spletna stran
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Sponzorirajte
