file-picker-title-open-file = Egy fájl megnyitása
file-picker-title-open-directory = Könyvtár megnyitása
file-picker-filter-supported = Minden támogatott fájl
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Ruffle Köteg (*.ruf)
file-picker-filter-all = Minden fájl
file-picker-select-root-movie-title = Kezdő animáció kiválasztása
file-picker-select-root-movie-message = Válassza ki a kezdő animációt a megnyitott könyvtárból.
file-picker-select-root-movie-select = Kiválasztás
