preferences-dialog = Ruffle beállítások
preference-locked-by-cli = Csak olvasható (parancssorból beállítva)
graphics-backend = Grafikus backend
graphics-backend-default = Alapértelmezett
graphics-power = Teljesítmény preferencia
graphics-power-low = Alacsony (pl. integrált GPU)
graphics-power-high = Magas (pl. dedikált GPU)
language = Nyelv
audio-output-device = Hangkimeneti eszköz
audio-output-device-default = Rendszer alapértelmezett
enable-openh264 = OpenH264 engedélyezése
show-license = Licenc mutatása
openh264-license = OpenH264 licenc
log-filename-pattern = Naplófájl neve
log-filename-pattern-single-file = Egyetlen fájl (ruffle.log)
log-filename-pattern-with-timestamp = Időbélyeggel
storage-backend = Mentésfájlok helye
storage-backend-disk = Lemez
storage-backend-memory = Memória
recent-limit = Legutóbbiak korlátja
recent-clear = Törlés
