preferences-dialog = Ruffle beállítások
preference-locked-by-cli = Csak olvasható (parancssorból beállítva)
graphics-backend = Grafikus backend
graphics-backend-vulkan = Vulkan
graphics-backend-gl = OpenGL
graphics-backend-dx12 = DirectX 12
graphics-backend-metal = Metal
graphics-backend-default = Alapértelmezett
graphics-power = Teljesítmény preferencia
graphics-power-low = Alacsony (pl. integrált GPU)
graphics-power-high = Magas (pl. dedikált GPU)
language = Nyelv
audio-output-device = Hangkimeneti eszköz
audio-output-device-default = Rendszer alapértelmezett
