network-settings = Hálózati beállítások
player-settings = Lejátszó beállításai
movie-parameters = Animáció paraméterei
custom-base-url = Egyedi bázis URL
spoof-swf-url = SWF URL hamisítás
referer-url = Referer URL
cookie = Süti
proxy = Proxy
upgrade-http = HTTP váltása HTTPS-re
tcp-connections = TCP kapcsolatok
tcp-connections-allow = Engedélyezés
tcp-connections-ask = Kérdezzen rá
tcp-connections-deny = Elutasítás
open-url-mode = Hivatkozások megnyitása
open-url-mode-allow = Engedélyezés
open-url-mode-confirm = Kérdezzen rá
open-url-mode-deny = Elutasítás
load-behavior = Betöltési viselkedés
load-behavior-streaming = Streamelt
load-behavior-delayed = Késleltetett
load-behavior-blocking = Blokkoló
max-execution-duration = Maximális futtatási idő
max-execution-duration-suffix = { " " } mp.
quality = Minőség
quality-low = Alacsony
quality-medium = Közepes
quality-high = Magas
quality-best = Legjobb
quality-high8x8 = Magas (8x8)
quality-high8x8linear = Magas (8x8) lineáris
quality-high16x16 = Magas (16x16)
quality-high16x16linear = Magas (16x16) lineáris
letterbox = Letterbox
letterbox-on = Be
letterbox-fullscreen = Csak teljes képernyőn
letterbox-off = Ki
align = Színpad igazítása
align-center = Középre
align-left = Balra
align-right = Jobbra
align-top = Fel
align-bottom = Le
align-top-left = Balra fel
align-bottom-left = Balra le
align-top-right = Jobbra fel
align-bottom-right = Jobbra le
align-force = Kényszerítés
scale-mode = Méretezés módja
scale-mode-exactfit = Pontos illeszkedés
scale-mode-noborder = Szegély nélkül
scale-mode-noscale = Nincs méretezés
scale-mode-showall = Mindent mutat
scale-mode-force = Kényszerítés
player-version = Lejátszó verziója
player-runtime = Futtatókörnyezet
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Egyéni képkockasebesség
custom-framerate-suffix = { " " } FPS
dummy-external-interface = Színlelt külső interfész
