network-settings = Hálózati beállítások
player-settings = Lejátszó beállításai
movie-parameters = Animáció paraméterei
custom-base-url = Egyedi bázis URL
spoof-swf-url = SWF URL hamisítás
proxy = Proxy
upgrade-http = HTTP váltása HTTPS-re
upgrade-http-check = Váltás
open-url-mode = URL megnyitásának módja
open-url-mode-allow = Engedélyezés
open-url-mode-confirm = Megerősítés
open-url-mode-deny = Elutasítás
load-behavior = Betöltési viselkedés
load-behavior-streaming = Streamelt
load-behavior-delayed = Késleltetett
load-behavior-blocking = Blokkoló
max-execution-duration = Maximális futtatási idő
max-execution-duration-suffix = { " " } mp.
quality = Minőség
quality-low = Alacsony
quality-medium = Közepes
quality-high = Magas
quality-best = Legjobb
quality-high8x8 = Magas (8x8)
quality-high8x8linear = Magas (8x8) lineáris
quality-high16x16 = Magas (16x16)
quality-high16x16linear = Magas (16x16) lineáris
scale-mode = Méretezés módja
scale-mode-exactfit = Pontos illeszkedés
scale-mode-noborder = Szegély nélkül
scale-mode-noscale = Nincs méretezés
scale-mode-showall = Mindent mutat
force-scale-mode = Méretezési mód kényszerítése
force-scale-mode-check = Kényszerítés
warn-if-unsupported = Figyelmeztessen ha nem támogatott
warn-if-unsupported-check = Figyelmeztetés
player-version = Lejátszó verziója
custom-framerate = Egyéni képkockasebesség
custom-framerate-suffix = { " " } FPS
