about-ruffle = ﻞﻓﺭ لﻮﺣ
about-ruffle-version = رﺍﺪﺻﻹﺍ
about-ruffle-channel = ةﺎﻨﻘﻟﺍ
about-ruffle-build-time = ﺚﻳﺪﺤﺘﻟﺍ ﺖﻗﻭ
about-ruffle-build-features = ﺚﻳﺪﺤﺘﻟﺍ تﺍﺰﻴﻣ
about-ruffle-commit-ref = رﺎﻌﺘﺴﻤﻟﺍ ﻢﺳﻻﺍ
about-ruffle-commit-time = رﺎﻌﺘﺴﻤﻟﺍ ﻢﺳﻻﺍ ﺖﻴﻗﻮﺗ
about-ruffle-visit-website = ﻲﻧﻭﺮﺘﻜﻟﻹﺍ ﻊﻗﻮﻤﻟﺍ
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = دﺭﻮﻜﺳﺪﻟﺍ
about-ruffle-visit-sponsor = ﻲﻋﺍﺮﻟﺍ
