about-ruffle = حول رفل
about-ruffle-version = الإصدار
about-ruffle-channel = قناة
about-ruffle-build-time = وقت التحديث
about-ruffle-build-features = ميزات التحديث
about-ruffle-commit-ref = الاسم المستعار
about-ruffle-commit-time = توقيت الاسم المستعار
about-ruffle-visit-website = الموقع الإلكتروني
about-ruffle-visit-github = جيت هب
about-ruffle-visit-discord = الدسكورد
about-ruffle-visit-sponsor = الراعي
