network-settings = إعدادات الشبكة
player-settings = إعدادات المشغل
movie-parameters = معامل الفيلم
custom-base-url = رابط الموقع الأساسي
spoof-swf-url = محاكاة رابط SWF
referer-url = الرابط المرجعي
cookie = ملف تعريف الارتباط
proxy = الخادم الوكيل
upgrade-http = ترقية HTTP إلى HTTPS
tcp-connections = اتصالات TCP
tcp-connections-allow = سماح
tcp-connections-ask = طلب
tcp-connections-deny = رفض
open-url-mode = فتح الروابط
open-url-mode-allow = سماح
open-url-mode-confirm = اسأل
open-url-mode-deny = رفض
load-behavior = تحميل السلوك
load-behavior-streaming = البث
load-behavior-delayed = مؤجل
load-behavior-blocking = حجب
max-execution-duration = مدة التنفيذ القصوى
max-execution-duration-suffix = { " " } ثانية
quality = الجودة
quality-low = منخفضة
quality-medium = متوسطة
quality-high = عالية
quality-best = الأفضل
quality-high8x8 = عالية (8x8)
quality-high8x8linear = ارتفاع طولي (8x8)
quality-high16x16 = عالية (16x16)
quality-high16x16linear = ارتفاع طولي (8x8)
letterbox = صندوق الرسائل
letterbox-on = مفعل
letterbox-fullscreen = ملء الشاشة فقط
letterbox-off = مغلق
align = انحياز المسرح
align-center = في الوَسَط
align-left = إلى اليسار
align-right = إلى اليمين
align-top = إلى فوق
align-bottom = إلى أسفل
align-top-left = إلى فوق-يسار
align-bottom-left = إلى أسفل-يسار
align-top-right = إلى فوق-يمين
align-bottom-right = إلى أسفل-يمين
align-force = إجبار
scale-mode = وضع المقياس
scale-mode-exactfit = تلائم تماما
scale-mode-noborder = دون حدود
scale-mode-noscale = لا مقياس
scale-mode-showall = عرض الكل
scale-mode-force = إجبار
player-version = إصدار المشغل
player-runtime = مدة التشغيل
player-runtime-flash = مشغل الفلاش
player-runtime-air = Adobe AIR
custom-framerate = معدل إطار مخصص
custom-framerate-suffix = { " " } معدل الإطار
dummy-external-interface = واجهة خارجية زائفة
