network-settings = ﺔﻜﺒﺸﻟﺍ تﺍﺩﺍﺪﻋﺇ
player-settings = ﻞﻐﺸﻤﻟﺍ تﺍﺩﺍﺪﻋﺇ
movie-parameters = ﻢﻠﻔﻟﺍ ﻞﻣﺎﻌﻣ
custom-base-url = ﻲﺳﺎﺳﻷﺍ ﻊﻗﻮﻤﻟﺍ ﻂﺑﺍﺭ
spoof-swf-url = FWS ﻂﺑﺍﺭ ةﺎﻛﺎﺤﻣ
proxy = ﻞﻴﻛﻭ مﺩﺎﺧ
upgrade-http = SPTTH ﻰﻟﺇ PTTH ﺔﻴﻗﺮﺗ
upgrade-http-check = ﺔﻴﻗﺮﺗ
tcp-connections = PCT تﻻﺎﺼﺗﺍ
tcp-connections-allow = حﺎﻤﺴﻟﺍ
tcp-connections-ask = ﺐﻠﻄ
tcp-connections-deny = ﺾﻓﺭ
open-url-mode = ﻂﺑﺍﻭﺮﻟﺍ ﺢﺘﻓ
open-url-mode-allow = حﺎﻤﺴﻟﺍ
open-url-mode-confirm = لﺄﺳﺍ
open-url-mode-deny = ﺾﻓﺭ
load-behavior = كﻮﻠﺴﻟﺍ ﻞﻴﻤﺤﺗ
load-behavior-streaming = ﺚﺒﻟﺍ
load-behavior-delayed = ﺮﻴﺧﺄﺗ
load-behavior-blocking = ﺐﺠﺣ
max-execution-duration = ىﻮﺼﻘﻟﺍ ﺬﻴﻔﻨﺘﻟﺍ ةﺪﻣ
max-execution-duration-suffix = { " " } ﺔﻴﻧﺎﺛ
quality = ةﺩﻮﺠﻟﺍ
quality-low = ﺔﻀﻔﺨﻨﻣ
quality-medium = ﺔﻄﺳﻮﺘﻣ
quality-high = ﺔﻴﻟﺎﻋ
quality-best = ﻞﻀﻓﻷﺍ
quality-high8x8 = ﺔﻴﻟﺎﻋ (8x8)
quality-high8x8linear = ﻲﻟﻮﻃ عﺎﻔﺗﺭﺍ (8x8)
quality-high16x16 = ﺔﻴﻟﺎﻋ (16x16)
quality-high16x16linear = ﻲﻟﻮﻃ عﺎﻔﺗﺭﺍ (16x16)
letterbox = ﻞﺋﺎﺳﺮﻟﺍ قﻭﺪﻨﺻ
letterbox-on = ﻞﻌﻔﻣ
letterbox-fullscreen = ﻂﻘﻓ ﺔﺷﺎﺸﻟﺍ ءﻞﻣ
letterbox-off = ﻖﻠﻐﻣ
align = حﺮﺴﻤﻟﺍ زﺎﻴﺤﻧﺍ
align-center = ﻂﺳﻮﻟﺍ ﻲﻓ
align-left = رﺎﺴﻴﻟﺍ ﻰﻟﺇ
align-right = ﻦﻴﻤﻴﻟﺍ ﻰﻟﺇ
align-top = قﻮﻓ ﻰﻟﺇ
align-bottom = ﻞﻔﺳﺃ ﻰﻟﺇ
align-top-left = رﺎﺴﻳ-قﻮﻓ ﻰﻟﺇ
align-bottom-left = رﺎﺴﻳ-ﻞﻔﺳﺃ ﻰﻟﺇ
align-top-right = ﻦﻴﻤﻳ-قﻮﻓ ﻰﻟﺇ
align-bottom-right = ﻦﻴﻤﻳ-ﻞﻔﺳﺃ ﻰﻟﺇ
align-force = رﺎﺒﺟﺇ
scale-mode = سﺎﻴﻘﻤﻟﺍ ﻊﺿﻭ
scale-mode-exactfit = ﺎﻣﺎﻤﺗ ﻢﺋﻼﺗ
scale-mode-noborder = دﻭﺪﺣ نﻭﺪﺑ
scale-mode-noscale = سﺎﻴﻘﻣ نﻭﺪﺑ
scale-mode-showall = ﻞﻜﻟﺍ ضﺮﻋ
scale-mode-force = رﺎﺒﺟﺇ
player-version = ﻞﻐﺸﻤﻟﺍ رﺍﺪﺻﺇ
custom-framerate = ﺺﺼﺨﻣ رﺎﻃﺇ لﺪﻌﻣ
custom-framerate-suffix = { " " } ﺔﻴﻧﺎﺜﻟﺍ ﻲﻓ رﺎﻃﺇ
dummy-external-interface = ﺔﻔﺋﺍﺯ ﺔﻴﺟﺭﺎﺧ ﺔﻬﺟﺍﻭ
dummy-external-interface-check = ﻞﻴﻌﻔﺗ
