network-settings = إعدادات الشبكة
player-settings = إعدادات اللاعب
upgrade-http-check = ترقية
open-url-mode-allow = سماح
open-url-mode-confirm = تأكيد
open-url-mode-deny = رفض
quality = الجودة
quality-low = منخفضة
quality-medium = متوسط
quality-high = عالية
quality-best = الأفضل
quality-high8x8 = عالية (8x8)
scale-mode-noborder = دون حدود
scale-mode-showall = عرض الكل
warn-if-unsupported = تحذير إذا كانت غير مدعومة
warn-if-unsupported-check = تحذير
player-version = إصدار اللاعب
