about-ruffle = Sobre Ruffle
about-ruffle-version = Versión
about-ruffle-channel = Canal
about-ruffle-build-time = Hora de compilación
about-ruffle-build-features = Características de la versión
about-ruffle-commit-ref = Referencia del metido
about-ruffle-commit-time = Hora del metido
about-ruffle-visit-website = Sitio Web
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Patrocinador
