file-picker-title-open-file = Abrir un archivo soltero
file-picker-title-open-directory = Abrir una carpeta
file-picker-filter-supported = Todos archivos apoyados
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Paquete de Ruffle (*.ruf)
file-picker-filter-all = Todos los archivos
file-picker-select-root-movie-title = Seleccionar la película de raíz
file-picker-select-root-movie-message = Seleccionar la película de raíz desde el directorio abierto.
file-picker-select-root-movie-select = Seleccionar
