preferences-dialog = Menú de Preferencias
preference-locked-by-cli = Leer solamente (puesto por la terminal de mandatos)
graphics-backend = Mecanismo/motor de los gráficos
graphics-backend-default = Predeterminado
graphics-power = Preferencias de Poder
graphics-power-low = Bajo (para gráficos integrados)
graphics-power-high = Alto (para gráficos dedicados)
language = Idioma
audio-output-device = Dispositivo de reproducción de audio
audio-output-device-default = Predeterminado del sistema
enable-openh264 = Habilitar OpenH264
show-license = Mostrar licencia
openh264-license = Licencia de OpenH264
log-filename-pattern = Nombre del archivo de registro
log-filename-pattern-single-file = Archivo soltero (ruffle.log)
log-filename-pattern-with-timestamp = Con marca de la fecha y la hora (UTC)
storage-backend = Destino del archivo guardado
storage-backend-disk = Disco
storage-backend-memory = Memoria
recent-limit = Límite de recientes
recent-clear = Borrar
