network-settings = Configuración de red
player-settings = Configuración de reproducción
movie-parameters = Parámetros de película
custom-base-url = URL Base personalizada
spoof-swf-url = Falsificar URL de SWF
referer-url = URL de origen
cookie = Cookie
proxy = Proxy
upgrade-http = Actualizar HTTP a HTTPS
tcp-connections = Conexiones TCP
tcp-connections-allow = Permitir
tcp-connections-ask = Preguntar
tcp-connections-deny = Denegar
open-url-mode = Abrir los enlaces
open-url-mode-allow = Permitir
open-url-mode-confirm = Preguntar
open-url-mode-deny = Rechazar
load-behavior = Forma de cargar
load-behavior-streaming = Retransmisión
load-behavior-delayed = Retrasado
load-behavior-blocking = Bloqueando
max-execution-duration = Duración máxima de ejecución
max-execution-duration-suffix = { " " } segundos
quality = Calidad
quality-low = Bajo
quality-medium = Medio
quality-high = Alta
quality-best = Óptima
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) lineal
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (8x8) lineal
letterbox = Usar dimensiones como un buzón
letterbox-on = Activado
letterbox-fullscreen = Solo pantalla completa
letterbox-off = Desactivado
align = Alineación
align-center = Centrar
align-left = Alinear a la izquierda
align-right = Alinear a la derecha
align-top = Alinear arriba
align-bottom = Alinear abajo
align-top-left = Alinear arriba a la izquierda
align-bottom-left = Alinear abajo a la izquierda
align-top-right = Alinear arriba a la derecha
align-bottom-right = Alinear abajo a la derecha
align-force = Forzar alineación
scale-mode = Modo de escala
scale-mode-exactfit = Medida Exacta
scale-mode-noborder = Sin fronteras
scale-mode-noscale = Sin escala
scale-mode-showall = Mostrar todo
scale-mode-force = Forzar el modo de escala
player-version = Versión del reproductor
player-runtime = Infraestructura del reproductor
player-runtime-flash = Reproductor de Flash
player-runtime-air = Adobe AIR
custom-framerate = Velocidad personalizada de rendimiento
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interfaz Externa Falsa
