network-settings = Configuración de red
player-settings = Ajustes de jugador
movie-parameters = Parámetros de película
custom-base-url = URL Base personalizada
spoof-swf-url = Falsificar URL de SWF
proxy = Proxy
upgrade-http = Actualizar HTTP a HTTPS
upgrade-http-check = Actualizar
open-url-mode = Abrir modo URL
open-url-mode-allow = Permitir
open-url-mode-confirm = Confirmar
open-url-mode-deny = Rechazar
load-behavior = Forma de cargar
load-behavior-streaming = Retransmisión
load-behavior-delayed = Retrasado
load-behavior-blocking = Bloqueando
max-execution-duration = Duración máxima de ejecución
max-execution-duration-suffix = { " " } segundos
quality = Calidad
quality-low = Bajo
quality-medium = Medio
quality-high = Alta
quality-best = Óptima
quality-high8x8 = Alta (8x8)
quality-high8x8linear = Alta (8x8) lineal
quality-high16x16 = Alta (16x16)
quality-high16x16linear = Alta (8x8) lineal
scale-mode = Modo de escala
scale-mode-exactfit = Medida Exacta
scale-mode-noborder = Sin fronteras
scale-mode-noscale = Sin escala
scale-mode-showall = Mostrar todo
force-scale-mode = Forzar modo de escala
force-scale-mode-check = Forzar
warn-if-unsupported = Advertir si no está soportado
warn-if-unsupported-check = Adevertir
player-version = Versión del Jugador
custom-framerate = Velocidad personalizada de rendimiento
custom-framerate-suffix = { " " } fps
