about-ruffle = O Ruffle-u
about-ruffle-version = Verzija
about-ruffle-channel = Kanal
about-ruffle-build-time = Vrijeme izgradnje
about-ruffle-build-features = Značajke izgradnje
about-ruffle-commit-ref = Potvrdi Referencu
about-ruffle-commit-time = Vrijeme potvrde
about-ruffle-visit-website = Web stranica
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Sponzorirajte
