preferences-dialog = Postavke Ruffle-a
preference-locked-by-cli = Samo za čitanje (postavljeno pomoću CLI-ja)
graphics-backend = Grafički pozadinski sistem
graphics-backend-default = Zadano
graphics-power = Preferencija napajanja
graphics-power-low = Nisko (npr. iGPU)
graphics-power-high = Visoko (npr. GPU)
language = Jezik
audio-output-device = Izlazni audio uređaj
audio-output-device-default = Zadano sistemsko
enable-openh264 = Omogući OpenH264
show-license = Prikaži licencu
openh264-license = OpenH264 licenca
log-filename-pattern = Naziv datoteke dnevnika
log-filename-pattern-single-file = Jedna datoteka (ruffle.log)
log-filename-pattern-with-timestamp = Sa vremenskom oznakom
storage-backend = Lokacija za spremanje datoteke
storage-backend-disk = Disk
storage-backend-memory = Pamćenje
recent-limit = Nedavna ograničenja
theme = Tema
theme-system = Zadano sistemsko
gamemode-default = Zadano
# See for context https://wiki.archlinux.org/title/Input_method
ime-enabled = Način unosa
ime-enabled-experimental = (eksperimentalno)
ime-enabled-tooltip = Metod unosa vam omogućava unos znakova koji nisu dostupni na tastaturi, kao što su kineski, japanski ili korejski znakovi.
ime-enabled-default = Zadano
