context-menu-rewind = Premotati
context-menu-forward = Naprijed
context-menu-back = Natrag
context-menu-quality-low = Kvaliteta: Niska
context-menu-quality-medium = Kvaliteta: Srednja
context-menu-quality-high = Kvaliteta: Visoka
context-menu-cut = Izreži
context-menu-copy = Kopiraj
context-menu-paste = Zalijepi
context-menu-delete = Izbriši
context-menu-select-all = Odaberi sve
