context-menu-play = 再生
context-menu-rewind = 巻き戻し
context-menu-forward = 次へ
context-menu-back = 戻る
context-menu-quality-low = 品質: 低
context-menu-quality-medium = 品質: 通常
context-menu-quality-high = 品質: 高
context-menu-cut = 切り取り
context-menu-copy = コピー
context-menu-paste = 貼り付け
context-menu-delete = 削除
context-menu-select-all = すべて選択
