// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/CollatorMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{

    public final class CollatorMode
    {
        // Initializes a Collator object so that the compare method is optimized for determining whether two strings are equivalent.
        public static const MATCHING:String = "matching";

        // Initializes a Collator object so that the compare method is optimized for sorting a list of text strings to be displayed to an end user.
        public static const SORTING:String = "sorting";

    }
}
