// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/DateTimeNameStyle.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{

    public final class DateTimeNameStyle
    {
        // Specifies the full form or full name style for month names and weekday names.
        public static const FULL:String = "full";

        // Specifies the long abbreviation style for month names and weekday names.
        public static const LONG_ABBREVIATION:String = "longAbbreviation";

        // Specifies the short abbreviation style for month names and weekday names.
        public static const SHORT_ABBREVIATION:String = "shortAbbreviation";

    }
}
