// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/DateTimeStyle.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{

    public final class DateTimeStyle
    {
        // Specifies that a custom pattern string is used to specify the date or time style.
        public static const CUSTOM:String = "custom";

        // Specifies the long style of a date or time.
        public static const LONG:String = "long";

        // Specifies the medium style of a date or time.
        public static const MEDIUM:String = "medium";

        // Specifies that the date or time should not be included in the formatted string.
        public static const NONE:String = "none";

        // Specifies the short style of a date or time.
        public static const SHORT:String = "short";

    }
}
