// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/DateTimeNameContext.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{

    public final class DateTimeNameContext
    {
        // Indicates that the date element name is used within a date format.
        public static const FORMAT:String = "format";

        // Indicates that the date element name is used in a "stand alone" context, independent of other formats.
        public static const STANDALONE:String = "standalone";

    }
}
