// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/LastOperationStatus.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{

    public final class LastOperationStatus
    {
        // Indicates that given buffer is not enough to hold the result.
        public static const BUFFER_OVERFLOW_ERROR:String = "bufferOverflowError";

        // Indicates that the return error code is not known.
        public static const ERROR_CODE_UNKNOWN:String = "errorCodeUnknown";

        // Indicates that an argument passed to a method was illegal.
        public static const ILLEGAL_ARGUMENT_ERROR:String = "illegalArgumentError";

        // Indicates that an iterator went out of range or an invalid parameter was specified for month, day, or time.
        public static const INDEX_OUT_OF_BOUNDS_ERROR:String = "indexOutOfBoundsError";

        // Indicates that a given attribute value is out of the expected range.
        public static const INVALID_ATTR_VALUE:String = "invalidAttrValue";

        // Indicates that invalid Unicode value was found.
        public static const INVALID_CHAR_FOUND:String = "invalidCharFound";

        // Indicates that memory allocation has failed.
        public static const MEMORY_ALLOCATION_ERROR:String = "memoryAllocationError";

        // Indicates that the last operation succeeded without any errors.
        public static const NO_ERROR:String = "noError";

        // Indicates that an operation resulted a value that exceeds a specified numeric type.
        public static const NUMBER_OVERFLOW_ERROR:String = "numberOverflowError";

        // Indicates that the parsing of a number failed.
        public static const PARSE_ERROR:String = "parseError";

        // Indicates that the pattern for formatting a number, date, or time is invalid.
        public static const PATTERN_SYNTAX_ERROR:String = "patternSyntaxError";

        // Indicates that an underlying platform API failed for an operation.
        public static const PLATFORM_API_FAILED:String = "platformAPIFailed";

        // Indicates that a truncated Unicode character value was found.
        public static const TRUNCATED_CHAR_FOUND:String = "truncatedCharFound";

        // Indicates that an unexpected token was detected in a Locale ID string.
        public static const UNEXPECTED_TOKEN:String = "unexpectedToken";

        // Indicates that the requested operation or option is not supported.
        public static const UNSUPPORTED_ERROR:String = "unsupportedError";

        // Indicates that an operating system default value was used during the most recent operation.
        public static const USING_DEFAULT_WARNING:String = "usingDefaultWarning";

        // Indicates that a fallback value was set during the most recent operation.
        public static const USING_FALLBACK_WARNING:String = "usingFallbackWarning";

    }
}
