text1.text = "a\na";
text2.html = true;
text2.htmlText = "<font name=\"Noto Sans\">a<br>a</font>";
text3.html = false;
text3.text = "a\na";

trace("Default text formats:");
trace("  Align:");
trace("    " + text1.getNewTextFormat().align);
trace("    " + text2.getNewTextFormat().align);
trace("    " + text3.getNewTextFormat().align);
trace("    " + text4.getNewTextFormat().align);
trace("  Indent:");
trace("    " + text1.getNewTextFormat().indent);
trace("    " + text2.getNewTextFormat().indent);
trace("    " + text3.getNewTextFormat().indent);
trace("    " + text4.getNewTextFormat().indent);
trace("  Left margin:");
trace("    " + text1.getNewTextFormat().leftMargin);
trace("    " + text2.getNewTextFormat().leftMargin);
trace("    " + text3.getNewTextFormat().leftMargin);
trace("    " + text4.getNewTextFormat().leftMargin);
trace("  Right margin:");
trace("    " + text1.getNewTextFormat().rightMargin);
trace("    " + text2.getNewTextFormat().rightMargin);
trace("    " + text3.getNewTextFormat().rightMargin);
trace("    " + text4.getNewTextFormat().rightMargin);
trace("  Leading:");
trace("    " + text1.getNewTextFormat().leading);
trace("    " + text2.getNewTextFormat().leading);
trace("    " + text3.getNewTextFormat().leading);
trace("    " + text4.getNewTextFormat().leading);

trace("Actual text formats:");
trace("  Align:");
trace("    " + text1.getTextFormat(0, 1).align);
trace("    " + text2.getTextFormat(0, 1).align);
trace("    " + text3.getTextFormat(0, 1).align);
trace("    " + text4.getTextFormat(0, 1).align);
trace("  Indent:");
trace("    " + text1.getTextFormat(0, 1).indent);
trace("    " + text2.getTextFormat(0, 1).indent);
trace("    " + text3.getTextFormat(0, 1).indent);
trace("    " + text4.getTextFormat(0, 1).indent);
trace("  Left margin:");
trace("    " + text1.getTextFormat(0, 1).leftMargin);
trace("    " + text2.getTextFormat(0, 1).leftMargin);
trace("    " + text3.getTextFormat(0, 1).leftMargin);
trace("    " + text4.getTextFormat(0, 1).leftMargin);
trace("  Right margin:");
trace("    " + text1.getTextFormat(0, 1).rightMargin);
trace("    " + text2.getTextFormat(0, 1).rightMargin);
trace("    " + text3.getTextFormat(0, 1).rightMargin);
trace("    " + text4.getTextFormat(0, 1).rightMargin);
trace("  Leading:");
trace("    " + text1.getTextFormat(0, 1).leading);
trace("    " + text2.getTextFormat(0, 1).leading);
trace("    " + text3.getTextFormat(0, 1).leading);
trace("    " + text4.getTextFormat(0, 1).leading);
