preferences-dialog = Уподобання Ruffle
preference-locked-by-cli = Лише читання (Встановлено CLI)
graphics-backend = Графічний сервер
graphics-backend-default = За замовчуванням
graphics-power = Переважна потужність
graphics-power-low = Низька (наприклад, iGPU)
graphics-power-high = Висока (наприклад, GPU)
language = Мова
audio-output-device = Пристрій виведення аудіо
audio-output-device-default = Системне за замовчуванням
enable-openh264 = Увімкнути OpenH264
show-license = Показати ліцензію
openh264-license = Ліцензія OpenH264
log-filename-pattern = Назва файлу журналу
log-filename-pattern-single-file = Один файл (ruffle.log)
log-filename-pattern-with-timestamp = З міткою часу
storage-backend = Зберегти розташування файлу
storage-backend-disk = Диск
storage-backend-memory = Пам'ять
recent-limit = Останні ліміти
recent-clear = Очистити
