preferences-dialog = Ruffle voorkeuren
preference-locked-by-cli = Alleen-lezen (via consoleinterface ingesteld)
graphics-backend = Grafisch systeem
graphics-backend-default = Standaard
graphics-power = Stroomverbruiksvoorkeur
graphics-power-low = Laag (e.g. iGPU)
graphics-power-high = Hoog (e.g. discrete GPU)
language = Taal
audio-output-device = Audio uitvoerapparaat
audio-output-device-default = Systeemstandaard
enable-openh264 = Schakel OpenH264 in
show-license = Laat licentie zien
openh264-license = OpenH264 licentie
log-filename-pattern = Logbestandsnaam
log-filename-pattern-single-file = Enkel bestand (ruffle.log)
log-filename-pattern-with-timestamp = Met tijdsaanduiding
storage-backend = Opslaglocatie voor bestanden
storage-backend-disk = Schijf
storage-backend-memory = Geheugen
recent-limit = Recent limiet
recent-clear = Legen
theme = Thema
theme-system = Systeemstandaard
theme-light = Licht
theme-dark = Donker
# See for context https://github.com/FeralInteractive/gamemode
gamemode = GameMode
gamemode-default = Standaard
# See for context https://wiki.archlinux.org/title/Input_method
ime-enabled = Invoermethode
ime-enabled-experimental = (experimenteel)
ime-enabled-tooltip = Een invoermethode maakt het mogelijk om tekens in te voeren die niet op het toetsenbord beschikbaar zijn, bijvoorbeeld Chinese, Japanse of Koreaanse tekens.
ime-enabled-default = Standaard
