preferences-dialog = Ruffle voorkeuren
preference-locked-by-cli = Alleen-lezen (via consoleinterface ingesteld)
graphics-backend = Grafisch systeem
graphics-backend-default = Standaard
graphics-power = Stroomverbruiksvoorkeur
graphics-power-low = Laag (e.g. iGPU)
graphics-power-high = Hoog (e.g. discrete GPU)
language = Taal
audio-output-device = Audio uitvoerapparaat
audio-output-device-default = Systeemstandaard
