network-settings = Netwerkinstellingen
player-settings = Spelerinstellingen
movie-parameters = Filminstellingen
custom-base-url = Aangepaste basis-URL
spoof-swf-url = SWF URL nadoen
referer-url = Doorverwijs-URL
cookie = Cookies
proxy = Proxy
upgrade-http = Upgrade HTTP naar HTTPS
tcp-connections = TCP verbindingen
tcp-connections-allow = Toestaan
tcp-connections-ask = Vragen
tcp-connections-deny = Weigeren
open-url-mode = Links openen
open-url-mode-allow = Toestaan
open-url-mode-confirm = Vragen
open-url-mode-deny = Weigeren
load-behavior = Laadgedrag
load-behavior-streaming = Streamen
load-behavior-delayed = Vertragen
load-behavior-blocking = Blokkeren
max-execution-duration = Maximale looptijd
max-execution-duration-suffix = { " " } sec
quality = Kwaliteit
quality-low = Laag
quality-medium = Midden
quality-high = Hoog
quality-best = Beste
quality-high8x8 = Hoog (8x8)
quality-high8x8linear = Hoog (8x8) lineair
quality-high16x16 = Hoog (16x16)
quality-high16x16linear = Hoog (16x16) lineair
letterbox = Zwarte balken
letterbox-on = Aan
letterbox-fullscreen = Alleen tijdens volledig beeld
letterbox-off = Uit
align = Schermuitlijning
align-center = Midden
align-left = Links
align-right = Rechts
align-top = Boven
align-bottom = Onder
align-top-left = Linksboven
align-bottom-left = Linksonder
align-top-right = Rechtsboven
align-bottom-right = Rechtsonder
align-force = Forceren
scale-mode = Schaalmodus
scale-mode-exactfit = Precies passend
scale-mode-noborder = Geen randen
scale-mode-noscale = Niet schalen
scale-mode-showall = Toon alles
scale-mode-force = Forceren
player-version = Spelerversie
player-runtime = Soort speler
player-runtime-flash = Flash speler
player-runtime-air = Adobe Air Speler
custom-framerate = Aangepaste afspeelsnelheid
custom-framerate-suffix = { " " } fps
dummy-external-interface = Nep externe interface
