network-settings = Netwerkinstellingen
player-settings = Spelerinstellingen
movie-parameters = Filminstellingen
custom-base-url = Aangepaste basis-URL
spoof-swf-url = SWF URL nadoen
proxy = Proxy
upgrade-http = Upgrade HTTP naar HTTPS
upgrade-http-check = Upgrade
open-url-mode = Open URL modus
open-url-mode-allow = Toestaan
open-url-mode-confirm = Bevestigen
open-url-mode-deny = Weigeren
load-behavior = Laadgedrag
load-behavior-streaming = Streamen
load-behavior-delayed = Vertragen
load-behavior-blocking = Blokkeren
max-execution-duration = Maximale looptijd
max-execution-duration-suffix = { " " } sec
quality = Kwaliteit
quality-low = Laag
quality-medium = Midden
quality-high = Hoog
quality-best = Beste
quality-high8x8 = Hoog (8x8)
quality-high8x8linear = Hoog (8x8) lineair
quality-high16x16 = Hoog (16x16)
quality-high16x16linear = Hoog (16x16) lineair
scale-mode = Schaalmodus
scale-mode-exactfit = Precies passend
scale-mode-noborder = Geen randen
scale-mode-noscale = Niet schalen
scale-mode-showall = Toon alles
warn-if-unsupported = Waarschuw indien niet ondersteund
warn-if-unsupported-check = Waarschuwen
player-version = Spelerversie
custom-framerate = Aangepaste afspeelsnelheid
custom-framerate-suffix = { " " } fps
