// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/security/CertificateStatus.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.security
{

    public final class CertificateStatus
    {
        // The certificate is outside its valid period.
        public static const EXPIRED:String = "expired";

        // An invalid certificate.
        public static const INVALID:String = "invalid";

        // A root or intermediate certificate in this certificate's chain is invalid.
        public static const INVALID_CHAIN:String = "invalidChain";

        // The certificate is not yet valid.
        public static const NOT_YET_VALID:String = "notYetValid";

        // The certificate common name does not match the expected host name.
        public static const PRINCIPAL_MISMATCH:String = "principalMismatch";

        // The certificate has been revoked.
        public static const REVOKED:String = "revoked";

        // A valid, trusted certificate.
        public static const TRUSTED:String = "trusted";

        // The validity of the certificate is not known.
        public static const UNKNOWN:String = "unknown";

        // The certificate does not chain to a trusted root certificate.
        public static const UNTRUSTED_SIGNERS:String = "untrustedSigners";

    }
}
