about-ruffle = Despre Ruffle
about-ruffle-version = Versiune
about-ruffle-channel = Canal
about-ruffle-build-time = Timpul clădirii
about-ruffle-build-features = Caracteristicile clădirii
about-ruffle-commit-ref = Referința commit-ului
about-ruffle-commit-time = Timpul commit-ului
about-ruffle-visit-website = Site web
about-ruffle-visit-github = GitHub
about-ruffle-visit-discord = Discord
about-ruffle-visit-sponsor = Sponsorizare
