network-settings = Setări de rețea
proxy = Proxy
tcp-connections = Conexiuni TCP
tcp-connections-allow = Permite
tcp-connections-ask = Întreabă
letterbox-fullscreen = Numai ecran complet
align-force = Forțează
scale-mode-force = Forțează
player-version = Versiunea playerului
custom-framerate = Frecvență de cadre personalizată
custom-framerate-suffix = { " " } fps
