proxy = Proxy
tcp-connections = Conexiuni TCP
tcp-connections-allow = Permite
tcp-connections-ask = Întreabă
max-execution-duration-suffix = { " " } sec
quality = Calitate
quality-low = Scăzut
letterbox-on = Pe
letterbox-fullscreen = Numai ecran complet
letterbox-off = Oprit
align = Alinierea etapei
align-top = Top
align-bottom = Fund
align-top-left = Stânga sus
align-bottom-left = Stânga jos
align-top-right = Sus în dreapta
align-bottom-right = Dreapta-jos
align-force = Forțează
scale-mode = Modul Scalare
scale-mode-exactfit = Potrivire exactă
scale-mode-noborder = Fara limita
scale-mode-noscale = No Scale
scale-mode-showall = Arata tot
scale-mode-force = Forțează
player-version = Versiunea playerului
custom-framerate = Frecvență de cadre personalizată
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interfață externă simulată
dummy-external-interface-check = Activează
