// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/IMEConversionMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{

    public final class IMEConversionMode
    {
        // The string "ALPHANUMERIC_FULL", for use with the IME.conversionMode property.
        public static const ALPHANUMERIC_FULL:String = "ALPHANUMERIC_FULL";

        // The string "ALPHANUMERIC_HALF", for use with the IME.conversionMode property.
        public static const ALPHANUMERIC_HALF:String = "ALPHANUMERIC_HALF";

        // The string "CHINESE", for use with the IME.conversionMode property.
        public static const CHINESE:String = "CHINESE";

        // The string "JAPANESE_HIRAGANA", for use with the IME.conversionMode property.
        public static const JAPANESE_HIRAGANA:String = "JAPANESE_HIRAGANA";

        // The string "JAPANESE_KATAKANA_FULL", for use with the IME.conversionMode property.
        public static const JAPANESE_KATAKANA_FULL:String = "JAPANESE_KATAKANA_FULL";

        // The string "JAPANESE_KATAKANA_HALF", for use with the IME.conversionMode property.
        public static const JAPANESE_KATAKANA_HALF:String = "JAPANESE_KATAKANA_HALF";

        // The string "KOREAN", for use with the IME.conversionMode property.
        public static const KOREAN:String = "KOREAN";

        // The string "UNKNOWN", which can be returned by a call to the IME.conversionMode property.
        public static const UNKNOWN:String = "UNKNOWN";

    }
}
