// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/MessageChannelState.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{

    [API("682")]
    public final class MessageChannelState
    {
        // This state indicates that the message channel has been closed and doesn't have any more messages to deliver.
        public static const CLOSED:String = "closed";

        // This state indicates that the message channel has been instructed to close and is in the process of delivering the remaining messages on the channel.
        public static const CLOSING:String = "closing";

        // This state indicates that the message channel is open and available for use.
        public static const OPEN:String = "open";

    }
}
