// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/SecurityPanel.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{

    public final class SecurityPanel
    {
        // When passed to Security.showSettings(), displays the Camera panel in Flash Player Settings.
        public static const CAMERA:String = "camera";

        // When passed to Security.showSettings(), displays the panel that was open the last time the user closed the Flash Player Settings.
        public static const DEFAULT:String = "default";

        // When passed to Security.showSettings(), displays the Display panel in Flash Player Settings.
        public static const DISPLAY:String = "display";

        // When passed to Security.showSettings(), displays the Local Storage Settings panel in Flash Player Settings.
        public static const LOCAL_STORAGE:String = "localStorage";

        // When passed to Security.showSettings(), displays the Microphone panel in Flash Player Settings.
        public static const MICROPHONE:String = "microphone";

        // When passed to Security.showSettings(), displays the Privacy Settings panel in Flash Player Settings.
        public static const PRIVACY:String = "privacy";

        // When passed to Security.showSettings(), displays the Settings Manager (in a separate browser window).
        public static const SETTINGS_MANAGER:String = "settingsManager";

    }
}
