// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/SystemUpdaterType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{

    public class SystemUpdaterType
    {
        // Updates the DRM module.
        public static const DRM:String = "drm";

        // Updates the player runtime itself.
        public static const SYSTEM:String = "system";

    }
}
