// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/TouchscreenType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.system
{

    public final class TouchscreenType
    {
        // A touchscreen designed to respond to finger touches.
        public static const FINGER:String = "finger";

        // The computer or device does not have a supported touchscreen.
        public static const NONE:String = "none";

        // A touchscreen designed for use with a stylus.
        public static const STYLUS:String = "stylus";

    }
}
