preferences-dialog = Nastavení Ruffle
preference-locked-by-cli = Pouze pro čtení (nastavené CLI)
graphics-backend = Grafický backend
graphics-backend-default = Výchozí
graphics-power = Nastavení výkonu
graphics-power-low = Nízký (např. iGPU)
graphics-power-high = Vysoký (např. GPU)
language = Jazyk
audio-output-device = Zařízení pro výstup zvuku
audio-output-device-default = Výchozí systému
enable-openh264 = Zapnout OpenH264
show-license = Ukázat licenci
openh264-license = OpenH264 Licence
log-filename-pattern = Název souboru logu
log-filename-pattern-single-file = Jeden soubor (ruffle.log)
log-filename-pattern-with-timestamp = S časovým razítkem
storage-backend = Umístění souboru s uloženými pozicemi
storage-backend-disk = Disk
storage-backend-memory = Paměť
recent-limit = Limit pro nedávné položky
recent-clear = Vymazat
theme = Téma
theme-system = Výchozí systému
theme-light = Světlá
theme-dark = Tmavá
