network-settings = Nastavení sítě
player-settings = Nastavení přehrávače
movie-parameters = Parametry filmu
custom-base-url = Vlastní základní URL
spoof-swf-url = Falešná SWF URL
referer-url = Odkazující URL odkaz
cookie = Cookie
proxy = Proxy
upgrade-http = Změnit HTTP na HTTPS
tcp-connections = TCP připojení
tcp-connections-allow = Povolit
tcp-connections-ask = Zeptat se
tcp-connections-deny = Zakázat
open-url-mode = Otevřít odkazy
open-url-mode-allow = Povolit
open-url-mode-confirm = Zeptat se
open-url-mode-deny = Zamítnout
load-behavior = Vybrat fungování
load-behavior-streaming = Streamování
load-behavior-delayed = Zpoždění
load-behavior-blocking = Blokování
max-execution-duration = Maximální doba provádění
max-execution-duration-suffix = { " " } vteřin
quality = Kvalita
quality-low = Nízká
quality-medium = Střední
quality-high = Vysoká
quality-best = Nejlepší
quality-high8x8 = Vysoká (8x8)
quality-high8x8linear = Vysoká (8x8) lineární
quality-high16x16 = Vysoká (16x16)
quality-high16x16linear = Vysoká (16x16) lineární
letterbox = Letterbox
letterbox-on = Zapnuto
letterbox-fullscreen = Pouze celá obrazovka
letterbox-off = Vypnuto
align = Zarovnání scény
align-center = Nastřed
align-left = Vlevo
align-right = Vpravo
align-top = Horní
align-bottom = Spodní
align-top-left = Horní vlevo
align-bottom-left = Spodní vlevo
align-top-right = Horní vpravo
align-bottom-right = Spodní vpravo
align-force = Vynutit
scale-mode = Režim natažení
scale-mode-exactfit = Přesné umístění
scale-mode-noborder = Bez okrajů
scale-mode-noscale = Bez natažení
scale-mode-showall = Zobrazit vše
scale-mode-force = Vynutit
player-version = Verze přehrávače
player-runtime = Doba běhu přehrávače
player-runtime-flash = Flash přehrávač
player-runtime-air = Adobe AIR
custom-framerate = Vlastní Framerate
custom-framerate-suffix = { " " } fps
dummy-external-interface = Falešné externí rozhraní
