network-settings = Podešavanja mreže
player-settings = Podešavanja plejera
movie-parameters = Parametri filma
custom-base-url = Prilagođeni osnovni URL
spoof-swf-url = Lažni SWF URL
cookie = Kolačić
proxy = Proksi
upgrade-http = Nadogradite HTTP na HTTPS
tcp-connections = TCP veze
tcp-connections-allow = Dozvoli
tcp-connections-ask = Pitajte
tcp-connections-deny = Odbaci
open-url-mode = Otvori linkove
open-url-mode-allow = Dozvoli
open-url-mode-confirm = Pitajte
open-url-mode-deny = Odbaci
load-behavior = Ponašanje opterećenja
load-behavior-delayed = Odloženo
max-execution-duration = Maksimalno trajanje izvršenja
max-execution-duration-suffix = { " " } sekundi
quality = Kvalitet
quality-low = Nizak
quality-medium = Srednji
quality-high = Visok
quality-best = Najbolji
quality-high8x8 = Visok (8x8)
quality-high8x8linear = Visok (8x8) linearan
quality-high16x16 = Visok (16x16)
quality-high16x16linear = Visok (16x16) linearan
