preferences-dialog = Préférences de Ruffle
preference-locked-by-cli = Lecture seule (défini par CLI)
graphics-backend = Sortie graphique
graphics-backend-vulkan = Vulkan
graphics-backend-gl = OpenGL
graphics-backend-dx12 = DirectX 12
graphics-backend-metal = Metal
graphics-backend-default = Standard
graphics-power = Préférence de performance
graphics-power-low = Faible (par exemple, iGPU)
graphics-power-high = Élevée (par exemple, GPU)
language = Langue
audio-output-device = Périphérique de sortie audio
audio-output-device-default = Valeur système par défaut
