preferences-dialog = Préférences de Ruffle
preference-locked-by-cli = Lecture seule (défini par CLI)
graphics-backend = Sortie graphique
graphics-backend-default = Standard
graphics-power = Préférence de performance
graphics-power-low = Faible (par exemple, iGPU)
graphics-power-high = Élevée (par exemple, GPU)
language = Langue
audio-output-device = Périphérique de sortie audio
audio-output-device-default = Valeur système par défaut
