preferences-dialog = Préférences de Ruffle
preference-locked-by-cli = Lecture seule (défini par CLI)
graphics-backend = Sortie graphique
graphics-backend-default = Standard
graphics-power = Préférence de performance
graphics-power-low = Faible (par exemple, iGPU)
graphics-power-high = Élevée (par exemple, GPU)
language = Langue
audio-output-device = Périphérique de sortie audio
audio-output-device-default = Valeur système par défaut
enable-openh264 = Activer OpenH264
show-license = Afficher la licence
openh264-license = Licence de OpenH264
log-filename-pattern = Nom du fichier journal
log-filename-pattern-single-file = Fichier unique (ruffle.log)
log-filename-pattern-with-timestamp = Avec horodatage
storage-backend = Emplacement des fichiers de sauvegarde
storage-backend-disk = Disque
storage-backend-memory = Mémoire
recent-limit = Limite de fichiers récents
recent-clear = Effacer
theme = Thème
theme-system = Valeur système par défaut
theme-light = Mode clair
theme-dark = Mode sombre
