network-settings = Paramètres réseau
player-settings = Paramètres du lecteur
movie-parameters = Paramètres de l'animation
custom-base-url = URL de base personnalisée
spoof-swf-url = URL détournée du SWF
proxy = Proxy
upgrade-http = Convertir HTTP en HTTPS
upgrade-http-check = Convertir les requêtes
open-url-mode-allow = Autoriser
open-url-mode-deny = Bloquer
load-behavior = Mode de chargement
load-behavior-streaming = Streaming
load-behavior-delayed = Retardé
load-behavior-blocking = Bloquant
max-execution-duration = Durée maximale d'exécution
max-execution-duration-suffix = { " " } secondes
quality = Qualité
quality-low = Inférieure
quality-medium = Moyenne
quality-high = Supérieure
quality-best = Meilleure
quality-high8x8 = Supérieure (8x8)
quality-high8x8linear = Supérieure (8x8) Linéaire
quality-high16x16 = Supérieure (16x16)
quality-high16x16linear = Supérieure (16x16) Linéaire
align = Alignement de la scène
align-center = Au centre
align-left = À gauche
align-right = À droite
align-top = En haut
align-bottom = En bas
align-top-left = En haut à gauche
align-bottom-left = En bas à gauche
align-top-right = En haut à droite
align-bottom-right = En bas à droite
align-force = Forcer
scale-mode = Mode de mise à l'échelle
scale-mode-exactfit = Ajustement exact
scale-mode-noborder = Sans bordure
scale-mode-noscale = Sans mise à l'échelle
scale-mode-showall = Tout afficher
scale-mode-force = Forcer
player-version = Version du lecteur
custom-framerate = Fréquence d'images personnalisée
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interface externe factice
dummy-external-interface-check = Activer
