network-settings = Paramètres réseau
player-settings = Paramètres du lecteur
movie-parameters = Paramètres de l'animation
custom-base-url = URL de base personnalisée
spoof-swf-url = URL détournée du SWF
proxy = Proxy
upgrade-http = Convertir HTTP en HTTPS
upgrade-http-check = Convertir les requêtes
open-url-mode = Mode d'ouverture des URLs
open-url-mode-allow = Autoriser
open-url-mode-confirm = Demander
open-url-mode-deny = Bloquer
load-behavior = Mode de chargement
load-behavior-streaming = Streaming
load-behavior-delayed = Retardé
load-behavior-blocking = Bloquant
max-execution-duration = Durée maximale d'exécution
max-execution-duration-suffix = { " " } secondes
quality = Qualité
quality-low = Inférieure
quality-medium = Moyenne
quality-high = Supérieure
quality-best = Meilleure
quality-high8x8 = Supérieure (8x8)
quality-high8x8linear = Supérieure (8x8) Linéaire
quality-high16x16 = Supérieure (16x16)
quality-high16x16linear = Supérieure (16x16) Linéaire
scale-mode = Mode de mise à l'échelle
scale-mode-exactfit = Ajustement exact
scale-mode-noborder = Sans bordure
scale-mode-noscale = Sans mise à l'échelle
scale-mode-showall = Tout afficher
force-scale-mode = Forcer le mode de mise à l'échelle
force-scale-mode-check = Forcer
warn-if-unsupported = Avertir si non pris en charge
warn-if-unsupported-check = Avertir
player-version = Version du lecteur
custom-framerate = Fréquence d'images personnalisée
custom-framerate-suffix = { " " } fps
