network-settings = Paramètres réseau
player-settings = Paramètres du lecteur
movie-parameters = Paramètres de l'animation
custom-base-url = URL de base personnalisée
spoof-swf-url = URL détournée du SWF
referer-url = URL référente
cookie = Cookie
proxy = Proxy
upgrade-http = Convertir HTTP en HTTPS
tcp-connections = Connexions TCP
tcp-connections-allow = Autoriser
tcp-connections-ask = Demander
tcp-connections-deny = Bloquer
open-url-mode = Ouverture de liens
open-url-mode-allow = Autoriser
open-url-mode-confirm = Demander
open-url-mode-deny = Bloquer
load-behavior = Mode de chargement
load-behavior-streaming = En continu
load-behavior-delayed = Différé
load-behavior-blocking = Bloquant
max-execution-duration = Durée maximale d'exécution
max-execution-duration-suffix = { " " } secondes
quality = Qualité
quality-low = Inférieure
quality-medium = Moyenne
quality-high = Supérieure
quality-best = Meilleure
quality-high8x8 = Supérieure (8x8)
quality-high8x8linear = Supérieure (8x8) Linéaire
quality-high16x16 = Supérieure (16x16)
quality-high16x16linear = Supérieure (16x16) Linéaire
letterbox = Mode d'affichage letterbox
letterbox-on = Activé
letterbox-fullscreen = Plein écran seulement
letterbox-off = Désactivé
align = Alignement de la scène
align-center = Au centre
align-left = À gauche
align-right = À droite
align-top = En haut
align-bottom = En bas
align-top-left = En haut à gauche
align-bottom-left = En bas à gauche
align-top-right = En haut à droite
align-bottom-right = En bas à droite
align-force = Forcer
scale-mode = Mode de mise à l'échelle
scale-mode-force = Forcer
player-version = Version du lecteur
player-runtime = Type de lecteur
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Fréquence d'images personnalisée
custom-framerate-suffix = { " " } fps
dummy-external-interface = Interface externe factice
