network-settings = Челтәр көйләүләре
player-settings = Плеер көйләүләре
movie-parameters = Клипны параметрлары
custom-base-url = Үзенчәлекле төп URL
spoof-swf-url = SWF өчен ялган URL
referer-url = Реферер URL
cookie = Cookie
proxy = Прокси
upgrade-http = HTTP’ны HTTPS’ка яңарту
tcp-connections = TCP тоташулары
tcp-connections-allow = Рөхсəт итәргә
tcp-connections-ask = Сора
tcp-connections-deny = Рөхсәт бирмәү
open-url-mode = Сылтамалар ачу
open-url-mode-allow = Рөхсəт итəргə
open-url-mode-confirm = Сора
open-url-mode-deny = Рөхсәт бирмәү
load-behavior = Йөкләгәндә тотышы
load-behavior-streaming = Агымдагы
load-behavior-delayed = Тоткарларган
load-behavior-blocking = Блоклау
max-execution-duration = Максималь башкару вакыты
max-execution-duration-suffix = { " " } секунд
letterbox-on = Янык
letterbox-fullscreen = Фәкать тулы экран
letterbox-off = Сүндерелгән
align = Сәхнәне тигезләү
align-center = Үзәк
align-left = Сул
align-right = Уң
align-top = Өст
align-bottom = Аста
align-force = Көчләп
scale-mode = Масштаблау режимы
scale-mode-noscale = Масштабсыз (100%)
scale-mode-force = Көчләп
player-version = Плеер версиясе
player-runtime = Плеер эш мохите
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Үз кадр тизлеге
custom-framerate-suffix = { " " } fps
dummy-external-interface = Фиктив тышкы интерфейс
