network-settings = Челтәр көйләүләре
player-settings = Плеер көйләүләре
movie-parameters = Клипны параметрлары
cookie = Cookie
proxy = Прокси
upgrade-http = HTTP’ны HTTPS’ка яңарту
tcp-connections = TCP тоташулары
tcp-connections-allow = Рөхсəт итәргә
tcp-connections-ask = Сора
tcp-connections-deny = Рөхсәт бирмәү
open-url-mode-allow = Рөхсəт итəргə
open-url-mode-confirm = Сора
open-url-mode-deny = Рөхсәт бирмәү
max-execution-duration-suffix = { " " } секунд
letterbox-fullscreen = Фәкать тулы экран
letterbox-off = Сүндерелгән
align-center = Үзәк
align-left = Сул
align-right = Уң
align-top = Өст
align-bottom = Аста
align-force = Көчләп
scale-mode = Масштаблау режимы
scale-mode-noscale = Масштабсыз (100%)
scale-mode-force = Көчләп
player-runtime-flash = Flash Player
player-runtime-air = Adobe AIR
custom-framerate = Үз кадр тизлеге
custom-framerate-suffix = { " " } fps
