// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/AudioDecoder.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("674")]
    public final class AudioDecoder
    {
        // Dolby Digital Audio, which is also known as AC-3.
        public static const DOLBY_DIGITAL:String = "DolbyDigital";

        // Dolby Digital Plus Audio, which is also known as Enhanced AC-3 and Enhanced Dolby Digital.
        public static const DOLBY_DIGITAL_PLUS:String = "DolbyDigitalPlus";

        // DTS Audio, which is also known as DTS Coherent Acoustics, DTS Digital Surround, and DTS core.
        public static const DTS:String = "DTS";

        // DTS Express Audio, which is also known as DTS Low Bit Rate (LBR).
        public static const DTS_EXPRESS:String = "DTSExpress";

        // DTS-HD High Resolution Audio, which is also known as DTS-HD HR.
        public static const DTS_HD_HIGH_RESOLUTION_AUDIO:String = "DTSHDHighResolutionAudio";

        // DTS-HD Master Audio, which is also known as DTS-HD MA.
        public static const DTS_HD_MASTER_AUDIO:String = "DTSHDMasterAudio";

    }
}
