// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/AudioOutputChangeReason.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    // TODO: [API("724")]
    public final class AudioOutputChangeReason
    {
        // Audio Output is changed because system device has been added or removed.
        public static const DEVICE_CHANGE:String = "deviceChange";

        // Audio Output is changed by user selecting a different device.
        public static const USER_SELECTION:String = "userSelection";

    }
}
