// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/H264Profile.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("674")]
    public final class H264Profile
    {
        // Constant for H.264/AVC baseline profile.
        public static const BASELINE:String = "baseline";

        // Constant for H.264/AVC main profile.
        public static const MAIN:String = "main";

    }
}
