// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/H264Level.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("674")]
    public final class H264Level
    {
        // Constant for H.264 level 1.
        public static const LEVEL_1:String = "1";

        // Constant for H.264 level 1.1.
        public static const LEVEL_1_1:String = "1.1";

        // Constant for H.264 level 1.2.
        public static const LEVEL_1_2:String = "1.2";

        // Constant for H.264 level 1.3.
        public static const LEVEL_1_3:String = "1.3";

        // Constant for H.264 level 1b.
        public static const LEVEL_1B:String = "1b";

        // Constant for H.264 level 2.
        public static const LEVEL_2:String = "2";

        // Constant for H.264 level 2.1.
        public static const LEVEL_2_1:String = "2.1";

        // Constant for H.264 level 2.2.
        public static const LEVEL_2_2:String = "2.2";

        // Constant for H.264 level 3.
        public static const LEVEL_3:String = "3";

        // Constant for H.264 level 3.1.
        public static const LEVEL_3_1:String = "3.1";

        // Constant for H.264 level 3.2.
        public static const LEVEL_3_2:String = "3.2";

        // Constant for H.264 level 4.
        public static const LEVEL_4:String = "4";

        // Constant for H.264 level 4.1.
        public static const LEVEL_4_1:String = "4.1";

        // Constant for H.264 level 4.2.
        public static const LEVEL_4_2:String = "4.2";

        // Constant for H.264 level 5.
        public static const LEVEL_5:String = "5";

        // Constant for H.264 level 5.1.
        public static const LEVEL_5_1:String = "5.1";

    }
}
