// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/MicrophoneEnhancedMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("672")]
    public final class MicrophoneEnhancedMode
    {
        // Use this mode to allow both parties to talk at the same time.
        public static const FULL_DUPLEX:String = "fullDuplex";

        // Use this mode for older and lower-quality speakers and microphones.
        public static const HALF_DUPLEX:String = "halfDuplex";

        // Use this mode when both parties are using headsets.
        public static const HEADSET:String = "headset";

        // All enhanced microphone functionality is off.
        public static const OFF:String = "off";

        // Use this mode when the speaker is muted.
        public static const SPEAKER_MUTE:String = "speakerMute";

    }
}
