// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/SoundCodec.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    public final class SoundCodec
    {
        // Specifies that the Nellymoser codec be used for compressing audio.
        public static const NELLYMOSER:String = "NellyMoser";

        // Specifies that the G711 A-law codec be used for compressing audio.
        public static const PCMA:String = "pcma";

        // Specifies that the G711 u-law codec be used for compressing audio.
        public static const PCMU:String = "pcmu";

        // Specifies that the Speex codec be used for compressing audio.
        public static const SPEEX:String = "Speex";

    }
}
