// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/StageVideoAvailability.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("670")]
    public final class StageVideoAvailability
    {
        // Stage video is currently available.
        public static const AVAILABLE:String = "available";

        // Stage video is not currently available.
        public static const UNAVAILABLE:String = "unavailable";

    }
}
