// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/VideoStatus.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("670")]
    public final class VideoStatus
    {
        // Indicates hardware-accelerated (GPU) video decoding.
        public static const ACCELERATED:String = "accelerated";

        // Indicates software video decoding.
        public static const SOFTWARE:String = "software";

        // Video decoding is not supported.
        public static const UNAVAILABLE:String = "unavailable";

    }
}
