// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/VideoCodec.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.media
{

    [API("674")]
    public final class VideoCodec
    {
        // Constant value indicating that H.264/AVC codec is used for compressing video.
        public static const H264AVC:String = "H264Avc";

        // Constant value indicating that Sorenson Spark codec is used for compressing video.
        public static const SORENSON:String = "Sorenson";

        // Constant value indicating that On2Vp6 codec is used for compressing video.
        public static const VP6:String = "VP6";

    }
}
