// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/BreakOpportunity.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    
    
    public final class BreakOpportunity
    {
        // Treats all characters in the ContentElement object as line break opportunities, meaning that a line break will occur after each character.
        public static const ALL:String = "all";
        
        // Treats any character in the ContentElement object as a line break opportunity.
        public static const ANY:String = "any";
        
        // Bases line break opportunities on Unicode character properties.
        public static const AUTO:String = "auto";
        
        // Treats no characters in the ContentElement object as line break opportunities.
        public static const NONE:String = "none";
        
        
    }
}
