// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/CFFHinting.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class CFFHinting
    {
        // Fits strong horizontal stems to the pixel grid for improved readability.
        public static const HORIZONTAL_STEM:String = "horizontalStem";

        // No hinting is applied.
        public static const NONE:String = "none";
    }
}
