// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/DigitWidth.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class DigitWidth
    {
        // Used to specify default digit width.
        public static const DEFAULT:String = "default";

        // Used to specify proportional digit width.
        public static const PROPORTIONAL:String = "proportional";

        // Used to specify tabular digit width.
        public static const TABULAR:String = "tabular";
    }
}
