// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/DigitCase.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    
    
    public final class DigitCase
    {
        // Used to specify default digit case.
        public static const DEFAULT:String = "default";
        
        // Used to specify lining digit case.
        public static const LINING:String = "lining";
        
        // Used to specify old style digit case.
        public static const OLD_STYLE:String = "oldStyle";
        
        
    }
}
