// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/FontLookup.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class FontLookup
    {
        // Used to indicate device font lookup.
        public static const DEVICE:String = "device";

        // Used to indicate embedded CFF (Compact Font Format) font lookup.
        public static const EMBEDDED_CFF:String = "embeddedCFF";
    }
}
