// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/FontPosture.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class FontPosture
    {
        // Used to indicate italic font posture.
        public static const ITALIC:String = "italic";

        // Used to indicate normal font posture.
        public static const NORMAL:String = "normal";
    }
}
