// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/JustificationStyle.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class JustificationStyle
    {
        // Bases justification on either expanding or compressing the line, whichever gives a result closest to the desired width.
        public static const PRIORITIZE_LEAST_ADJUSTMENT:String = "prioritizeLeastAdjustment";

        // Bases justification on compressing kinsoku at the end of the line, or expanding it if no kinsoku occurs or if that space is insufficient.
        public static const PUSH_IN_KINSOKU:String = "pushInKinsoku";

        // Bases justification on expanding the line.
        public static const PUSH_OUT_ONLY:String = "pushOutOnly";
    }
}
