// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/Kerning.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class Kerning
    {
        // Used to indicate that kerning is enabled except where inappropriate in Asian typography.
        public static const AUTO:String = "auto";

        // Used to indicate kerning is disabled.
        public static const OFF:String = "off";

        // Used to indicate kerning is enabled.
        public static const ON:String = "on";
    }
}
