// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/LigatureLevel.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    
    
    public final class LigatureLevel
    {
        // Used to specify common ligatures.
        public static const COMMON:String = "common";
        
        // Used to specify exotic ligatures.
        public static const EXOTIC:String = "exotic";
        
        // Used to specify minimum ligatures.
        public static const MINIMUM:String = "minimum";
        
        // Used to specify no ligatures.
        public static const NONE:String = "none";
        
        // Used to specify uncommon ligatures.
        public static const UNCOMMON:String = "uncommon";
        
        
    }
}
