// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/LineJustification.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    
    
    public final class LineJustification
    {
        // Justify all but the last line.
        public static const ALL_BUT_LAST:String = "allButLast";
        
        // Justify all but the last line and lines ending in mandatory breaks.
        [API("674")]
        public static const ALL_BUT_MANDATORY_BREAK:String = "allButMandatoryBreak";
        
        // Justify all lines.
        public static const ALL_INCLUDING_LAST:String = "allIncludingLast";
        
        // Do not justify lines.
        public static const UNJUSTIFIED:String = "unjustified";
        
        
    }
}
