// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TabAlignment.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TabAlignment
    {
        // Positions the center of the tabbed text at the tab stop.
        public static const CENTER:String = "center";

        // Positions the alignment token of the tabbed text at the tab stop.
        public static const DECIMAL:String = "decimal";

        // Positions the end of the tabbed text at the tab stop.
        public static const END:String = "end";

        // Positions the start of the tabbed text at the tab stop.
        public static const START:String = "start";
    }
}
