// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextRotation.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TextRotation
    {
        // Specifies a 90 degree counter clockwise rotation for full width and wide glyphs only, as determined by the Unicode properties of the glyph.
        public static const AUTO:String = "auto";

        // Specifies no rotation.
        public static const ROTATE_0:String = "rotate0";

        // Specifies a 180 degree rotation.
        public static const ROTATE_180:String = "rotate180";

        // Specifies a 270 degree clockwise rotation.
        public static const ROTATE_270:String = "rotate270";

        // Specifies a 90 degree clockwise rotation.
        public static const ROTATE_90:String = "rotate90";
    }
}
