// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextBaseline.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TextBaseline
    {
        // Specifies an ascent baseline.
        public static const ASCENT:String = "ascent";

        // Specifies a descent baseline.
        public static const DESCENT:String = "descent";

        // Specifies an ideographic bottom baseline.
        public static const IDEOGRAPHIC_BOTTOM:String = "ideographicBottom";

        // Specifies an ideographic center baseline.
        public static const IDEOGRAPHIC_CENTER:String = "ideographicCenter";

        // Specifies an ideographic top baseline.
        public static const IDEOGRAPHIC_TOP:String = "ideographicTop";

        // Specifies a roman baseline.
        public static const ROMAN:String = "roman";

        // Specifies that the alignmentBaseline is the same as the dominantBaseline.
        public static const USE_DOMINANT_BASELINE:String = "useDominantBaseline";


    }
}
