// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextLineCreationResult.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TextLineCreationResult
    {
        // Indicates no line was created because all text in the block had already been broken.
        public static const COMPLETE:String = "complete";

        // Indicates the line was created with an emergency break because no break opportunity was available in the specified width.
        public static const EMERGENCY:String = "emergency";

        // Indicates no line was created because no text could fit in the specified width and fitSomething was not specified in the call to createTextLine().
        public static const INSUFFICIENT_WIDTH:String = "insufficientWidth";

        // Indicates the line was successfully broken.
        public static const SUCCESS:String = "success";
    }
}
