// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextLineValidity.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TextLineValidity
    {
        // Specifies that the line is invalid.
        public static const INVALID:String = "invalid";

        // Specifies that the text line is possibly invalid.
        public static const POSSIBLY_INVALID:String = "possiblyInvalid";

        // Specifies that the line is static, and that the connection between the line and the text block has been severed.
        public static const STATIC:String = "static";

        // Specifies that the text line is valid.
        public static const VALID:String = "valid";


    }
}
