// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TypographicCase.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.text.engine
{
    [API("662")]
    public final class TypographicCase
    {
        // Specifies that spacing is adjusted for uppercase characters on output.
        public static const CAPS:String = "caps";

        // Specifies that all lowercase characters use small-caps glyphs on output.
        public static const CAPS_AND_SMALL_CAPS:String = "capsAndSmallCaps";

        // Specifies default typographic case.
        public static const DEFAULT:String = "default";

        // Specifies that all characters use lowercase glyphs on output.
        public static const LOWERCASE:String = "lowercase";

        // Specifies that uppercase characters use small-caps glyphs on output.
        public static const SMALL_CAPS:String = "smallCaps";

        // Specifies that uppercase characters use title glyphs on output.
        public static const TITLE:String = "title";

        // Specifies that all characters use uppercase glyphs on output.
        public static const UPPERCASE:String = "uppercase";
    }
}
