context-menu-play = Oynat
context-menu-rewind = Geri Sar
context-menu-forward = İleri
context-menu-back = Geri
context-menu-quality-low = Kalite: Düşük
context-menu-quality-medium = Kalite: Orta
context-menu-quality-high = Kalite: Yüksek
context-menu-cut = Kes
context-menu-copy = Kopyala
context-menu-paste = Yapıştır
context-menu-delete = Sil
context-menu-select-all = Hepsini Seç
