root: true
env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  camelcase:
    - error
    - properties: never
      allow:
        - __webpack_public_path__
  curly: error
  eqeqeq: error
  no-constructor-return: error
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  prefer-const: error
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
overrides:
  # TypeScript rules.
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-non-null-assertion': 'off'
      '@typescript-eslint/consistent-type-assertions':
        - error
        - assertionStyle: 'as'
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
      # Disallow const enums, as they can't be used by consumers.
      # See https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls
      no-restricted-syntax:
        - error
        - selector: 'TSEnumDeclaration[const=true]'
          message: Don't declare const enums
